import { CreateIndexesOptions, IndexSpecification } from "mongodb";

import {
  arrayOf,
  arrayOfOrNull,
  boolean,
  booleanOrNull,
  numberOrNull,
  object,
  objectId,
  objectOrNull,
  string,
  stringOrNull,
} from "./json-schema/jsonSchemaTypes";

const collectionName = "formationsCatalogue";

const indexes: [IndexSpecification, CreateIndexesOptions][] = [];

const schema = object({
  _id: objectId(),
  cle_ministere_educatif: string(),
  cfd: string(),
  cfd_specialite: stringOrNull(),
  cfd_outdated: boolean(),
  cfd_date_fermeture: stringOrNull(),
  cfd_entree: stringOrNull(),
  nom_academie: string(),
  num_academie: string(),
  code_postal: string(),
  code_commune_insee: string(),
  num_departement: string(),
  nom_departement: string(),
  region: string(),
  localite: string(),
  nom: stringOrNull(),
  intitule_rco: string(),
  intitule_long: string(),
  intitule_court: string(),
  diplome: string(),
  niveau: string(),
  onisep_url: stringOrNull(),
  onisep_intitule: stringOrNull(),
  onisep_libelle_poursuite: stringOrNull(),
  onisep_lien_site_onisepfr: stringOrNull(),
  onisep_discipline: stringOrNull(),
  onisep_domaine_sousdomaine: stringOrNull(),
  rncp_code: stringOrNull(),
  rncp_intitule: stringOrNull(),
  rncp_eligible_apprentissage: booleanOrNull(),
  rncp_details: objectOrNull({
    date_fin_validite_enregistrement: stringOrNull(),
    active_inactive: stringOrNull(),
    etat_fiche_rncp: stringOrNull(),
    niveau_europe: stringOrNull(),
    code_type_certif: stringOrNull(),
    type_certif: stringOrNull(),
    ancienne_fiche: arrayOfOrNull(string()),
    nouvelle_fiche: arrayOfOrNull(string()),
    demande: numberOrNull(),
    certificateurs: arrayOfOrNull(
      object({
        certificateur: string(),
        siret_certificateur: stringOrNull(),
      })
    ),
    nsf_code: stringOrNull(),
    nsf_libelle: stringOrNull(),
    romes: arrayOf(
      object({
        rome: string(),
        libelle: string(),
      })
    ),

    blocs_competences: arrayOfOrNull(
      object({
        numero_bloc: string(),
        intitule: string(),
        liste_competences: string(),
        modalites_evaluation: stringOrNull(),
      })
    ),
    voix_acces: stringOrNull(),
    partenaires: arrayOfOrNull(
      object({
        Nom_Partenaire: string(),
        Siret_Partenaire: string(),
        Habilitation_Partenaire: string(),
      })
    ),
    rncp_outdated: boolean(),
  }),
  rome_codes: arrayOf(string()),
  periode: arrayOf(string()),
  capacite: stringOrNull(),
  duree: string(),
  duree_incoherente: boolean(),
  annee: string(),
  annee_incoherente: boolean(),
  published: boolean(),
  forced_published: boolean(),
  distance: numberOrNull(),
  lieu_formation_adresse: string(),
  lieu_formation_adresse_computed: stringOrNull(),
  lieu_formation_siret: stringOrNull(),
  id_rco_formation: string(),
  id_formation: string(),
  id_action: string(),
  ids_action: arrayOf(string()),
  id_certifinfo: string(),
  tags: arrayOf(string()),
  libelle_court: string(),
  niveau_formation_diplome: string(),
  distance_lieu_formation_etablissement_formateur: stringOrNull(),
  niveau_entree_obligatoire: numberOrNull(),
  entierement_a_distance: boolean(),
  france_competence_infos: stringOrNull(),
  catalogue_published: boolean(),
  date_debut: arrayOf(string()),
  date_fin: arrayOf(string()),
  modalites_entrees_sorties: arrayOf(boolean()),
  id_RCO: string(),
  etablissement_gestionnaire_id: string(),
  etablissement_gestionnaire_siret: string(),
  etablissement_gestionnaire_enseigne: stringOrNull(),
  etablissement_gestionnaire_uai: stringOrNull(),
  etablissement_gestionnaire_published: boolean(),
  etablissement_gestionnaire_habilite_rncp: booleanOrNull(),
  etablissement_gestionnaire_certifie_qualite: boolean(),
  etablissement_gestionnaire_adresse: string(),
  etablissement_gestionnaire_code_postal: string(),
  etablissement_gestionnaire_code_commune_insee: string(),
  etablissement_gestionnaire_localite: string(),
  etablissement_gestionnaire_complement_adresse: stringOrNull(),
  etablissement_gestionnaire_cedex: stringOrNull(),
  etablissement_gestionnaire_entreprise_raison_sociale: string(),
  etablissement_gestionnaire_region: string(),
  etablissement_gestionnaire_num_departement: string(),
  etablissement_gestionnaire_nom_departement: string(),
  etablissement_gestionnaire_nom_academie: string(),
  etablissement_gestionnaire_num_academie: string(),
  etablissement_gestionnaire_siren: string(),
  etablissement_gestionnaire_nda: stringOrNull(),
  etablissement_gestionnaire_date_creation: string(),
  etablissement_formateur_id: string(),
  etablissement_formateur_siret: string(),
  etablissement_formateur_enseigne: stringOrNull(),
  etablissement_formateur_uai: stringOrNull(),
  etablissement_formateur_published: boolean(),
  etablissement_formateur_habilite_rncp: booleanOrNull(),
  etablissement_formateur_certifie_qualite: boolean(),
  etablissement_formateur_adresse: string(),
  etablissement_formateur_code_postal: string(),
  etablissement_formateur_code_commune_insee: string(),
  etablissement_formateur_localite: string(),
  etablissement_formateur_complement_adresse: stringOrNull(),
  etablissement_formateur_cedex: stringOrNull(),
  etablissement_formateur_entreprise_raison_sociale: string(),
  etablissement_formateur_region: string(),
  etablissement_formateur_num_departement: string(),
  etablissement_formateur_nom_departement: string(),
  etablissement_formateur_nom_academie: string(),
  etablissement_formateur_num_academie: string(),
  etablissement_formateur_siren: string(),
  etablissement_formateur_nda: stringOrNull(),
  etablissement_formateur_date_creation: stringOrNull(),
  etablissement_reference: string(),
  etablissement_reference_published: boolean(),
  etablissement_reference_habilite_rncp: booleanOrNull(),
  etablissement_reference_certifie_qualite: boolean(),
  etablissement_reference_date_creation: stringOrNull(),
  bcn_mefs_10: arrayOf(
    object({
      mef10: string(),
      modalite: object({
        duree: string(),
        annee: string(),
      }),
    })
  ),
  lieu_formation_geo_coordonnees: string(),
  geo_coordonnees_etablissement_gestionnaire: stringOrNull(),
  geo_coordonnees_etablissement_formateur: stringOrNull(),
  idea_geo_coordonnees_etablissement: stringOrNull(),
  created_at: string(),
  last_update_at: string(),
  lieu_formation_geo_coordonnees_computed: stringOrNull(),
});

export default { schema, indexes, collectionName };
