import { CreateIndexesOptions, IndexSpecification } from "mongodb";
import {
  arrayOfOrNull,
  booleanOrNull,
  numberOrNull,
  object,
  objectId,
  objectOrNull,
  string,
  stringOrNull,
} from "shared";

const collectionName = "formationsCatalogue";

const indexes: [IndexSpecification, CreateIndexesOptions][] = [
  [{ cle_ministere_educatif: 1 }, { name: "cle_ministere_educatif", unique: true }],
  [{ intitule_long: 1 }, { name: "intitule_long" }],
  [{ cfd: 1 }, { name: "cfd" }],
  [{ rncp_code: 1 }, { name: "rncp_code" }],
  [{ etablissement_formateur_siret: 1, etablissement_formateur_uai: 1 }, { name: "etablissement_formateur_siret_uai" }],
  [
    { etablissement_gestionnaire_siret: 1, etablissement_gestionnaire_uai: 1 },
    { name: "etablissement_gestionnaire_siret_uai" },
  ],
  [{ etablissement_formateur_uai: 1 }, { name: "etablissement_formateur_uai" }],
  [{ etablissement_gestionnaire_uai: 1 }, { name: "etablissement_gestionnaire_uai" }],
];

const schema = object(
  {
    _id: objectId(),
    cle_ministere_educatif: string(),
    cfd: string(),
    cfd_specialite: stringOrNull(),
    cfd_outdated: booleanOrNull(),
    cfd_date_fermeture: stringOrNull(),
    cfd_entree: stringOrNull(),
    nom_academie: stringOrNull(),
    num_academie: stringOrNull(),
    code_postal: stringOrNull(),
    code_commune_insee: stringOrNull(),
    num_departement: stringOrNull(),
    nom_departement: stringOrNull(),
    region: stringOrNull(),
    localite: stringOrNull(),
    nom: stringOrNull(),
    intitule_rco: stringOrNull(),
    intitule_long: string(),
    intitule_court: stringOrNull(),
    diplome: stringOrNull(),
    niveau: stringOrNull(),
    onisep_url: stringOrNull(),
    onisep_intitule: stringOrNull(),
    onisep_libelle_poursuite: stringOrNull(),
    onisep_lien_site_onisepfr: stringOrNull(),
    onisep_discipline: stringOrNull(),
    onisep_domaine_sousdomaine: stringOrNull(),
    rncp_code: stringOrNull(),
    rncp_intitule: stringOrNull(),
    rncp_eligible_apprentissage: booleanOrNull(),
    rncp_details: objectOrNull({
      date_fin_validite_enregistrement: stringOrNull(),
      active_inactive: stringOrNull(),
      etat_fiche_rncp: stringOrNull(),
      niveau_europe: stringOrNull(),
      code_type_certif: stringOrNull(),
      type_certif: stringOrNull(),
      ancienne_fiche: arrayOfOrNull(stringOrNull()),
      nouvelle_fiche: arrayOfOrNull(stringOrNull()),
      demande: numberOrNull(),
      certificateurs: arrayOfOrNull(
        objectOrNull({
          certificateur: stringOrNull(),
          siret_certificateur: stringOrNull(),
        })
      ),
      nsf_code: stringOrNull(),
      nsf_libelle: stringOrNull(),
      romes: arrayOfOrNull(
        objectOrNull({
          rome: stringOrNull(),
          libelle: stringOrNull(),
        })
      ),

      blocs_competences: arrayOfOrNull(
        objectOrNull({
          numero_bloc: stringOrNull(),
          intitule: stringOrNull(),
          liste_competences: stringOrNull(),
          modalites_evaluation: stringOrNull(),
        })
      ),
      voix_acces: stringOrNull(),
      partenaires: arrayOfOrNull(
        objectOrNull({
          Nom_Partenaire: stringOrNull(),
          Siret_Partenaire: stringOrNull(),
          Habilitation_Partenaire: stringOrNull(),
        })
      ),
      rncp_outdated: booleanOrNull(),
    }),
    rome_codes: arrayOfOrNull(stringOrNull()),
    periode: arrayOfOrNull(stringOrNull()),
    capacite: stringOrNull(),
    duree: string(),
    duree_incoherente: booleanOrNull(),
    annee: string(),
    annee_incoherente: booleanOrNull(),
    published: booleanOrNull(),
    forced_published: booleanOrNull(),
    distance: numberOrNull(),
    lieu_formation_adresse: stringOrNull(),
    lieu_formation_adresse_computed: stringOrNull(),
    lieu_formation_siret: stringOrNull(),
    id_rco_formation: stringOrNull(),
    id_formation: stringOrNull(),
    id_action: stringOrNull(),
    ids_action: arrayOfOrNull(stringOrNull()),
    id_certifinfo: stringOrNull(),
    tags: arrayOfOrNull(stringOrNull()),
    libelle_court: stringOrNull(),
    niveau_formation_diplome: stringOrNull(),
    distance_lieu_formation_etablissement_formateur: stringOrNull(),
    niveau_entree_obligatoire: numberOrNull(),
    entierement_a_distance: booleanOrNull(),
    france_competence_infos: stringOrNull(),
    catalogue_published: booleanOrNull(),
    date_debut: arrayOfOrNull(stringOrNull()),
    date_fin: arrayOfOrNull(stringOrNull()),
    modalites_entrees_sorties: arrayOfOrNull(booleanOrNull()),
    id_RCO: stringOrNull(),
    etablissement_gestionnaire_id: stringOrNull(),
    etablissement_gestionnaire_siret: string(),
    etablissement_gestionnaire_enseigne: stringOrNull(),
    etablissement_gestionnaire_uai: stringOrNull(),
    etablissement_gestionnaire_published: booleanOrNull(),
    etablissement_gestionnaire_habilite_rncp: booleanOrNull(),
    etablissement_gestionnaire_certifie_qualite: booleanOrNull(),
    etablissement_gestionnaire_adresse: stringOrNull(),
    etablissement_gestionnaire_code_postal: stringOrNull(),
    etablissement_gestionnaire_code_commune_insee: stringOrNull(),
    etablissement_gestionnaire_localite: stringOrNull(),
    etablissement_gestionnaire_complement_adresse: stringOrNull(),
    etablissement_gestionnaire_cedex: stringOrNull(),
    etablissement_gestionnaire_entreprise_raison_sociale: stringOrNull(),
    etablissement_gestionnaire_region: stringOrNull(),
    etablissement_gestionnaire_num_departement: stringOrNull(),
    etablissement_gestionnaire_nom_departement: stringOrNull(),
    etablissement_gestionnaire_nom_academie: stringOrNull(),
    etablissement_gestionnaire_num_academie: stringOrNull(),
    etablissement_gestionnaire_siren: stringOrNull(),
    etablissement_gestionnaire_nda: stringOrNull(),
    etablissement_gestionnaire_date_creation: stringOrNull(),
    etablissement_formateur_id: stringOrNull(),
    etablissement_formateur_siret: string(),
    etablissement_formateur_enseigne: stringOrNull(),
    etablissement_formateur_uai: stringOrNull(),
    etablissement_formateur_published: booleanOrNull(),
    etablissement_formateur_habilite_rncp: booleanOrNull(),
    etablissement_formateur_certifie_qualite: booleanOrNull(),
    etablissement_formateur_adresse: stringOrNull(),
    etablissement_formateur_code_postal: stringOrNull(),
    etablissement_formateur_code_commune_insee: stringOrNull(),
    etablissement_formateur_localite: stringOrNull(),
    etablissement_formateur_complement_adresse: stringOrNull(),
    etablissement_formateur_cedex: stringOrNull(),
    etablissement_formateur_entreprise_raison_sociale: stringOrNull(),
    etablissement_formateur_region: stringOrNull(),
    etablissement_formateur_num_departement: stringOrNull(),
    etablissement_formateur_nom_departement: stringOrNull(),
    etablissement_formateur_nom_academie: stringOrNull(),
    etablissement_formateur_num_academie: stringOrNull(),
    etablissement_formateur_siren: stringOrNull(),
    etablissement_formateur_nda: stringOrNull(),
    etablissement_formateur_date_creation: stringOrNull(),
    etablissement_reference: stringOrNull(),
    etablissement_reference_published: booleanOrNull(),
    etablissement_reference_habilite_rncp: booleanOrNull(),
    etablissement_reference_certifie_qualite: booleanOrNull(),
    etablissement_reference_date_creation: stringOrNull(),
    bcn_mefs_10: arrayOfOrNull(
      objectOrNull({
        mef10: stringOrNull(),
        modalite: objectOrNull({
          duree: stringOrNull(),
          annee: stringOrNull(),
        }),
      })
    ),
    lieu_formation_geo_coordonnees: stringOrNull(),
    geo_coordonnees_etablissement_gestionnaire: stringOrNull(),
    geo_coordonnees_etablissement_formateur: stringOrNull(),
    idea_geo_coordonnees_etablissement: stringOrNull(),
    created_at: stringOrNull(),
    last_update_at: stringOrNull(),
    lieu_formation_geo_coordonnees_computed: stringOrNull(),
  },
  {
    required: [
      "cle_ministere_educatif",
      "cfd",
      "rncp_code",
      "duree",
      "annee",
      "intitule_long",
      "etablissement_gestionnaire_uai",
      "etablissement_gestionnaire_siret",
      "etablissement_formateur_uai",
      "etablissement_formateur_siret",
    ],
    additionalProperties: true,
  }
);

export default { schema, indexes, collectionName };
