import { ObjectId } from "mongodb";

import { organisationsDb } from "@/common/model/collections";

export const up = async () => {
  const now = new Date();
  await organisationsDb().insertMany([
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "AREFIE - HAUTS DE France",
      region_list: ["32"],
      telephone: "09 72 56 12 30",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "DES MISSIONS LOCALES DE CORSE",
      region_list: ["94"],
      telephone: "04 95 55 65 05",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "DES MISSIONS LOCALES NOUVELLE AQUITAINE",
      region_list: ["75"],
      telephone: "05 57 81 76 50",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "DES MISSIONS LOCALES BOURGOGNE - FRANCHE-COMTE",
      region_list: ["27"],
      telephone: "03 80 42 01 42",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "DES MISSIONS LOCALES D'ILE DE France",
      region_list: ["11"],
      telephone: "01 45 42 27 57",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "GRAND-EST",
      region_list: ["44"],
      telephone: "03 83 35 41 85",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "DES MISSIONS LOCALES DU CENTRE - VAL DE LOIRE",
      region_list: ["24"],
      telephone: "06 58 11 41 22",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "DES MISSIONS LOCALES DE BRETAGNE",
      region_list: ["53"],
      telephone: "02 30 96 65 32",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "MISSIONS LOCALES NORMANDIE",
      region_list: ["28"],
      telephone: "02 31 95 06 06",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "DES MISSIONS LOCALES DES PAYS DE LA LOIRE",
      region_list: ["52"],
      telephone: "0624671039",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "DES MISSIONS LOCALES D'OCCITANIE",
      region_list: ["76"],
      telephone: "04 67 73 27 35",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "AMILAURA - AUVERGNE - RHONE-ALPES",
      region_list: ["84"],
      telephone: "04 72 98 24 75",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "SUD PROVENCE - ALPES COTE D'AZUR",
      region_list: ["93"],
      telephone: "06 75 03 41 58",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "DES MISSIONS LOCALES OCEAN INDIEN",
      region_list: ["04", "06"],
      telephone: "02 62 32 46 92",
    },
    {
      _id: new ObjectId(),
      created_at: now,
      type: "ARML",
      nom: "ANTILLES-GUYANE",
      region_list: ["01", "02", "03", "978"],
      telephone: "0696 837 444",
    },
  ]);
};
