version: "2.4"
services:
  reverse_proxy:
    image: tableau_de_bord_reverse_proxy
    container_name: tableau_de_bord_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - tableau_de_bord_network
    depends_on:
      - server
      - ui

  ui:
    image: tableau_de_bord_ui
    container_name: tableau_de_bord_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - tableau_de_bord_network
    depends_on:
      - server

  server:
    image: tableau_de_bord_server
    container_name: tableau_de_bord_server
    build:
      context: server
    restart: unless-stopped
    networks:
      - tableau_de_bord_network
    depends_on:
      - mongodb
      - ftp
    environment:
      - TABLEAU_DE_BORD_MONGODB_URI=mongodb://mongodb:27017/flux-retour-cfas?retryWrites=true&w=majority
      - TABLEAU_DE_BORD_FTP_DIR=/ftp
      - TABLEAU_DE_BORD_OUTPUT_DIR=/data

  mongodb:
    image: mongo:5.0.2-focal
    container_name: tableau_de_bord_mongodb
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - tableau_de_bord_network

  ftp:
    image: tableau_de_bord_ftp
    container_name: tableau_de_bord_ftp
    mem_limit: 256m
    build:
      context: ftp
    restart: unless-stopped
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - tableau_de_bord_network

networks:
  tableau_de_bord_network:
    name: tableau_de_bord_network
