// Code postal pour l'étranger de type 99XXX
const CODE_POSTAL_FOREIGN_COUNTRY_ONLY_PATTERN = "^99[0-9]{3}$";
export const CODE_POSTAL_FOREIGN_COUNTRY_ONLY_REGEX = new RegExp(CODE_POSTAL_FOREIGN_COUNTRY_ONLY_PATTERN);
