export const QUERY_KEYS = {
  SEARCH_RESEAUX_CFA: "search-reseaux-cfas",
  SEARCH_USERS: "search-users",
  SEARCH_CFAS: "search-cfas",
  SEARCH_FORMATIONS: "search-formations",
  EFFECTIFS: "effectifs",
  CFAS: "cfas",
  DEPARTEMENT: "departement",
  REGIONS: "regions",
  ORGANISMES_APPARTENANCE: "organismes-appartenance",
  RESEAUX: "reseaux",
  GET_USER: "user-by-id",
  TOTAL_ORGANISMES: "total-organismes",
  FORMATION: "formation",
  EFFECTIFS_NATIONAL: "effectifs-national",
  EFFECTIF_PAR: {
    CFA: "effectifs-par-cfa",
    ANNEE_FORMATION: "effectifs-par-annee-formation",
    DEPARTEMENT: "effectifs-par-departement",
    FORMATION: "effectifs-par-formation",
    NIVEAU_FORMATION: "effectifs-par-niveau-formation",
    SIRET: "effectifs-par-siret",
  },
  SIGNALEMENT_ANOMALIE: "signalement anomalie",
  UPLOAD_HISTORY: "upload-history",
};
