export const QUERY_KEYS = {
  SEARCH_CFAS: "search-cfas",
  SEARCH_FORMATIONS: "search-formations",
  EFFECTIFS: "effectifs",
  CFAS: "cfas",
  DEPARTEMENT: "departement",
  REGIONS: "regions",
  RESEAUX: "reseaux",
  RESEAUX_CFAS: "reseaux-cfas",
  USERS: "users",
  TOTAL_ORGANISMES: "total-organismes",
  FORMATION: "formation",
  EFFECTIF_PAR: {
    CFA: "effectifs-par-cfa",
    ANNEE_FORMATION: "effectifs-par-annee-formation",
    DEPARTEMENT: "effectifs-par-departement",
    FORMATION: "effectifs-par-formation",
    NIVEAU_FORMATION: "effectifs-par-niveau-formation",
    SIRET: "effectifs-par-siret",
  },
};
