# Remove legacy backup CRON
- block:
    - name: Installation nfs-client package
      apt:
        name: nfs-client
      state: absent

    - name: Mount backup NFS partition
      ansible.posix.mount:
        src: "10.201.16.96:zpool-129542/fluxretourcfas"
        path: /mnt/backups
        opts: _netdev,mountproto=tcp
        state: mounted
        fstype: nfs
        boot: yes
      state: absent

    - name: Add mongodb backup cron
      cron:
        name: "backup mongodb each day at 04h00"
        minute: "0"
        hour: "4"
        job: "bash /opt/flux-retour-cfas/tools/backup-mongodb.sh >> /var/log/backup-mongodb.log 2>&1"
      state: absent

    - name: Add metabase backup cron"
      become: true
      cron:
        name: "backup metabase each day at 00h20"
        minute: "20"
        hour: "0"
        job: "bash /opt/flux-retour-cfas/tools/backup-metabase.sh >> /var/log/backup-metabase.log 2>&1"
      state: absent

  when: env_type == "production"
