- name: Add CRON to run jobs processing application data everyday at 5:30AM
  become: true
  cron:
    name: "Run daily jobs each day at 05h30"
    minute: "30"
    hour: "5"
    job: "bash /opt/flux-retour-cfas/tools/cron-data-jobs/run-daily-jobs.sh"

- name: Add CRON to run fiabilité analyses on data received in last 24hours everyday at 11:15AM
  become: true
  cron:
    name: "Run analyses fiabilité données reçues job each day at 11h15"
    minute: "15"
    hour: "11"
    job: "bash /opt/flux-retour-cfas/tools/cron-data-jobs/run-analyse-fiabilite-donnees-recues-job.sh"

- name: Add CRON to archive dossiersApprenants every 1rst day of the month at 12:45AM
  become: true
  cron:
    name: "Run archive dossiers apprenants & effectifs job each first day of month at 12h45"
    minute: "45"
    hour: "12"
    day: "1"
    job: "bash /opt/flux-retour-cfas/tools/cron-data-jobs/run-archive-job.sh"
