- name: Add CRON to run jobs processing application data everyday at 5:30AM
  become: true
  cron:
    name: "application data jobs"
    minute: "30"
    hour: "5"
    job: "bash /opt/flux-retour-cfas/tools/cron-data-jobs/run-data-jobs.sh"

- name: Add CRON to run fiabilité analyses on data received in last 24hours everyday at 11:15AM
  become: true
  cron:
    name: "Analyses fiabilité données reçues"
    minute: "15"
    hour: "11"
    job: "bash /opt/flux-retour-cfas/tools/cron-data-jobs/run-analyse-fiabilite-donnees-recues-job.sh"
