#Override containers for ovh environments
version: "2.4"
services:
  server:
    environment:
      - FLUX_RETOUR_CFAS_ENV=production
      - FLUX_RETOUR_CFAS_LOG_LEVEL=info
      - FLUX_RETOUR_CFAS_LOG_TYPE=json
      - FLUX_RETOUR_CFAS_LOG_STREAMS=stdout,mongodb,slack
      - FLUX_RETOUR_CFAS_LOG_DESTINATIONS=stdout,mongodb,slack
      - FLUX_RETOUR_CFAS_PUBLIC_URL=https://cfas.apprentissage.beta.gouv.fr
      - FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL={{ vault.FLUX_RETOUR_CFAS_SLACK_WEBHOOK_URL }}
      - FLUX_RETOUR_CFAS_AUTH_PASSWORD_HASH_ROUNDS={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_PASSWORD_HASH_ROUNDS }}
      - FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET_EXPIRES={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_USER_JWT_SECRET_EXPIRES }}
      # MongoDb
      - FLUX_RETOUR_CFAS_MONGODB_URI={{ vault[env_type].FLUX_RETOUR_CFAS_MONGODB_URI }}
      # APIs
      - FLUX_RETOUR_CFAS_TABLES_CORRESPONDANCES_ENDPOINT_URL=https://tables-correspondances.apprentissage.beta.gouv.fr/api
      - FLUX_RETOUR_CFAS_MNA_CATALOG_ENDPOINT_URL=https://catalogue.apprentissage.beta.gouv.fr/api
      - FLUX_RETOUR_CFAS_LBA_ENDPOINT_URL=http://labonnealternance.apprentissage.beta.gouv.fr/api
      # ADMIN
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_NAME }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PASSWORD }}
      - FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS={{ vault[env_type].FLUX_RETOUR_CFAS_USERS_DEFAULT_ADMIN_PERMISSIONS }}
      # OVH Storage
      - FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_USERNAME }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_PASSWORD }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_AUTH_URL={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_AUTH_URL }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_TENANT_ID }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_REGION={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_REGION }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_CONTAINER_NAME }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_ENCRYPTION_KEY={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_ENCRYPTION_KEY }}
      - FLUX_RETOUR_CFAS_OVH_STORAGE_URI={{ vault.FLUX_RETOUR_CFAS_OVH_STORAGE_URI }}
      - FLUX_RETOUR_CFAS_API_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_API_KEY }}
      - FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_ACTIVATION_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_PASSWORD_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_AUTH_ACTION_TOKEN_JWT_SECRET={{ vault[env_type].FLUX_RETOUR_CFAS_AUTH_ACTION_TOKEN_JWT_SECRET }}
      - FLUX_RETOUR_CFAS_SMTP_HOST={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_HOST }}
      - FLUX_RETOUR_CFAS_SMTP_PORT={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_PORT }}
      - FLUX_RETOUR_CFAS_SMTP_AUTH_USER={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_AUTH_USER }}
      - FLUX_RETOUR_CFAS_SMTP_AUTH_PASS={{ vault[env_type].FLUX_RETOUR_CFAS_SMTP_AUTH_PASS }}
      - FLUX_RETOUR_CFAS_API_ENTREPRISE_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_API_ENTREPRISE_KEY }}
      - FLUX_RETOUR_CFAS_ORGANISMES_CONSULTATION_API_KEY={{ vault[env_type].FLUX_RETOUR_CFAS_ORGANISMES_CONSULTATION_API_KEY }}
      - FLUX_RETOUR_CFAS_APP_NAME=Flux Retour Cfas
      - FLUX_RETOUR_CFAS_IS_OFFLINE=false
      - FLUX_RETOUR_CFAS_SENTRY_DSN=
      - SENTRY_AUTH_TOKEN={{ vault.SENTRY_AUTH_TOKEN }}

  ui:
    build:
      args:
        - NEXT_PUBLIC_ENV=production
        - NEXT_PUBLIC_BASE_URL=https://cfas.apprentissage.beta.gouv.fr
        - NEXT_PUBLIC_BASE_HOST=cfas.apprentissage.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_URL=https://cfas.apprentissage.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_SECRET_KEY={{ vault[env_type].NEXT_PUBLIC_METABASE_SECRET_KEY }}
        - SENTRY_AUTH_TOKEN={{ vault.SENTRY_AUTH_TOKEN }}

  metabase:
    environment:
      MB_SITE_URL: https://cfas.apprentissage.beta.gouv.fr/metabase
