export const STATUT_FIABILISATION_ORGANISME = {
  FIABLE: "FIABLE" as const,
  NON_FIABILISABLE_PB_COLLECTE: "NON_FIABILISABLE_PB_COLLECTE" as const,
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE" as const,
  NON_FIABILISABLE_UAI_VALIDEE: "NON_FIABILISABLE_UAI_VALIDEE" as const,
  NON_FIABILISABLE_INEXISTANT: "NON_FIABILISABLE_INEXISTANT" as const,
  A_CONTACTER: "A_CONTACTER" as const,
  INCONNU: "INCONNU" as const,
  INCONNU_INSCRIPTION: "INCONNU_INSCRIPTION" as const,
};

export const STATUT_FIABILISATION_API_ORGANISME = {
  FIABLE: "FIABLE" as const,
  NON_FIABLE: "NON_FIABLE" as const,
};

export const STATUT_FIABILISATION_COUPLES_UAI_SIRET = {
  FIABLE: "FIABLE" as const,
  A_FIABILISER: "A_FIABILISER" as const,
  NON_FIABILISABLE_INEXISTANT: "NON_FIABILISABLE_INEXISTANT" as const,
  NON_FIABILISABLE_PB_COLLECTE: "NON_FIABILISABLE_PB_COLLECTE" as const,
  NON_FIABILISABLE_UAI_VALIDEE: "NON_FIABILISABLE_UAI_VALIDEE" as const,
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE" as const,
};

export const STATUT_CREATION_ORGANISME = {
  ORGANISME_LIEU_FORMATION: "ORGANISME_LIEU_FORMATION" as const,
};
