export const RECHERCHER_ORGANISME_FORM_STATE = {
  INITIAL: "INITIAL",
  UAI_UNKNOWN: "UAI_UNKNOWN",
  UAI_NOT_FOUND: "UAI_NOT_FOUND",
  ONE_OR_MANY_ORGANISMES_FOUND: "ONE_OR_MANY_ORGANISMES_FOUND",
  ERROR: "ERROR",
};
