import { ACC_CONJOINT_MOTIF_ENUM } from "shared";

export const MOTIF_LABELS: Record<ACC_CONJOINT_MOTIF_ENUM, string> = {
  [ACC_CONJOINT_MOTIF_ENUM.MOBILITE]: "Mobilité",
  [ACC_CONJOINT_MOTIF_ENUM.LOGEMENT]: "Logement",
  [ACC_CONJOINT_MOTIF_ENUM.SANTE]: "Santé",
  [ACC_CONJOINT_MOTIF_ENUM.FINANCE]: "Finance",
  [ACC_CONJOINT_MOTIF_ENUM.ADMINISTRATIF]: "Administratif",
  [ACC_CONJOINT_MOTIF_ENUM.SOCIAL_FAMILIAL]: "Social / Familial",
  [ACC_CONJOINT_MOTIF_ENUM.REORIENTATION]: "Réorientation",
  [ACC_CONJOINT_MOTIF_ENUM.RECHERCHE_EMPLOI]: "Recherche d'emploi",
  [ACC_CONJOINT_MOTIF_ENUM.AUTRE]: "Autre",
};

export const MOTIF_EMOJIS: Partial<Record<ACC_CONJOINT_MOTIF_ENUM, string>> = {
  [ACC_CONJOINT_MOTIF_ENUM.RECHERCHE_EMPLOI]: "💼",
  [ACC_CONJOINT_MOTIF_ENUM.MOBILITE]: "🚗",
  [ACC_CONJOINT_MOTIF_ENUM.LOGEMENT]: "🏠",
  [ACC_CONJOINT_MOTIF_ENUM.SANTE]: "🩺",
  [ACC_CONJOINT_MOTIF_ENUM.ADMINISTRATIF]: "📂",
  [ACC_CONJOINT_MOTIF_ENUM.FINANCE]: "💶",
  [ACC_CONJOINT_MOTIF_ENUM.SOCIAL_FAMILIAL]: "👨‍👩‍👧",
  [ACC_CONJOINT_MOTIF_ENUM.REORIENTATION]: "🧭",
};
