name: NPM packages check
description: Analyse les dépendances NPM via mna-npm-check (protection supply chain)

runs:
  using: composite
  steps:
    - name: Clone mna-npm-check repository
      uses: actions/checkout@v6
      with:
        repository: mission-apprentissage/mna-npm-check
        path: mna-npm-check

    - name: Analyze NPM dependancies
      run: mna-npm-check/npm-check.sh -p .
      shell: bash
