import {
  CONNAISSANCE_ML_ENUM,
  PROBLEME_TYPE_ENUM,
  SITUATION_ENUM,
} from "shared/models/data/missionLocaleEffectif.model";

import type { SeedEmployeur, SeedFormation } from "../factories";
import type { SeedCommune } from "../hosts";

export const COMMUNES_CLICHY = {
  CLICHY: { code_postal: "92110", code_insee: "92024", commune: "Clichy", departement: "92", region: "11" },
  ASNIERES: {
    code_postal: "92600",
    code_insee: "92004",
    commune: "Asnières-sur-Seine",
    departement: "92",
    region: "11",
  },
  LEVALLOIS: {
    code_postal: "92300",
    code_insee: "92044",
    commune: "Levallois-Perret",
    departement: "92",
    region: "11",
  },
  GENNEVILLIERS: {
    code_postal: "92230",
    code_insee: "92036",
    commune: "Gennevilliers",
    departement: "92",
    region: "11",
  },
  SAINT_OUEN: {
    code_postal: "93400",
    code_insee: "93070",
    commune: "Saint-Ouen-sur-Seine",
    departement: "93",
    region: "11",
  },
  PARIS_17: {
    code_postal: "75017",
    code_insee: "75117",
    commune: "Paris 17e Arrondissement",
    departement: "75",
    region: "11",
  },
} satisfies Record<string, SeedCommune>;

export const RUES_CLICHY = [
  "RUE MARTRE",
  "BOULEVARD JEAN JAURES",
  "RUE DE NEUILLY",
  "RUE HENRI BARBUSSE",
  "RUE DU LANDY",
  "AVENUE DE LA PORTE DE CLICHY",
  "RUE VILLENEUVE",
  "RUE PIERRE CURIE",
  "RUE DES CAILLOUX",
  "RUE DAGOBERT",
];

export const FORMATIONS_CLICHY = {
  CUISINE: {
    cfd: "50022141",
    rncp: "RNCP26650",
    libelle_long: "CUISINE (CAP)",
    libelle_court: "CUISINE",
    niveau: "3",
    niveau_libelle: "3 (CAP...)",
    dureeMois: 24,
  },
  MCO: {
    cfd: "32031213",
    rncp: "RNCP34031",
    libelle_long: "MANAGEMENT COMMERCIAL OPERATIONNEL (BTS)",
    libelle_court: "MCO",
    niveau: "5",
    niveau_libelle: "5 (BTS, DEUST...)",
    dureeMois: 24,
  },
  BAC_PRO_MCV: {
    cfd: "40031213",
    rncp: "RNCP32208",
    libelle_long: "METIERS DU COMMERCE ET DE LA VENTE OPTION A ANIMATION ET GESTION DE L'ESPACE COMMERCIAL (BAC PRO)",
    libelle_court: "MET.COM.VENTE OP.A ANIM.GEST.ESP.COM",
    niveau: "4",
    niveau_libelle: "4 (BAC...)",
    dureeMois: 36,
  },
  COIFFURE: {
    cfd: "50033616",
    rncp: "RNCP34670",
    libelle_long: "METIERS DE LA COIFFURE (CAP)",
    libelle_court: "METIERS DE LA COIFFURE",
    niveau: "3",
    niveau_libelle: "3 (CAP...)",
    dureeMois: 24,
  },
  SIO_SLAM: {
    cfd: "32032612",
    rncp: "RNCP35340",
    libelle_long:
      "SERVICES INFORMATIQUES AUX ORGANISATIONS OPTION B SOLUTIONS LOGICIELLES ET APPLICATIONS METIERS (BTS)",
    libelle_court: "SIO OPTION B SLAM",
    niveau: "5",
    niveau_libelle: "5 (BTS, DEUST...)",
    dureeMois: 24,
  },
  DWWM: {
    cfd: "36T23201",
    rncp: "RNCP37674",
    libelle_long: "DEVELOPPEUR WEB ET WEB MOBILE (TP)",
    libelle_court: "DEVELOPPEUR WEB ET WEB MOBILE",
    niveau: "5",
    niveau_libelle: "5 (BTS, DEUST...)",
    dureeMois: 12,
  },
  BOULANGER: {
    cfd: "50022137",
    rncp: "RNCP37537",
    libelle_long: "BOULANGER (CAP)",
    libelle_court: "BOULANGER",
    niveau: "3",
    niveau_libelle: "3 (CAP...)",
    dureeMois: 24,
  },
  ESTHETIQUE: {
    cfd: "46033604",
    rncp: "RNCP37014",
    libelle_long: "ESTHETIQUE COSMETIQUE PARFUMERIE (BP)",
    libelle_court: "ESTHETIQUE COSMETIQUE PARFUMERIE",
    niveau: "4",
    niveau_libelle: "4 (BAC...)",
    dureeMois: 24,
  },
  BAC_PRO_MELEC: {
    cfd: "40025510",
    rncp: "RNCP37218",
    libelle_long: "METIERS DE L'ELECTRICITE ET DE SES ENVIRONNEMENTS CONNECTES (BAC PRO)",
    libelle_court: "MET.ELECT.ENVIRON.CONNECTES",
    niveau: "4",
    niveau_libelle: "4 (BAC...)",
    dureeMois: 36,
  },
  NDRC: {
    cfd: "32031212",
    rncp: "RNCP34030",
    libelle_long: "NEGOCIATION ET DIGITALISATION DE LA RELATION CLIENT (BTS)",
    libelle_court: "NDRC",
    niveau: "5",
    niveau_libelle: "5 (BTS, DEUST...)",
    dureeMois: 24,
  },
  EPC: {
    cfd: "50031224",
    rncp: "RNCP34947",
    libelle_long: "EQUIPIER POLYVALENT DU COMMERCE (CAP)",
    libelle_court: "EQUIPIER POLYVALENT DU COMMERCE",
    niveau: "3",
    niveau_libelle: "3 (CAP...)",
    dureeMois: 24,
  },
  ADVF: {
    cfd: "36T33201",
    rncp: "RNCP37715",
    libelle_long: "ASSISTANT DE VIE AUX FAMILLES (TP)",
    libelle_court: "ASSISTANT DE VIE AUX FAMILLES",
    niveau: "3",
    niveau_libelle: "3 (CAP...)",
    dureeMois: 12,
  },
} satisfies Record<string, SeedFormation & { dureeMois: number }>;

export const EMPLOYEURS_CLICHY = {
  BOULANGERIE: { siret: "90000001100019", denomination: "BOULANGERIE DU MARCHE", naf: "1071C" },
  SALON: { siret: "90000001200017", denomination: "SALON COIFF'ATTITUDE", naf: "9602A" },
  SUPERETTE: { siret: "90000001300015", denomination: "SUPER FRAIS CLICHY", naf: "4711D" },
  ELECTRICIEN: { siret: "90000001400013", denomination: "ELEC 92 SERVICES", naf: "4321A" },
  RESTAURANT: { siret: "90000001500010", denomination: "RESTAURANT LA TERRASSE", naf: "5610A" },
  WEBAGENCY: { siret: "90000001600018", denomination: "WEBAGENCY PARIS NORD", naf: "6201Z" },
  INSTITUT: { siret: "90000001700016", denomination: "INSTITUT BEAUTE ASNIERES", naf: "9602B" },
  GARAGE: { siret: "90000001800014", denomination: "GARAGE DES BATIGNOLLES", naf: "4520A" },
} satisfies Record<string, SeedEmployeur>;

export type CategorieClichy =
  | "mineur"
  | "rqth"
  | "confirme"
  | "rdv_whatsapp"
  | "rappel_whatsapp"
  | "collab_rupture"
  | "collab_en_contrat"
  | "a_traiter"
  | "contact_opportun"
  | "injoignable"
  | "injoignable_whatsapp"
  | "pas_besoin_whatsapp"
  | "traite"
  | "traite_collab";

export interface JeuneClichy {
  nom: string;
  prenom: string;
  sexe: "M" | "F";
  age: number;
  naissance: { jour: number; mois: number };
  commune: keyof typeof COMMUNES_CLICHY;
  deca?: boolean;
  cfa: "CFA_REAL_CAMPUS" | "CFA_AFTRAL";
  formation: keyof typeof FORMATIONS_CLICHY;
  employeur: keyof typeof EMPLOYEURS_CLICHY;
  joursDepuisRupture: number;
  moisDeContrat: number;
  categorie: CategorieClichy;
  rqth?: boolean;
  situation?: SITUATION_ENUM;
  situation_autre?: string;
  probleme_type?: PROBLEME_TYPE_ENUM;
  connaissance_ml?: CONNAISSANCE_ML_ENUM;
  commentaires?: string;
}

export const JEUNES_CLICHY: JeuneClichy[] = [
  {
    nom: "DUPUIS",
    prenom: "Lisa",
    sexe: "F",
    age: 17,
    naissance: { jour: 14, mois: 3 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "COIFFURE",
    employeur: "SALON",
    joursDepuisRupture: 12,
    moisDeContrat: 3,
    categorie: "mineur",
  },
  {
    nom: "LEFEVRE",
    prenom: "Mathis",
    sexe: "M",
    age: 16,
    naissance: { jour: 2, mois: 5 },
    commune: "CLICHY",
    deca: true,
    cfa: "CFA_REAL_CAMPUS",
    formation: "BOULANGER",
    employeur: "BOULANGERIE",
    joursDepuisRupture: 25,
    moisDeContrat: 2,
    categorie: "mineur",
  },
  {
    nom: "LEROY",
    prenom: "Margaux",
    sexe: "F",
    age: 20,
    naissance: { jour: 21, mois: 5 },
    commune: "LEVALLOIS",
    cfa: "CFA_REAL_CAMPUS",
    formation: "MCO",
    employeur: "SUPERETTE",
    joursDepuisRupture: 18,
    moisDeContrat: 8,
    categorie: "rqth",
    rqth: true,
  },
  {
    nom: "FLEURY",
    prenom: "Sacha",
    sexe: "M",
    age: 19,
    naissance: { jour: 9, mois: 8 },
    commune: "ASNIERES",
    cfa: "CFA_AFTRAL",
    formation: "BAC_PRO_MELEC",
    employeur: "ELECTRICIEN",
    joursDepuisRupture: 30,
    moisDeContrat: 11,
    categorie: "rqth",
    rqth: true,
  },
  {
    nom: "RICHARD",
    prenom: "Assia",
    sexe: "F",
    age: 21,
    naissance: { jour: 30, mois: 1 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "NDRC",
    employeur: "WEBAGENCY",
    joursDepuisRupture: 9,
    moisDeContrat: 12,
    categorie: "confirme",
  },
  {
    nom: "THOMAS",
    prenom: "Samuel",
    sexe: "M",
    age: 18,
    naissance: { jour: 17, mois: 6 },
    commune: "GENNEVILLIERS",
    cfa: "CFA_REAL_CAMPUS",
    formation: "CUISINE",
    employeur: "RESTAURANT",
    joursDepuisRupture: 21,
    moisDeContrat: 5,
    categorie: "confirme",
  },
  {
    nom: "MERCIER",
    prenom: "Nour",
    sexe: "F",
    age: 22,
    naissance: { jour: 5, mois: 9 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "SIO_SLAM",
    employeur: "WEBAGENCY",
    joursDepuisRupture: 40,
    moisDeContrat: 14,
    categorie: "rdv_whatsapp",
  },
  {
    nom: "POIRIER",
    prenom: "Jules",
    sexe: "M",
    age: 19,
    naissance: { jour: 25, mois: 2 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "EPC",
    employeur: "SUPERETTE",
    joursDepuisRupture: 55,
    moisDeContrat: 4,
    categorie: "rappel_whatsapp",
    situation: SITUATION_ENUM.CONTACTE_SANS_RETOUR,
  },
  {
    nom: "BOYER",
    prenom: "Sarah",
    sexe: "F",
    age: 17,
    naissance: { jour: 12, mois: 12 },
    commune: "ASNIERES",
    cfa: "CFA_AFTRAL",
    formation: "BAC_PRO_MCV",
    employeur: "SUPERETTE",
    joursDepuisRupture: 15,
    moisDeContrat: 13,
    categorie: "collab_rupture",
  },
  {
    nom: "ROCHE",
    prenom: "Matéo",
    sexe: "M",
    age: 20,
    naissance: { jour: 3, mois: 4 },
    commune: "GENNEVILLIERS",
    cfa: "CFA_AFTRAL",
    formation: "BAC_PRO_MELEC",
    employeur: "ELECTRICIEN",
    joursDepuisRupture: 0,
    moisDeContrat: 6,
    categorie: "collab_en_contrat",
  },
  {
    nom: "MARCHAL",
    prenom: "Kenza",
    sexe: "F",
    age: 17,
    naissance: { jour: 28, mois: 7 },
    commune: "CLICHY",
    deca: true,
    cfa: "CFA_REAL_CAMPUS",
    formation: "ESTHETIQUE",
    employeur: "INSTITUT",
    joursDepuisRupture: 33,
    moisDeContrat: 10,
    categorie: "mineur",
  },
  {
    nom: "MEYER",
    prenom: "Enzo",
    sexe: "M",
    age: 18,
    naissance: { jour: 19, mois: 10 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "DWWM",
    employeur: "WEBAGENCY",
    joursDepuisRupture: 7,
    moisDeContrat: 9,
    categorie: "contact_opportun",
  },
  {
    nom: "ROUSSEAU",
    prenom: "Justine",
    sexe: "F",
    age: 20,
    naissance: { jour: 8, mois: 3 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "MCO",
    employeur: "SUPERETTE",
    joursDepuisRupture: 14,
    moisDeContrat: 12,
    categorie: "a_traiter",
  },
  {
    nom: "ROYER",
    prenom: "Ismaël",
    sexe: "M",
    age: 21,
    naissance: { jour: 1, mois: 6 },
    commune: "SAINT_OUEN",
    deca: true,
    cfa: "CFA_REAL_CAMPUS",
    formation: "BAC_PRO_MELEC",
    employeur: "ELECTRICIEN",
    joursDepuisRupture: 22,
    moisDeContrat: 7,
    categorie: "a_traiter",
  },
  {
    nom: "ROYER",
    prenom: "Chloé",
    sexe: "F",
    age: 22,
    naissance: { jour: 14, mois: 2 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "ADVF",
    employeur: "RESTAURANT",
    joursDepuisRupture: 28,
    moisDeContrat: 3,
    categorie: "a_traiter",
  },
  {
    nom: "RIVIERE",
    prenom: "Enzo",
    sexe: "M",
    age: 18,
    naissance: { jour: 23, mois: 9 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "BOULANGER",
    employeur: "BOULANGERIE",
    joursDepuisRupture: 35,
    moisDeContrat: 15,
    categorie: "a_traiter",
  },
  {
    nom: "BARON",
    prenom: "Nour",
    sexe: "F",
    age: 22,
    naissance: { jour: 11, mois: 11 },
    commune: "LEVALLOIS",
    deca: true,
    cfa: "CFA_REAL_CAMPUS",
    formation: "NDRC",
    employeur: "WEBAGENCY",
    joursDepuisRupture: 41,
    moisDeContrat: 6,
    categorie: "a_traiter",
  },
  {
    nom: "PEREZ",
    prenom: "Thomas",
    sexe: "M",
    age: 20,
    naissance: { jour: 6, mois: 1 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "SIO_SLAM",
    employeur: "GARAGE",
    joursDepuisRupture: 47,
    moisDeContrat: 10,
    categorie: "a_traiter",
  },
  {
    nom: "AUBERT",
    prenom: "Mathilde",
    sexe: "F",
    age: 18,
    naissance: { jour: 30, mois: 8 },
    commune: "GENNEVILLIERS",
    cfa: "CFA_REAL_CAMPUS",
    formation: "BAC_PRO_MCV",
    employeur: "SUPERETTE",
    joursDepuisRupture: 52,
    moisDeContrat: 14,
    categorie: "a_traiter",
  },
  {
    nom: "HENRY",
    prenom: "Jules",
    sexe: "M",
    age: 21,
    naissance: { jour: 17, mois: 4 },
    commune: "PARIS_17",
    deca: true,
    cfa: "CFA_REAL_CAMPUS",
    formation: "DWWM",
    employeur: "WEBAGENCY",
    joursDepuisRupture: 60,
    moisDeContrat: 8,
    categorie: "a_traiter",
  },
  {
    nom: "LEMAIRE",
    prenom: "Justine",
    sexe: "F",
    age: 18,
    naissance: { jour: 24, mois: 12 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "ESTHETIQUE",
    employeur: "INSTITUT",
    joursDepuisRupture: 68,
    moisDeContrat: 11,
    categorie: "a_traiter",
  },
  {
    nom: "NOEL",
    prenom: "Matéo",
    sexe: "M",
    age: 20,
    naissance: { jour: 7, mois: 7 },
    commune: "ASNIERES",
    cfa: "CFA_AFTRAL",
    formation: "CUISINE",
    employeur: "RESTAURANT",
    joursDepuisRupture: 19,
    moisDeContrat: 9,
    categorie: "a_traiter",
  },
  {
    nom: "LACROIX",
    prenom: "Inès",
    sexe: "F",
    age: 22,
    naissance: { jour: 15, mois: 5 },
    commune: "ASNIERES",
    cfa: "CFA_AFTRAL",
    formation: "NDRC",
    employeur: "ELECTRICIEN",
    joursDepuisRupture: 26,
    moisDeContrat: 5,
    categorie: "a_traiter",
  },
  {
    nom: "JULIEN",
    prenom: "Tom",
    sexe: "M",
    age: 19,
    naissance: { jour: 2, mois: 3 },
    commune: "GENNEVILLIERS",
    cfa: "CFA_AFTRAL",
    formation: "COIFFURE",
    employeur: "SALON",
    joursDepuisRupture: 75,
    moisDeContrat: 12,
    categorie: "a_traiter",
  },
  {
    nom: "LAURENT",
    prenom: "Charlotte",
    sexe: "F",
    age: 19,
    naissance: { jour: 10, mois: 10 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "MCO",
    employeur: "SUPERETTE",
    joursDepuisRupture: 38,
    moisDeContrat: 7,
    categorie: "injoignable",
    situation: SITUATION_ENUM.CONTACTE_SANS_RETOUR,
    commentaires: "Deux appels sans réponse, message vocal laissé.",
  },
  {
    nom: "BRUNET",
    prenom: "Axel",
    sexe: "M",
    age: 19,
    naissance: { jour: 20, mois: 1 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "BAC_PRO_MELEC",
    employeur: "ELECTRICIEN",
    joursDepuisRupture: 45,
    moisDeContrat: 9,
    categorie: "injoignable_whatsapp",
    situation: SITUATION_ENUM.CONTACTE_SANS_RETOUR,
    commentaires: "Numéro sonne dans le vide. Relance WhatsApp envoyée.",
  },
  {
    nom: "MORIN",
    prenom: "Candice",
    sexe: "F",
    age: 21,
    naissance: { jour: 4, mois: 8 },
    commune: "LEVALLOIS",
    deca: true,
    cfa: "CFA_REAL_CAMPUS",
    formation: "EPC",
    employeur: "SUPERETTE",
    joursDepuisRupture: 50,
    moisDeContrat: 4,
    categorie: "pas_besoin_whatsapp",
    situation: SITUATION_ENUM.CONTACTE_SANS_RETOUR,
    commentaires: "Pas de réponse au téléphone ni au mail.",
  },
  {
    nom: "DUBOIS",
    prenom: "Adrien",
    sexe: "M",
    age: 20,
    naissance: { jour: 27, mois: 2 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "BOULANGER",
    employeur: "BOULANGERIE",
    joursDepuisRupture: 64,
    moisDeContrat: 13,
    categorie: "injoignable",
    situation: SITUATION_ENUM.CONTACTE_SANS_RETOUR,
    commentaires: "Mail envoyé le mois dernier, sans retour.",
  },
  {
    nom: "GAILLARD",
    prenom: "Justine",
    sexe: "F",
    age: 19,
    naissance: { jour: 13, mois: 6 },
    commune: "SAINT_OUEN",
    cfa: "CFA_REAL_CAMPUS",
    formation: "COIFFURE",
    employeur: "SALON",
    joursDepuisRupture: 80,
    moisDeContrat: 6,
    categorie: "injoignable",
    situation: SITUATION_ENUM.CONTACTE_SANS_RETOUR,
    commentaires: "Trois tentatives d'appel à des horaires différents.",
  },
  {
    nom: "MARTIN",
    prenom: "Quentin",
    sexe: "M",
    age: 18,
    naissance: { jour: 28, mois: 11 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "BAC_PRO_MCV",
    employeur: "SUPERETTE",
    joursDepuisRupture: 20,
    moisDeContrat: 8,
    categorie: "traite",
    situation: SITUATION_ENUM.RDV_PRIS,
    connaissance_ml: CONNAISSANCE_ML_ENUM.NON_CONNU,
    commentaires: "RDV fixé jeudi 10h avec la conseillère. Souhaite retrouver un employeur rapidement.",
  },
  {
    nom: "CARRE",
    prenom: "Candice",
    sexe: "F",
    age: 20,
    naissance: { jour: 9, mois: 4 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "ADVF",
    employeur: "RESTAURANT",
    joursDepuisRupture: 31,
    moisDeContrat: 10,
    categorie: "traite",
    situation: SITUATION_ENUM.RDV_PRIS,
    connaissance_ml: CONNAISSANCE_ML_ENUM.CONNU_NON_ACCOMPAGNE,
    commentaires: "Déjà inscrite en 2024. Reprise de contact, RDV la semaine prochaine.",
  },
  {
    nom: "ROBERT",
    prenom: "Nolan",
    sexe: "M",
    age: 21,
    naissance: { jour: 16, mois: 9 },
    commune: "LEVALLOIS",
    deca: true,
    cfa: "CFA_REAL_CAMPUS",
    formation: "DWWM",
    employeur: "WEBAGENCY",
    joursDepuisRupture: 36,
    moisDeContrat: 11,
    categorie: "traite",
    situation: SITUATION_ENUM.NOUVEAU_PROJET,
    connaissance_ml: CONNAISSANCE_ML_ENUM.NON_CONNU,
    commentaires: "Souhaite se réorienter vers la cybersécurité. Orientation vers un atelier projet.",
  },
  {
    nom: "AUBERT",
    prenom: "Alice",
    sexe: "F",
    age: 19,
    naissance: { jour: 22, mois: 5 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "ESTHETIQUE",
    employeur: "INSTITUT",
    joursDepuisRupture: 44,
    moisDeContrat: 15,
    categorie: "traite",
    situation: SITUATION_ENUM.DEJA_ACCOMPAGNE,
    connaissance_ml: CONNAISSANCE_ML_ENUM.DEJA_ACCOMPAGNE_ACTIVEMENT,
    commentaires: "Suivie en Garantie jeunes, la conseillère référente est informée de la rupture.",
  },
  {
    nom: "COUSIN",
    prenom: "Nathan",
    sexe: "M",
    age: 19,
    naissance: { jour: 1, mois: 12 },
    commune: "GENNEVILLIERS",
    cfa: "CFA_REAL_CAMPUS",
    formation: "CUISINE",
    employeur: "RESTAURANT",
    joursDepuisRupture: 58,
    moisDeContrat: 7,
    categorie: "traite",
    situation: SITUATION_ENUM.NOUVEAU_CONTRAT,
    connaissance_ml: CONNAISSANCE_ML_ENUM.NON_CONNU,
    commentaires: "A signé un nouveau contrat d'apprentissage dans une autre brasserie.",
  },
  {
    nom: "MARTIN",
    prenom: "Lola",
    sexe: "F",
    age: 22,
    naissance: { jour: 19, mois: 7 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "NDRC",
    employeur: "WEBAGENCY",
    joursDepuisRupture: 62,
    moisDeContrat: 9,
    categorie: "traite",
    situation: SITUATION_ENUM.CHERCHE_CONTRAT,
    connaissance_ml: CONNAISSANCE_ML_ENUM.NON_CONNU,
    commentaires: "Cherche seule via son réseau, ne souhaite pas d'accompagnement pour le moment.",
  },
  {
    nom: "LEMAIRE",
    prenom: "Paul",
    sexe: "M",
    age: 19,
    naissance: { jour: 31, mois: 3 },
    commune: "CLICHY",
    deca: true,
    cfa: "CFA_REAL_CAMPUS",
    formation: "BAC_PRO_MELEC",
    employeur: "ELECTRICIEN",
    joursDepuisRupture: 70,
    moisDeContrat: 12,
    categorie: "traite",
    situation: SITUATION_ENUM.REORIENTATION,
    connaissance_ml: CONNAISSANCE_ML_ENUM.NON_CONNU,
    commentaires: "Reprend un bac pro en lycée à la rentrée.",
  },
  {
    nom: "PAUL",
    prenom: "Célia",
    sexe: "F",
    age: 20,
    naissance: { jour: 8, mois: 8 },
    commune: "PARIS_17",
    cfa: "CFA_REAL_CAMPUS",
    formation: "SIO_SLAM",
    employeur: "GARAGE",
    joursDepuisRupture: 85,
    moisDeContrat: 5,
    categorie: "traite",
    situation: SITUATION_ENUM.COORDONNEES_INCORRECT,
    probleme_type: PROBLEME_TYPE_ENUM.COORDONNEES_INCORRECTES,
    connaissance_ml: CONNAISSANCE_ML_ENUM.NON_CONNU,
    commentaires: "Numéro attribué à une autre personne. CFA contacté pour mise à jour.",
  },
  {
    nom: "VASSEUR",
    prenom: "Samuel",
    sexe: "M",
    age: 21,
    naissance: { jour: 3, mois: 2 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "MCO",
    employeur: "SUPERETTE",
    joursDepuisRupture: 95,
    moisDeContrat: 10,
    categorie: "traite",
    situation: SITUATION_ENUM.INJOIGNABLE_APRES_RELANCES,
    probleme_type: PROBLEME_TYPE_ENUM.JEUNE_INJOIGNABLE,
    connaissance_ml: CONNAISSANCE_ML_ENUM.NON_CONNU,
    commentaires: "Cinq relances sur six semaines, dossier clos.",
  },
  {
    nom: "DUVAL",
    prenom: "Amandine",
    sexe: "F",
    age: 18,
    naissance: { jour: 26, mois: 10 },
    commune: "CLICHY",
    cfa: "CFA_REAL_CAMPUS",
    formation: "ADVF",
    employeur: "RESTAURANT",
    joursDepuisRupture: 100,
    moisDeContrat: 4,
    categorie: "traite",
    situation: SITUATION_ENUM.AUTRE,
    situation_autre: "Déménagement à Lyon, orientée vers la Mission Locale de Lyon.",
    connaissance_ml: CONNAISSANCE_ML_ENUM.NON_CONNU,
    commentaires: "A quitté le département, transfert de dossier proposé.",
  },
  {
    nom: "REMY",
    prenom: "Axel",
    sexe: "M",
    age: 20,
    naissance: { jour: 6, mois: 6 },
    commune: "ASNIERES",
    cfa: "CFA_AFTRAL",
    formation: "BAC_PRO_MCV",
    employeur: "SUPERETTE",
    joursDepuisRupture: 48,
    moisDeContrat: 13,
    categorie: "traite_collab",
    situation: SITUATION_ENUM.RDV_PRIS,
    connaissance_ml: CONNAISSANCE_ML_ENUM.NON_CONNU,
    commentaires: "Demande du CFA reçue, RDV pris avec le jeune et point prévu avec la référente CFA.",
  },
  {
    nom: "DUVAL",
    prenom: "Juliette",
    sexe: "F",
    age: 19,
    naissance: { jour: 12, mois: 4 },
    commune: "ASNIERES",
    cfa: "CFA_AFTRAL",
    formation: "NDRC",
    employeur: "ELECTRICIEN",
    joursDepuisRupture: 66,
    moisDeContrat: 8,
    categorie: "traite",
    situation: SITUATION_ENUM.DEJA_ACCOMPAGNE,
    connaissance_ml: CONNAISSANCE_ML_ENUM.DEJA_ACCOMPAGNE_ACTIVEMENT,
    commentaires: "Déjà suivie, la rupture était anticipée.",
  },
];
