const statutsTest = [
  {
    ine_apprenant: "12345",
    nom_apprenant: "testNom",
    prenom_apprenant: "testPrenom",
    ne_pas_solliciter: false,
    email_contact: "testemail_contact@test.fr",
    nom_representant_legal: "testnom_representant_legal",
    tel_representant_legal: "testtel_representant_legal",
    tel2_representant_legal: "testtel2_representant_legal",
    id_formation: "testid_formation",
    libelle_court_formation: "testlibelle_court_formation",
    libelle_long_formation: "testlibelle_long_formation",
    uai_etablissement: "testuai_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 1,
    date_metier_mise_a_jour_statut: Date.now(),
  },
  {
    ine_apprenant: "6789",
    nom_apprenant: "test2Nom",
    prenom_apprenant: "test2Prenom",
    ne_pas_solliciter: true,
    email_contact: "test2email_contact@test.fr",
    id_formation: "test2id_formation",
    uai_etablissement: "testuai_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 1,
  },
  {
    nom_apprenant: "test3Nom",
    prenom_apprenant: "test3Prenom",
    ne_pas_solliciter: true,
    email_contact: "test3email_contact@test.fr",
    id_formation: "test3id_formation",
    uai_etablissement: "testuai_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 2,
  },
];

const statutsTestUpdate = [
  {
    ine_apprenant: "12345",
    nom_apprenant: "testNom",
    prenom_apprenant: "testPrenom",
    ne_pas_solliciter: false,
    email_contact: "testemail_contact@test.fr",
    nom_representant_legal: "testnom_representant_legal",
    tel_representant_legal: "testtel_representant_legal",
    tel2_representant_legal: "testtel2_representant_legal",
    id_formation: "testid_formation",
    libelle_court_formation: "testlibelle_court_formation",
    libelle_long_formation: "testlibelle_long_formation",
    uai_etablissement: "testuai_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 2,
    date_metier_mise_a_jour_statut: Date.now(),
  },
  {
    ine_apprenant: "6789",
    nom_apprenant: "test2Nom",
    prenom_apprenant: "test2Prenom",
    ne_pas_solliciter: true,
    email_contact: "test2email_contact@test.fr",
    id_formation: "test2id_formation",
    uai_etablissement: "testuai_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 2,
  },
  {
    nom_apprenant: "test3Nom",
    prenom_apprenant: "test3Prenom",
    ne_pas_solliciter: true,
    email_contact: "test3email_contact@test.fr",
    id_formation: "test3id_formation",
    uai_etablissement: "testuai_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 1,
  },
  {
    ine_apprenant: "99999",
    nom_apprenant: "nouveauNom",
    prenom_apprenant: "nouveauPrenom",
    ne_pas_solliciter: false,
    email_contact: "nouvelEmail@email.fr",
    id_formation: "nouvelleFormation",
    uai_etablissement: "testuai_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 1,
  },
];

const simpleStatut = {
  ine_apprenant: "12345",
  nom_apprenant: "testNom",
  prenom_apprenant: "testPrenom",
  ne_pas_solliciter: false,
  email_contact: "testemail_contact@test.fr",
  nom_representant_legal: "testnom_representant_legal",
  tel_representant_legal: "testtel_representant_legal",
  tel2_representant_legal: "testtel2_representant_legal",
  id_formation: "testid_formation",
  libelle_court_formation: "testlibelle_court_formation",
  libelle_long_formation: "testlibelle_long_formation",
  uai_etablissement: "testuai_etablissement",
  nom_etablissement: "testnom_etablissement",
  statut_apprenant: 3,
  date_metier_mise_a_jour_statut: Date.now(),
};

const simpleStatutBadUpdate = {
  ine_apprenant: "12345",
  nom_apprenant: "testNom",
  prenom_apprenant: "testPrenom",
  ne_pas_solliciter: false,
  email_contact: "testemail_contact@test.fr",
  nom_representant_legal: "testnom_representant_legal",
  tel_representant_legal: "testtel_representant_legal",
  tel2_representant_legal: "testtel2_representant_legal",
  id_formation: "testid_formation",
  libelle_court_formation: "testlibelle_court_formation",
  libelle_long_formation: "testlibelle_long_formation",
  uai_etablissement: "testuai_etablissement",
  nom_etablissement: "testnom_etablissement",
  statut_apprenant: 1,
};

const statutsStatsTest = [
  {
    ine_apprenant: "12345",
    nom_apprenant: "testNom",
    prenom_apprenant: "testPrenom",
    ne_pas_solliciter: false,
    email_contact: "testemail_contact@test.fr",
    nom_representant_legal: "testnom_representant_legal",
    tel_representant_legal: "testtel_representant_legal",
    tel2_representant_legal: "testtel2_representant_legal",
    id_formation: "testid_formation",
    libelle_court_formation: "testlibelle_court_formation",
    libelle_long_formation: "testlibelle_long_formation",
    uai_etablissement: "testuai_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 1,
  },
  {
    ine_apprenant: "6789",
    nom_apprenant: "test2Nom",
    prenom_apprenant: "test2Prenom",
    ne_pas_solliciter: true,
    email_contact: "test2email_contact@test.fr",
    id_formation: "test2id_formation",
    uai_etablissement: "testuai_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 1,
  },
  {
    nom_apprenant: "test3Nom",
    prenom_apprenant: "test3Prenom",
    ne_pas_solliciter: true,
    email_contact: "test3email_contact@test.fr",
    id_formation: "test3id_formation",
    uai_etablissement: "testuai2_etablissement",
    nom_etablissement: "testnom_etablissement",
    statut_apprenant: 2,
  },
];

module.exports = {
  statutsTest,
  statutsTestUpdate,
  simpleStatut,
  simpleStatutBadUpdate,
  statutsStatsTest,
};
