export const ACADEMIES = {
  "01": { nom: "Paris", code: 1 },
  "02": { nom: "Aix-Marseille", code: 2 },
  "03": { nom: "Besançon", code: 3 },
  "04": { nom: "Bordeaux", code: 4 },
  "06": { nom: "Clermont-Ferrand", code: 6 },
  "07": { nom: "Dijon", code: 7 },
  "08": { nom: "Grenoble", code: 8 },
  "09": { nom: "Lille", code: 9 },
  10: { nom: "Lyon", code: 10 },
  11: { nom: "Montpellier", code: 11 },
  12: { nom: "Nancy-Metz", code: 12 },
  13: { nom: "Poitiers", code: 13 },
  14: { nom: "Rennes", code: 14 },
  15: { nom: "Strasbourg", code: 15 },
  16: { nom: "Toulouse", code: 16 },
  17: { nom: "Nantes", code: 17 },
  18: { nom: "Orléans-Tours", code: 18 },
  19: { nom: "Reims", code: 19 },
  20: { nom: "Amiens", code: 20 },
  22: { nom: "Limoges", code: 22 },
  23: { nom: "Nice", code: 23 },
  24: { nom: "Créteil", code: 24 },
  25: { nom: "Versailles", code: 25 },
  27: { nom: "Corse", code: 27 },
  28: { nom: "La Réunion", code: 28 },
  31: { nom: "Martinique", code: 31 },
  32: { nom: "Guadeloupe", code: 32 },
  33: { nom: "Guyane", code: 33 },
  43: { nom: "Mayotte", code: 43 },
  70: { nom: "Normandie", code: 70 },
};
