export default {
  10: {
    nom_dept: "Aube",
    code_dept: "10",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Reims",
    num_academie: 19,
  },
  11: {
    nom_dept: "Aude",
    code_dept: "11",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Montpellier",
    num_academie: 11,
  },
  12: {
    nom_dept: "Aveyron",
    code_dept: "12",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Toulouse",
    num_academie: 16,
  },
  13: {
    nom_dept: "Bouches-du-Rhône",
    code_dept: "13",
    nom_region: "Provence-Alpes-Côte d'Azur",
    code_region: "93",
    nom_academie: "Aix-Marseille",
    num_academie: 2,
  },
  14: {
    nom_dept: "Calvados",
    code_dept: "14",
    nom_region: "Normandie",
    code_region: "28",
    nom_academie: "Normandie",
    num_academie: 70,
  },
  15: {
    nom_dept: "Cantal",
    code_dept: "15",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Clermont-Ferrand",
    num_academie: 6,
  },
  16: {
    nom_dept: "Charente",
    code_dept: "16",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Poitiers",
    num_academie: 13,
  },
  17: {
    nom_dept: "Charente-Maritime",
    code_dept: "17",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Poitiers",
    num_academie: 13,
  },
  18: {
    nom_dept: "Cher",
    code_dept: "18",
    nom_region: "Centre-Val de Loire",
    code_region: "24",
    nom_academie: "Orléans-Tours",
    num_academie: 18,
  },
  19: {
    nom_dept: "Corrèze",
    code_dept: "19",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Limoges",
    num_academie: 22,
  },
  21: {
    nom_dept: "Côte-d'Or",
    code_dept: "21",
    nom_region: "Bourgogne-Franche-Comté",
    code_region: "27",
    nom_academie: "Dijon",
    num_academie: 7,
  },
  22: {
    nom_dept: "Côtes-d'Armor",
    code_dept: "22",
    nom_region: "Bretagne",
    code_region: "53",
    nom_academie: "Rennes",
    num_academie: 14,
  },
  23: {
    nom_dept: "Creuse",
    code_dept: "23",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Limoges",
    num_academie: 22,
  },
  24: {
    nom_dept: "Dordogne",
    code_dept: "24",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Bordeaux",
    num_academie: 4,
  },
  25: {
    nom_dept: "Doubs",
    code_dept: "25",
    nom_region: "Bourgogne-Franche-Comté",
    code_region: "27",
    nom_academie: "Besançon",
    num_academie: 3,
  },
  26: {
    nom_dept: "Drôme",
    code_dept: "26",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Grenoble",
    num_academie: 8,
  },
  27: {
    nom_dept: "Eure",
    code_dept: "27",
    nom_region: "Normandie",
    code_region: "28",
    nom_academie: "Normandie",
    num_academie: 70,
  },
  28: {
    nom_dept: "Eure-et-Loir",
    code_dept: "28",
    nom_region: "Centre-Val de Loire",
    code_region: "24",
    nom_academie: "Orléans-Tours",
    num_academie: 18,
  },
  29: {
    nom_dept: "Finistère",
    code_dept: "29",
    nom_region: "Bretagne",
    code_region: "53",
    nom_academie: "Rennes",
    num_academie: 14,
  },
  30: {
    nom_dept: "Gard",
    code_dept: "30",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Montpellier",
    num_academie: 11,
  },
  31: {
    nom_dept: "Haute-Garonne",
    code_dept: "31",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Toulouse",
    num_academie: 16,
  },
  32: {
    nom_dept: "Gers",
    code_dept: "32",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Toulouse",
    num_academie: 16,
  },
  33: {
    nom_dept: "Gironde",
    code_dept: "33",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Bordeaux",
    num_academie: 4,
  },
  34: {
    nom_dept: "Hérault",
    code_dept: "34",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Montpellier",
    num_academie: 11,
  },
  35: {
    nom_dept: "Ille-et-Vilaine",
    code_dept: "35",
    nom_region: "Bretagne",
    code_region: "53",
    nom_academie: "Rennes",
    num_academie: 14,
  },
  36: {
    nom_dept: "Indre",
    code_dept: "36",
    nom_region: "Centre-Val de Loire",
    code_region: "24",
    nom_academie: "Orléans-Tours",
    num_academie: 18,
  },
  37: {
    nom_dept: "Indre-et-Loire",
    code_dept: "37",
    nom_region: "Centre-Val de Loire",
    code_region: "24",
    nom_academie: "Orléans-Tours",
    num_academie: 18,
  },
  38: {
    nom_dept: "Isère",
    code_dept: "38",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Grenoble",
    num_academie: 8,
  },
  39: {
    nom_dept: "Jura",
    code_dept: "39",
    nom_region: "Bourgogne-Franche-Comté",
    code_region: "27",
    nom_academie: "Besançon",
    num_academie: 3,
  },
  40: {
    nom_dept: "Landes",
    code_dept: "40",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Bordeaux",
    num_academie: 4,
  },
  41: {
    nom_dept: "Loir-et-Cher",
    code_dept: "41",
    nom_region: "Centre-Val de Loire",
    code_region: "24",
    nom_academie: "Orléans-Tours",
    num_academie: 18,
  },
  42: {
    nom_dept: "Loire",
    code_dept: "42",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Lyon",
    num_academie: 10,
  },
  43: {
    nom_dept: "Haute-Loire",
    code_dept: "43",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Clermont-Ferrand",
    num_academie: 6,
  },
  44: {
    nom_dept: "Loire-Atlantique",
    code_dept: "44",
    nom_region: "Pays de la Loire",
    code_region: "52",
    nom_academie: "Nantes",
    num_academie: 17,
  },
  45: {
    nom_dept: "Loiret",
    code_dept: "45",
    nom_region: "Centre-Val de Loire",
    code_region: "24",
    nom_academie: "Orléans-Tours",
    num_academie: 18,
  },
  46: {
    nom_dept: "Lot",
    code_dept: "46",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Toulouse",
    num_academie: 16,
  },
  47: {
    nom_dept: "Lot-et-Garonne",
    code_dept: "47",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Bordeaux",
    num_academie: 4,
  },
  48: {
    nom_dept: "Lozère",
    code_dept: "48",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Montpellier",
    num_academie: 11,
  },
  49: {
    nom_dept: "Maine-et-Loire",
    code_dept: "49",
    nom_region: "Pays de la Loire",
    code_region: "52",
    nom_academie: "Nantes",
    num_academie: 17,
  },
  50: {
    nom_dept: "Manche",
    code_dept: "50",
    nom_region: "Normandie",
    code_region: "28",
    nom_academie: "Normandie",
    num_academie: 70,
  },
  51: {
    nom_dept: "Marne",
    code_dept: "51",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Reims",
    num_academie: 19,
  },
  52: {
    nom_dept: "Haute-Marne",
    code_dept: "52",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Reims",
    num_academie: 19,
  },
  53: {
    nom_dept: "Mayenne",
    code_dept: "53",
    nom_region: "Pays de la Loire",
    code_region: "52",
    nom_academie: "Nantes",
    num_academie: 17,
  },
  54: {
    nom_dept: "Meurthe-et-Moselle",
    code_dept: "54",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Nancy-Metz",
    num_academie: 12,
  },
  55: {
    nom_dept: "Meuse",
    code_dept: "55",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Nancy-Metz",
    num_academie: 12,
  },
  56: {
    nom_dept: "Morbihan",
    code_dept: "56",
    nom_region: "Bretagne",
    code_region: "53",
    nom_academie: "Rennes",
    num_academie: 14,
  },
  57: {
    nom_dept: "Moselle",
    code_dept: "57",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Nancy-Metz",
    num_academie: 12,
  },
  58: {
    nom_dept: "Nièvre",
    code_dept: "58",
    nom_region: "Bourgogne-Franche-Comté",
    code_region: "27",
    nom_academie: "Dijon",
    num_academie: 7,
  },
  59: {
    nom_dept: "Nord",
    code_dept: "59",
    nom_region: "Hauts-de-France",
    code_region: "32",
    nom_academie: "Lille",
    num_academie: 9,
  },
  60: {
    nom_dept: "Oise",
    code_dept: "60",
    nom_region: "Hauts-de-France",
    code_region: "32",
    nom_academie: "Amiens",
    num_academie: 20,
  },
  61: {
    nom_dept: "Orne",
    code_dept: "61",
    nom_region: "Normandie",
    code_region: "28",
    nom_academie: "Normandie",
    num_academie: 70,
  },
  62: {
    nom_dept: "Pas-de-Calais",
    code_dept: "62",
    nom_region: "Hauts-de-France",
    code_region: "32",
    nom_academie: "Lille",
    num_academie: 9,
  },
  63: {
    nom_dept: "Puy-de-Dôme",
    code_dept: "63",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Clermont-Ferrand",
    num_academie: 6,
  },
  64: {
    nom_dept: "Pyrénées-Atlantiques",
    code_dept: "64",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Bordeaux",
    num_academie: 4,
  },
  65: {
    nom_dept: "Hautes-Pyrénées",
    code_dept: "65",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Toulouse",
    num_academie: 16,
  },
  66: {
    nom_dept: "Pyrénées-Orientales",
    code_dept: "66",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Montpellier",
    num_academie: 11,
  },
  67: {
    nom_dept: "Bas-Rhin",
    code_dept: "67",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Strasbourg",
    num_academie: 15,
  },
  68: {
    nom_dept: "Haut-Rhin",
    code_dept: "68",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Strasbourg",
    num_academie: 15,
  },
  69: {
    nom_dept: "Rhône",
    code_dept: "69",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Lyon",
    num_academie: 10,
  },
  70: {
    nom_dept: "Haute-Saône",
    code_dept: "70",
    nom_region: "Bourgogne-Franche-Comté",
    code_region: "27",
    nom_academie: "Besançon",
    num_academie: 3,
  },
  71: {
    nom_dept: "Saône-et-Loire",
    code_dept: "71",
    nom_region: "Bourgogne-Franche-Comté",
    code_region: "27",
    nom_academie: "Dijon",
    num_academie: 7,
  },
  72: {
    nom_dept: "Sarthe",
    code_dept: "72",
    nom_region: "Pays de la Loire",
    code_region: "52",
    nom_academie: "Nantes",
    num_academie: 17,
  },
  73: {
    nom_dept: "Savoie",
    code_dept: "73",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Grenoble",
    num_academie: 8,
  },
  74: {
    nom_dept: "Haute-Savoie",
    code_dept: "74",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Grenoble",
    num_academie: 8,
  },
  75: {
    nom_dept: "Paris",
    code_dept: "75",
    nom_region: "Île-de-France",
    code_region: "11",
    nom_academie: "Paris",
    num_academie: 1,
  },
  76: {
    nom_dept: "Seine-Maritime",
    code_dept: "76",
    nom_region: "Normandie",
    code_region: "28",
    nom_academie: "Normandie",
    num_academie: 70,
  },
  77: {
    nom_dept: "Seine-et-Marne",
    code_dept: "77",
    nom_region: "Île-de-France",
    code_region: "11",
    nom_academie: "Créteil",
    num_academie: 24,
  },
  78: {
    nom_dept: "Yvelines",
    code_dept: "78",
    nom_region: "Île-de-France",
    code_region: "11",
    nom_academie: "Versailles",
    num_academie: 25,
  },
  79: {
    nom_dept: "Deux-Sèvres",
    code_dept: "79",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Poitiers",
    num_academie: 13,
  },
  80: {
    nom_dept: "Somme",
    code_dept: "80",
    nom_region: "Hauts-de-France",
    code_region: "32",
    nom_academie: "Amiens",
    num_academie: 20,
  },
  81: {
    nom_dept: "Tarn",
    code_dept: "81",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Toulouse",
    num_academie: 16,
  },
  82: {
    nom_dept: "Tarn-et-Garonne",
    code_dept: "82",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Toulouse",
    num_academie: 16,
  },
  83: {
    nom_dept: "Var",
    code_dept: "83",
    nom_region: "Provence-Alpes-Côte d'Azur",
    code_region: "93",
    nom_academie: "Nice",
    num_academie: 23,
  },
  84: {
    nom_dept: "Vaucluse",
    code_dept: "84",
    nom_region: "Provence-Alpes-Côte d'Azur",
    code_region: "93",
    nom_academie: "Aix-Marseille",
    num_academie: 2,
  },
  85: {
    nom_dept: "Vendée",
    code_dept: "85",
    nom_region: "Pays de la Loire",
    code_region: "52",
    nom_academie: "Nantes",
    num_academie: 17,
  },
  86: {
    nom_dept: "Vienne",
    code_dept: "86",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Poitiers",
    num_academie: 13,
  },
  87: {
    nom_dept: "Haute-Vienne",
    code_dept: "87",
    nom_region: "Nouvelle-Aquitaine",
    code_region: "75",
    nom_academie: "Limoges",
    num_academie: 22,
  },
  88: {
    nom_dept: "Vosges",
    code_dept: "88",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Nancy-Metz",
    num_academie: 12,
  },
  89: {
    nom_dept: "Yonne",
    code_dept: "89",
    nom_region: "Bourgogne-Franche-Comté",
    code_region: "27",
    nom_academie: "Dijon",
    num_academie: 7,
  },
  90: {
    nom_dept: "Territoire de Belfort",
    code_dept: "90",
    nom_region: "Bourgogne-Franche-Comté",
    code_region: "27",
    nom_academie: "Besançon",
    num_academie: 3,
  },
  91: {
    nom_dept: "Essonne",
    code_dept: "91",
    nom_region: "Île-de-France",
    code_region: "11",
    nom_academie: "Versailles",
    num_academie: 25,
  },
  92: {
    nom_dept: "Hauts-de-Seine",
    code_dept: "92",
    nom_region: "Île-de-France",
    code_region: "11",
    nom_academie: "Versailles",
    num_academie: 25,
  },
  93: {
    nom_dept: "Seine-Saint-Denis",
    code_dept: "93",
    nom_region: "Île-de-France",
    code_region: "11",
    nom_academie: "Créteil",
    num_academie: 24,
  },
  94: {
    nom_dept: "Val-de-Marne",
    code_dept: "94",
    nom_region: "Île-de-France",
    code_region: "11",
    nom_academie: "Créteil",
    num_academie: 24,
  },
  95: {
    nom_dept: "Val-d'Oise",
    code_dept: "95",
    nom_region: "Île-de-France",
    code_region: "11",
    nom_academie: "Versailles",
    num_academie: 25,
  },
  971: {
    nom_dept: "Guadeloupe",
    code_dept: "971",
    nom_region: "Guadeloupe",
    code_region: "01",
    nom_academie: "Guadeloupe",
    num_academie: 32,
  },
  972: {
    nom_dept: "Martinique",
    code_dept: "972",
    nom_region: "Martinique",
    code_region: "02",
    nom_academie: "Martinique",
    num_academie: 31,
  },
  973: {
    nom_dept: "Guyane",
    code_dept: "973",
    nom_region: "Guyane",
    code_region: "03",
    nom_academie: "Guyane",
    num_academie: 33,
  },
  974: {
    nom_dept: "La Réunion",
    code_dept: "974",
    nom_region: "La Réunion",
    code_region: "04",
    nom_academie: "La Réunion",
    num_academie: 28,
  },
  976: {
    nom_dept: "Mayotte",
    code_dept: "976",
    nom_region: "Mayotte",
    code_region: "06",
    nom_academie: "Mayotte",
    num_academie: 43,
  },
  "01": {
    nom_dept: "Ain",
    code_dept: "01",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Lyon",
    num_academie: 10,
  },
  "02": {
    nom_dept: "Aisne",
    code_dept: "02",
    nom_region: "Hauts-de-France",
    code_region: "32",
    nom_academie: "Amiens",
    num_academie: 20,
  },
  "03": {
    nom_dept: "Allier",
    code_dept: "03",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Clermont-Ferrand",
    num_academie: 6,
  },
  "04": {
    nom_dept: "Alpes-de-Haute-Provence",
    code_dept: "04",
    nom_region: "Provence-Alpes-Côte d'Azur",
    code_region: "93",
    nom_academie: "Aix-Marseille",
    num_academie: 2,
  },
  "05": {
    nom_dept: "Hautes-Alpes",
    code_dept: "05",
    nom_region: "Provence-Alpes-Côte d'Azur",
    code_region: "93",
    nom_academie: "Aix-Marseille",
    num_academie: 2,
  },
  "06": {
    nom_dept: "Alpes-Maritimes",
    code_dept: "06",
    nom_region: "Provence-Alpes-Côte d'Azur",
    code_region: "93",
    nom_academie: "Nice",
    num_academie: 23,
  },
  "07": {
    nom_dept: "Ardèche",
    code_dept: "07",
    nom_region: "Auvergne-Rhône-Alpes",
    code_region: "84",
    nom_academie: "Grenoble",
    num_academie: 8,
  },
  "08": {
    nom_dept: "Ardennes",
    code_dept: "08",
    nom_region: "Grand Est",
    code_region: "44",
    nom_academie: "Reims",
    num_academie: 19,
  },
  "09": {
    nom_dept: "Ariège",
    code_dept: "09",
    nom_region: "Occitanie",
    code_region: "76",
    nom_academie: "Toulouse",
    num_academie: 16,
  },
  "2A": {
    nom_dept: "Corse-du-Sud",
    code_dept: "2A",
    nom_region: "Corse",
    code_region: "94",
    nom_academie: "Corse",
    num_academie: 27,
  },
  "2B": {
    nom_dept: "Haute-Corse",
    code_dept: "2B",
    nom_region: "Corse",
    code_region: "94",
    nom_academie: "Corse",
    num_academie: 27,
  },
};
