export const STATUT_FIABILISATION_ORGANISME = {
  FIABLE: "FIABLE" as const,
  NON_FIABILISABLE_PB_COLLECTE: "NON_FIABILISABLE_PB_COLLECTE" as const,
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE" as const,
  NON_FIABILISABLE_MAPPING: "NON_FIABILISABLE_MAPPING" as const,
  A_CONTACTER: "A_CONTACTER" as const,
  INCONNU: "INCONNU" as const,
};

export const STATUT_FIABILISATION_COUPLES_UAI_SIRET = {
  FIABLE: "FIABLE" as const,
  A_FIABILISER: "A_FIABILISER" as const,
  NON_FIABILISABLE_PB_COLLECTE: "NON_FIABILISABLE_PB_COLLECTE" as const,
  NON_FIABILISABLE_MAPPING: "NON_FIABILISABLE_MAPPING" as const,
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE" as const,
};
