export const STATUT_FIABILISATION_ORGANISME = {
  FIABLE: "FIABLE" as const,
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE" as const,
  NON_FIABILISABLE_MAPPING: "NON_FIABILISABLE_MAPPING" as const,
  INCONNU: "INCONNU" as const,
  FIABILISE: "FIABILISE" as const, // TODO A supprimer une fois BDD clean
};

export const STATUT_FIABILISATION_COUPLES_UAI_SIRET = {
  FIABLE: "FIABLE" as const,
  A_FIABILISER: "A_FIABILISER" as const,
  NON_FIABILISABLE_MAPPING: "NON_FIABILISABLE_MAPPING" as const,
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE" as const,

  INCONNU: "INCONNU" as const, // TODO A supprimer une fois BDD clean
  DEJA_FIABLE: "DEJA_FIABLE" as const, // TODO A supprimer une fois BDD clean
};
