export const STATUT_FIABILISATION_ORGANISME = {
  FIABLE: "FIABLE",
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE",
  NON_FIABILISABLE_MAPPING: "NON_FIABILISABLE_MAPPING",
  INCONNU: "INCONNU",

  FIABILISE: "FIABILISE", // TODO A supprimer une fois BDD clean
};

export const STATUT_FIABILISATION_COUPLES_UAI_SIRET = {
  FIABLE: "FIABLE",
  A_FIABILISER: "A_FIABILISER",
  NON_FIABILISABLE_MAPPING: "NON_FIABILISABLE_MAPPING",
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE",

  INCONNU: "INCONNU", // TODO A supprimer une fois BDD clean
  DEJA_FIABLE: "DEJA_FIABLE", // TODO A supprimer une fois BDD clean
};
