export const STATUT_FIABILISATION_ORGANISME = {
  FIABLE: "FIABLE",
  FIABILISE: "FIABILISE",
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE",
  NON_FIABILISABLE_MAPPING: "NON_FIABILISABLE_MAPPING",
  INCONNU: "INCONNU",
  SANS_SIRET: "SANS_SIRET",
};

export const STATUT_FIABILISATION_COUPLES_UAI_SIRET = {
  DEJA_FIABLE: "DEJA_FIABLE",
  A_FIABILISER: "A_FIABILISER",
  NON_FIABILISABLE_MAPPING: "NON_FIABILISABLE_MAPPING",
  NON_FIABILISABLE_UAI_NON_VALIDEE: "NON_FIABILISABLE_UAI_NON_VALIDEE",
  INCONNU: "INCONNU",
};
