/**
 * Noms des types d'organismes d'appartenance des utilisateurs possibles
 */
export const ORGANISMES_APPARTENANCE = {
  TETE_DE_RESEAU: "TÊTE DE RÉSEAU",
  ACADEMIE: "ACADÉMIE",
  DRAAF: "DRAAF",
  CARIF_OREF: "CARIF OREF",
  DREETS: "DREETS",
  DEETS: "DEETS",
  DDETS: "DDETS",
  CONSEIL_REGIONAL: "CONSEIL RÉGIONAL",
  OPCO: "OPCO",
  ERP: "ERP",
  AUTRE: "AUTRE",
  POLE_EMPLOI: "PÔLE EMPLOI",
  MISSION_LOCALE: "MISSION LOCALE",
  CELLULE_APPRENTISSAGE: "CELLULE APPRENTISSAGE",
  ORGANISME_FORMATION: "ORGANISME DE FORMATION",
};

/**
 * Statuts possibles du compte utilisateur
 */
export const USER_ACCOUNT_STATUS = {
  PENDING_EMAIL_VALIDATION: "PENDING_EMAIL_VALIDATION",
  PENDING_PASSWORD_SETUP: "PENDING_PASSWORD_SETUP",
  PENDING_PERMISSIONS_SETUP: "PENDING_PERMISSIONS_SETUP",
  PENDING_ADMIN_VALIDATION: "PENDING_ADMIN_VALIDATION",
  CONFIRMED: "CONFIRMED",
  DIRECT_PENDING_PASSWORD_SETUP: "DIRECT_PENDING_PASSWORD_SETUP",
};
