FROM node:16.15.0-stretch

WORKDIR /app

VOLUME /data
EXPOSE 5000

# esbuild est (re)-installé manuellement pour avoir le bon driver linux (vs le driver macos ou windows)
RUN yarn add esbuild

CMD ["yarn", "start:dev"]
