version: "3.8"

services:
  smtp:
    image: axllent/mailpit:latest
    deploy:
      resources:
        limits:
          memory: 128m
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        window: 360s
        delay: 30s
        # Max 24hours
        max_attempts: 240
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - mna_network
    volumes:
      - /opt/app/data/smtp:/data
      - /opt/app/configs/mailpit/auth:/auth
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - MP_UI_AUTH_FILE=/auth
      - MP_WEBROOT=/smtp/
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.json.{{product_name}}.{{env_type}}.smtp
        fluentd-async: "true"
