#!/usr/bin/env bash

set -euo pipefail

export PRODUCT_NAME="tdb"
export REPO_NAME="flux-retour-cfas"
export DATABASE_NAME="tdb"

export BIN_DIR="$(dirname -- "$( readlink -f -- "$0"; )")"
export BIN_SHARED_DIR="$BIN_DIR/shared"
export ROOT_DIR="$(dirname "${BIN_DIR}")"
export SCRIPTS_DIR="$BIN_DIR/scripts"
export SCRIPTS_SHARED_DIR="$BIN_SHARED_DIR/scripts"

. "${BIN_DIR}/commands.sh"

################################################################################
################################################################################
# Main program                                                                 #
################################################################################
################################################################################

readonly command=${1:-}

if [ -z "${CI:-}" ]; then
  _dispatch "dev:dependencies:check"
fi

case "$command" in
  ""|help|-h|--help) _help; exit 0 ;;
  *) shift; _dispatch "$command" "${@:-}" ;;
esac
