#!/usr/bin/env bash

set -euo pipefail

export PRODUCT_NAME="tdb"
export REPO_NAME="flux-retour-cfas"
export DATABASE_NAME="tdb"

export BIN_DIR="$(dirname -- "$( readlink -f -- "$0"; )")"
export BIN_SHARED_DIR="$BIN_DIR/shared"
export ROOT_DIR="$(dirname "${BIN_DIR}")"
export SCRIPT_DIR="$BIN_DIR/scripts"
export SCRIPT_SHARED_DIR="$BIN_SHARED_DIR/scripts"

. "${BIN_DIR}/commands.sh"

################################################################################
################################################################################
# Main program                                                                 #
################################################################################
################################################################################

readonly command=${1:-}
if [ -z "$command" ]; then
  _help
fi
shift

if [[ `command -v $command` != $command ]]; then
  echo "Err: Command '$command' not found"
  echo
  _help
fi

if [ -z "${CI:-}" ]; then
  dev:dependencies:check
fi

$command "$@"
