import { object, boolean } from "../../../json-schema/jsonSchemaTypes.js";

const adresseLocker = object({
  numero: boolean(),
  repetition_voie: boolean(),
  voie: boolean(),
  complement: boolean(),
  code_postal: boolean(),
  code_insee: boolean(),
  commune: boolean(),
  departement: boolean(),
  region: boolean(),
  academie: boolean(),
  complete: boolean(),
  pays: boolean(),
});

export const effectifFieldsLockerSchema = object({
  apprenant: object({
    ine: boolean(),
    nom: boolean(),
    prenom: boolean(),
    sexe: boolean(),
    date_de_naissance: boolean(),
    nationalite: boolean(),
    handicap: boolean(),
    courriel: boolean(),
    telephone: boolean(),
    adresse: adresseLocker,
    historique_statut: boolean(),
    contrats: boolean(),

    code_postal_de_naissance: boolean(),
    regime_scolaire: boolean(),
    inscription_sportif_haut_niveau: boolean(),
    situation_avant_contrat: boolean(),
    derniere_situation: boolean(),
    dernier_organisme_uai: boolean(),
    dernier_diplome: boolean(),
    mineur_emancipe: boolean(),
    representant_legal: object({
      nom: boolean(),
      prenom: boolean(),
      pcs: boolean(),
      meme_adresse: boolean(),
      adresse: adresseLocker,
      courriel: boolean(),
      telephone: boolean(),
    }),
  }),
  formation: object({
    cfd: boolean(),
    rncp: boolean(),
    libelle_long: boolean(),
    niveau: boolean(),
    niveau_libelle: boolean(),
    periode: boolean(),
    annee: boolean(),
    date_debut_formation: boolean(),
    date_fin_formation: boolean(),
    date_obtention_diplome: boolean(),
    duree_formation_relle: boolean(),
  }),
});

const defaultAdresseLock = (lockAtCreate = false) => ({
  numero: lockAtCreate,
  repetition_voie: lockAtCreate,
  voie: lockAtCreate,
  complement: lockAtCreate,
  code_postal: lockAtCreate,
  code_insee: lockAtCreate,
  commune: lockAtCreate,
  departement: lockAtCreate,
  region: lockAtCreate,
  academie: lockAtCreate,
  complete: lockAtCreate,
  pays: lockAtCreate,
});

// Default value
export function defaultValuesEffectifFieldsLocker(lockAtCreate = false) {
  return {
    apprenant: {
      ine: lockAtCreate,
      nom: true,
      prenom: true,
      sexe: lockAtCreate,
      date_de_naissance: lockAtCreate,
      nationalite: lockAtCreate,
      handicap: lockAtCreate,
      courriel: lockAtCreate,
      telephone: lockAtCreate,
      adresse: defaultAdresseLock(lockAtCreate),
      historique_statut: lockAtCreate,
      contrats: lockAtCreate,
      code_postal_de_naissance: lockAtCreate,
      regime_scolaire: lockAtCreate,
      inscription_sportif_haut_niveau: lockAtCreate,
      situation_avant_contrat: lockAtCreate,
      derniere_situation: lockAtCreate,
      dernier_organisme_uai: lockAtCreate,
      dernier_diplome: lockAtCreate,
      mineur_emancipe: lockAtCreate,
      representant_legal: {
        nom: lockAtCreate,
        prenom: lockAtCreate,
        pcs: lockAtCreate,
        meme_adresse: lockAtCreate,
        adresse: defaultAdresseLock(lockAtCreate),
        courriel: lockAtCreate,
        telephone: lockAtCreate,
      },
    },
    formation: {
      cfd: true,
      rncp: lockAtCreate,
      libelle_long: lockAtCreate,
      niveau: lockAtCreate,
      niveau_libelle: lockAtCreate,
      periode: lockAtCreate,
      annee: lockAtCreate,
      date_debut_formation: lockAtCreate,
      date_fin_formation: lockAtCreate,
      date_obtention_diplome: lockAtCreate,
      duree_formation_relle: lockAtCreate,
    },
  };
}
