export const legacySchema = {
  additionalProperties: true,
  bsonType: "object",
  properties: {
    _computed: {
      additionalProperties: false,
      bsonType: "object",
      description: "Propriétés calculées ou récupérées d'autres collections",
      properties: {
        formation: {
          additionalProperties: false,
          bsonType: "object",
          properties: {
            codes_rome: {
              bsonType: "array",
              items: {
                bsonType: "string",
              },
            },
            opcos: {
              bsonType: "array",
              items: {
                bsonType: "string",
              },
            },
          },
        },
        organisme: {
          additionalProperties: false,
          bsonType: "object",
          properties: {
            academie: {
              bsonType: "string",
              enum: [
                "1",
                "2",
                "3",
                "4",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "22",
                "23",
                "24",
                "25",
                "27",
                "28",
                "31",
                "32",
                "33",
                "43",
                "44",
                "70",
                "77",
                "78",
              ],
            },
            bassinEmploi: {
              bsonType: "string",
            },
            departement: {
              bsonType: "string",
              enum: [
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "2A",
                "2B",
                "30",
                "31",
                "32",
                "33",
                "34",
                "35",
                "36",
                "37",
                "38",
                "39",
                "40",
                "41",
                "42",
                "43",
                "44",
                "45",
                "46",
                "47",
                "48",
                "49",
                "50",
                "51",
                "52",
                "53",
                "54",
                "55",
                "56",
                "57",
                "58",
                "59",
                "60",
                "61",
                "62",
                "63",
                "64",
                "65",
                "66",
                "67",
                "68",
                "69",
                "70",
                "71",
                "72",
                "73",
                "74",
                "75",
                "76",
                "77",
                "78",
                "79",
                "80",
                "81",
                "82",
                "83",
                "84",
                "85",
                "86",
                "87",
                "88",
                "89",
                "90",
                "91",
                "92",
                "93",
                "94",
                "95",
                "971",
                "972",
                "973",
                "974",
                "975",
                "976",
                "977",
                "978",
                "984",
                "986",
                "987",
                "988",
                "989",
              ],
              example: "1 Ain, 99 Étranger",
              maxLength: 3,
              minLength: 1,
              pattern: "^([0-9][0-9]|2[AB]|9[012345]|97[1234678]|98[46789])$",
            },
            fiable: {
              bsonType: "bool",
            },
            region: {
              bsonType: "string",
              enum: [
                "01",
                "02",
                "03",
                "04",
                "06",
                "11",
                "24",
                "27",
                "28",
                "32",
                "44",
                "52",
                "53",
                "75",
                "76",
                "84",
                "93",
                "94",
                "978",
                "977",
                "00",
              ],
            },
            reseaux: {
              bsonType: "array",
              items: {
                bsonType: "string",
                enum: [
                  "ADEN",
                  "CMA",
                  "AGRI",
                  "AGRI_CNEAP",
                  "AGRI_UNREP",
                  "AGRI_UNMFREO",
                  "ANASUP",
                  "AMUE",
                  "CCI",
                  "CFA_EC",
                  "COMP_DU_DEVOIR",
                  "COMP_DU_TOUR_DE_FRANCE",
                  "GRETA",
                  "UIMM",
                  "BTP_CFA",
                  "MFR",
                  "AFTRAL",
                  "GRETA_VAUCLUSE",
                  "CFA_SAT",
                  "EN_HORS_MURS",
                  "EN_CFA_ACADEMIQUE",
                  "EN_EPLE",
                ],
              },
            },
            siret: {
              bsonType: "string",
              maxLength: 14,
              minLength: 14,
              pattern: "^[0-9]{14}$",
            },
            uai: {
              bsonType: "string",
              maxLength: 8,
              minLength: 8,
              pattern: "^[0-9]{7}[a-zA-Z]$",
            },
          },
        },
      },
    },
    _id: {
      bsonType: "objectId",
      description: "Identifiant MongoDB de l'effectif",
    },
    annee_scolaire: {
      bsonType: "string",
      pattern: "^[12][0-9]{3}-[12][0-9]{3}$",
    },
    apprenant: {
      additionalProperties: true,
      bsonType: "object",
      properties: {
        adresse: {
          additionalProperties: false,
          bsonType: "object",
          properties: {
            academie: {
              bsonType: "string",
              enum: [
                "1",
                "2",
                "3",
                "4",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "22",
                "23",
                "24",
                "25",
                "27",
                "28",
                "31",
                "32",
                "33",
                "43",
                "44",
                "70",
                "77",
                "78",
              ],
            },
            bassinEmploi: {
              bsonType: "string",
              description: "Code Bassin d'emploi",
            },
            code_insee: {
              bsonType: "string",
              description: "Code commune insee de l'apprenant",
              example: "54318",
              maxLength: 5,
              minLength: 5,
              pattern: "^[0-9]{1}[0-9A-Z]{1}[0-9]{3}$",
            },
            code_postal: {
              bsonType: "string",
              description: "Le code postal doit contenir 5 caractères",
              example: "75000",
              maxLength: 5,
              minLength: 5,
              pattern: "^[0-9]{5}$",
            },
            commune: {
              bsonType: "string",
              description: "Commune",
              example: "PARIS",
              maxLength: 80,
            },
            complement: {
              bsonType: "string",
              description: "Complément d'adresse",
              example: "Bâtiment ; Résidence ; Entrée ; Appartement ; Escalier ; Etage",
            },
            complete: {
              bsonType: "string",
              description: "Adresse complète",
              example: "13 Bis Boulevard de la liberté 75000 PARIS",
            },
            departement: {
              bsonType: "string",
              enum: [
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "2A",
                "2B",
                "30",
                "31",
                "32",
                "33",
                "34",
                "35",
                "36",
                "37",
                "38",
                "39",
                "40",
                "41",
                "42",
                "43",
                "44",
                "45",
                "46",
                "47",
                "48",
                "49",
                "50",
                "51",
                "52",
                "53",
                "54",
                "55",
                "56",
                "57",
                "58",
                "59",
                "60",
                "61",
                "62",
                "63",
                "64",
                "65",
                "66",
                "67",
                "68",
                "69",
                "70",
                "71",
                "72",
                "73",
                "74",
                "75",
                "76",
                "77",
                "78",
                "79",
                "80",
                "81",
                "82",
                "83",
                "84",
                "85",
                "86",
                "87",
                "88",
                "89",
                "90",
                "91",
                "92",
                "93",
                "94",
                "95",
                "971",
                "972",
                "973",
                "974",
                "975",
                "976",
                "977",
                "978",
                "984",
                "986",
                "987",
                "988",
                "989",
              ],
              example: "1 Ain, 99 Étranger",
              maxLength: 3,
              minLength: 1,
              pattern: "^([0-9][0-9]|2[AB]|9[012345]|97[12345678]|98[46789])$",
            },
            numero: {
              bsonType: "int",
              description: "N° de la voie",
              example: 13,
              pattern: "^(?!0{1})[0-9]*$",
            },
            pays: {
              bsonType: "string",
              description: "Pays",
              enum: [
                "AF",
                "ZA",
                "AL",
                "DZ",
                "DE",
                "AD",
                "AO",
                "AG",
                "SA",
                "AR",
                "AM",
                "AU",
                "AT",
                "AZ",
                "BS",
                "BH",
                "BD",
                "BB",
                "BE",
                "BZ",
                "BJ",
                "BT",
                "BY",
                "MM",
                "BO",
                "BQ",
                "BA",
                "BW",
                "BR",
                "BN",
                "BG",
                "BF",
                "BI",
                "KH",
                "CM",
                "CA",
                "CV",
                "CF",
                "CL",
                "CN",
                "CY",
                "CO",
                "KM",
                "CG",
                "CD",
                "KR",
                "KP",
                "CR",
                "CI",
                "HR",
                "CU",
                "CW",
                "DK",
                "DJ",
                "DO",
                "DM",
                "EG",
                "SV",
                "AE",
                "EC",
                "ER",
                "ES",
                "EE",
                "SZ",
                "US",
                "ET",
                "MK",
                "FJ",
                "FI",
                "FR",
                "GA",
                "GM",
                "GE",
                "GH",
                "GR",
                "GD",
                "GT",
                "GN",
                "GQ",
                "GW",
                "GY",
                "HT",
                "HN",
                "HU",
                "IN",
                "ID",
                "IR",
                "IQ",
                "IE",
                "IS",
                "IL",
                "IT",
                "JM",
                "JP",
                "JO",
                "KZ",
                "KE",
                "KG",
                "KI",
                "XK",
                "KW",
                "LA",
                "LS",
                "LV",
                "LB",
                "LR",
                "LY",
                "LI",
                "LT",
                "LU",
                "MG",
                "MY",
                "MW",
                "MV",
                "ML",
                "MT",
                "MA",
                "MH",
                "MU",
                "MR",
                "MX",
                "FM",
                "MD",
                "MC",
                "MN",
                "ME",
                "MZ",
                "NA",
                "NR",
                "NP",
                "NI",
                "NE",
                "NG",
                "NO",
                "NZ",
                "OM",
                "UG",
                "UZ",
                "PK",
                "PW",
                "PS",
                "PA",
                "PG",
                "PY",
                "NL",
                "PE",
                "PH",
                "PL",
                "PT",
                "QA",
                "RO",
                "GB",
                "RU",
                "RW",
                "KN",
                "SM",
                "SX",
                "VC",
                "LC",
                "SB",
                "WS",
                "ST",
                "SN",
                "RS",
                "SC",
                "SL",
                "SG",
                "SK",
                "SI",
                "SO",
                "SD",
                "SS",
                "LK",
                "SE",
                "CH",
                "SR",
                "SY",
                "TJ",
                "TZ",
                "TD",
                "CZ",
                "TH",
                "TL",
                "TG",
                "TO",
                "TT",
                "TN",
                "TM",
                "TR",
                "TV",
                "UA",
                "UY",
                "VU",
                "VA",
                "VE",
                "VN",
                "YE",
                "ZM",
                "ZW",
              ],
            },
            region: {
              bsonType: "string",
              enum: [
                "01",
                "02",
                "03",
                "04",
                "06",
                "11",
                "24",
                "27",
                "28",
                "32",
                "44",
                "52",
                "53",
                "75",
                "76",
                "84",
                "93",
                "94",
                "978",
                "977",
                "00",
              ],
            },
            repetition_voie: {
              bsonType: "string",
              description: "Indice de répétition du numéro de voie",
              enum: ["B", "T", "Q", "C"],
              example: "B",
            },
            voie: {
              bsonType: "string",
              description: "Nom de voie",
              example: "Boulevard de la liberté",
            },
          },
        },
        affelnet: {
          bsonType: "array",
          items: {
            bsonType: "string",
            description: "voeux affelnet de l'apprenant",
          },
        },
        code_postal_de_naissance: {
          bsonType: "string",
          example: "75000",
          maxLength: 5,
          minLength: 5,
          pattern: "^[0-9]{5}$",
        },
        courriel: {
          bsonType: "string",
          description: "Adresse mail de contact de l'apprenant",
        },
        date_de_naissance: {
          bsonType: "date",
          description: "Date de naissance de l'apprenant",
        },
        date_rqth: {
          bsonType: "date",
          description: "Date de la reconnaissance travailleur handicapé",
        },
        dernier_diplome: {
          bsonType: "int",
          description: "Dernier diplôme obtenu",
          enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 99],
        },
        dernier_organisme_uai: {
          bsonType: "string",
          pattern: "^(0?[0-9][0-9]|0?2[AB]|0?9[012345]|97[1234678]|98[46789]|99[0135]|[0-9]{7}[a-zA-Z])$",
        },
        derniere_situation: {
          bsonType: "int",
          description: "Situation de l'apprenant N-1",
          enum: [
            1003, 1005, 1009, 1013, 1015, 1017, 1018, 1019, 1021, 1023, 2001, 2003, 2005, 2007, 3001, 3101, 3003, 3103,
            3009, 3109, 3011, 3111, 3031, 3131, 3032, 3132, 3033, 3133, 3117, 3119, 3021, 3121, 3023, 3123, 4001, 4101,
            4003, 4103, 4005, 4105, 4007, 4107, 4009, 4011, 4111, 4013, 4113, 4015, 4115, 4017, 4117, 4019, 4119, 4021,
            4121, 5901, 5903, 5905, 5907, 5909, 9900, 9999,
          ],
        },
        has_nir: {
          bsonType: "bool",
          description: "Numéro de sécurité sociale de l'apprenant",
        },
        historique_statut: {
          bsonType: "array",
          description: "Historique du statut de l'apprenant",
          items: {
            additionalProperties: true,
            bsonType: "object",
            properties: {
              abandon_forced: {
                bsonType: "bool",
                description: "Le statut a été forcé en abandon",
              },
              date_reception: {
                bsonType: "date",
              },
              date_statut: {
                bsonType: "date",
              },
              valeur_statut: {
                bsonType: "int",
                description: "Statut de l'apprenant",
                enum: [2, 3, 0],
              },
            },
            required: ["valeur_statut", "date_statut"],
          },
        },
        ine: {
          bsonType: "string",
          description: "N° INE de l'apprenant",
          example: "0494004062M",
        },
        inscription_sportif_haut_niveau: {
          bsonType: "bool",
          description:
            "Apprenant inscrit sur la liste des sportifs, entraîneurs, arbitres et juges sportifs de haut niveau",
        },
        mineur: {
          bsonType: "bool",
          description: "l'apprenant(e) sera-t-il(elle) mineur(e) ? (calc)",
        },
        mineur_emancipe: {
          bsonType: "bool",
          description: "Un mineur émancipé peut accomplir seul les actes nécessitant la majorité légale.",
        },
        nationalite: {
          bsonType: "int",
          description: "Apprenant étranger, non citoyen européen",
          enum: [1, 2, 3],
        },
        nom: {
          bsonType: "string",
          description: "Nom de l'apprenant",
          pattern: "^.+$",
        },
        parcoursup: {
          bsonType: "array",
          items: {
            bsonType: "string",
            description: "voeux parcoursup de l'apprenant",
          },
        },
        prenom: {
          bsonType: "string",
          description: "Prénom de l'apprenant",
          pattern: "^.+$",
        },
        regime_scolaire: {
          bsonType: "string",
          description: "Régime scolaire (I : Interne, D : Demi-pensionnaire, E : Externe, IE : Interne externé)",
          enum: ["I", "D", "E", "IE"],
        },
        representant_legal: {
          additionalProperties: false,
          bsonType: "object",
          properties: {
            adresse: {
              additionalProperties: false,
              bsonType: "object",
              properties: {
                academie: {
                  bsonType: "string",
                  enum: [
                    "1",
                    "2",
                    "3",
                    "4",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16",
                    "17",
                    "18",
                    "19",
                    "20",
                    "22",
                    "23",
                    "24",
                    "25",
                    "27",
                    "28",
                    "31",
                    "32",
                    "33",
                    "43",
                    "44",
                    "70",
                    "77",
                    "78",
                  ],
                },
                bassinEmploi: {
                  bsonType: "string",
                  description: "Code Bassin d'emploi",
                },
                code_insee: {
                  bsonType: "string",
                  description: "Le code insee doit contenir 5 caractères",
                  example: "54318",
                  maxLength: 5,
                  minLength: 5,
                  pattern: "^[0-9]{1}[0-9A-Z]{1}[0-9]{3}$",
                },
                code_postal: {
                  bsonType: "string",
                  description: "Le code postal doit contenir 5 caractères",
                  example: "75000",
                  maxLength: 5,
                  minLength: 5,
                  pattern: "^[0-9]{5}$",
                },
                commune: {
                  bsonType: "string",
                  description: "Commune",
                  example: "PARIS",
                  maxLength: 80,
                },
                complement: {
                  bsonType: "string",
                  description: "Complément d'adresse",
                  example: "Bâtiment ; Résidence ; Entrée ; Appartement ; Escalier ; Etage",
                },
                complete: {
                  bsonType: "string",
                  description: "Adresse complète",
                  example: "13 Bis Boulevard de la liberté 75000 PARIS",
                },
                departement: {
                  bsonType: "string",
                  enum: [
                    "01",
                    "02",
                    "03",
                    "04",
                    "05",
                    "06",
                    "07",
                    "08",
                    "09",
                    "10",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16",
                    "17",
                    "18",
                    "19",
                    "21",
                    "22",
                    "23",
                    "24",
                    "25",
                    "26",
                    "27",
                    "28",
                    "29",
                    "2A",
                    "2B",
                    "30",
                    "31",
                    "32",
                    "33",
                    "34",
                    "35",
                    "36",
                    "37",
                    "38",
                    "39",
                    "40",
                    "41",
                    "42",
                    "43",
                    "44",
                    "45",
                    "46",
                    "47",
                    "48",
                    "49",
                    "50",
                    "51",
                    "52",
                    "53",
                    "54",
                    "55",
                    "56",
                    "57",
                    "58",
                    "59",
                    "60",
                    "61",
                    "62",
                    "63",
                    "64",
                    "65",
                    "66",
                    "67",
                    "68",
                    "69",
                    "70",
                    "71",
                    "72",
                    "73",
                    "74",
                    "75",
                    "76",
                    "77",
                    "78",
                    "79",
                    "80",
                    "81",
                    "82",
                    "83",
                    "84",
                    "85",
                    "86",
                    "87",
                    "88",
                    "89",
                    "90",
                    "91",
                    "92",
                    "93",
                    "94",
                    "95",
                    "971",
                    "972",
                    "973",
                    "974",
                    "975",
                    "976",
                    "977",
                    "978",
                    "984",
                    "986",
                    "987",
                    "988",
                    "989",
                  ],
                  example: "1 Ain, 99 Étranger",
                  maxLength: 3,
                  minLength: 1,
                  pattern: "^([0-9][0-9]|2[AB]|9[012345]|97[12345678]|98[46789])$",
                },
                numero: {
                  bsonType: "int",
                  description: "N° de la voie",
                  example: 13,
                  pattern: "^(?!0{1})[0-9]*$",
                },
                pays: {
                  bsonType: "string",
                  description: "Pays",
                  enum: [
                    "AF",
                    "ZA",
                    "AL",
                    "DZ",
                    "DE",
                    "AD",
                    "AO",
                    "AG",
                    "SA",
                    "AR",
                    "AM",
                    "AU",
                    "AT",
                    "AZ",
                    "BS",
                    "BH",
                    "BD",
                    "BB",
                    "BE",
                    "BZ",
                    "BJ",
                    "BT",
                    "BY",
                    "MM",
                    "BO",
                    "BQ",
                    "BA",
                    "BW",
                    "BR",
                    "BN",
                    "BG",
                    "BF",
                    "BI",
                    "KH",
                    "CM",
                    "CA",
                    "CV",
                    "CF",
                    "CL",
                    "CN",
                    "CY",
                    "CO",
                    "KM",
                    "CG",
                    "CD",
                    "KR",
                    "KP",
                    "CR",
                    "CI",
                    "HR",
                    "CU",
                    "CW",
                    "DK",
                    "DJ",
                    "DO",
                    "DM",
                    "EG",
                    "SV",
                    "AE",
                    "EC",
                    "ER",
                    "ES",
                    "EE",
                    "SZ",
                    "US",
                    "ET",
                    "MK",
                    "FJ",
                    "FI",
                    "FR",
                    "GA",
                    "GM",
                    "GE",
                    "GH",
                    "GR",
                    "GD",
                    "GT",
                    "GN",
                    "GQ",
                    "GW",
                    "GY",
                    "HT",
                    "HN",
                    "HU",
                    "IN",
                    "ID",
                    "IR",
                    "IQ",
                    "IE",
                    "IS",
                    "IL",
                    "IT",
                    "JM",
                    "JP",
                    "JO",
                    "KZ",
                    "KE",
                    "KG",
                    "KI",
                    "XK",
                    "KW",
                    "LA",
                    "LS",
                    "LV",
                    "LB",
                    "LR",
                    "LY",
                    "LI",
                    "LT",
                    "LU",
                    "MG",
                    "MY",
                    "MW",
                    "MV",
                    "ML",
                    "MT",
                    "MA",
                    "MH",
                    "MU",
                    "MR",
                    "MX",
                    "FM",
                    "MD",
                    "MC",
                    "MN",
                    "ME",
                    "MZ",
                    "NA",
                    "NR",
                    "NP",
                    "NI",
                    "NE",
                    "NG",
                    "NO",
                    "NZ",
                    "OM",
                    "UG",
                    "UZ",
                    "PK",
                    "PW",
                    "PS",
                    "PA",
                    "PG",
                    "PY",
                    "NL",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "QA",
                    "RO",
                    "GB",
                    "RU",
                    "RW",
                    "KN",
                    "SM",
                    "SX",
                    "VC",
                    "LC",
                    "SB",
                    "WS",
                    "ST",
                    "SN",
                    "RS",
                    "SC",
                    "SL",
                    "SG",
                    "SK",
                    "SI",
                    "SO",
                    "SD",
                    "SS",
                    "LK",
                    "SE",
                    "CH",
                    "SR",
                    "SY",
                    "TJ",
                    "TZ",
                    "TD",
                    "CZ",
                    "TH",
                    "TL",
                    "TG",
                    "TO",
                    "TT",
                    "TN",
                    "TM",
                    "TR",
                    "TV",
                    "UA",
                    "UY",
                    "VU",
                    "VA",
                    "VE",
                    "VN",
                    "YE",
                    "ZM",
                    "ZW",
                  ],
                },
                region: {
                  bsonType: "string",
                  enum: [
                    "01",
                    "02",
                    "03",
                    "04",
                    "06",
                    "11",
                    "24",
                    "27",
                    "28",
                    "32",
                    "44",
                    "52",
                    "53",
                    "75",
                    "76",
                    "84",
                    "93",
                    "94",
                    "978",
                    "977",
                    "00",
                  ],
                },
                repetition_voie: {
                  bsonType: "string",
                  description: "Indice de répétition du numéro de voie",
                  enum: ["B", "T", "Q", "C"],
                  example: "B",
                },
                voie: {
                  bsonType: "string",
                  description: "Nom de voie",
                  example: "Boulevard de la liberté",
                },
              },
            },
            courriel: {
              bsonType: "string",
              description: "Adresse mail de contact du representant légal",
            },
            meme_adresse: {
              bsonType: "bool",
              description: "l'apprenti(e) vit à la même adresse que son representant légal",
            },
            nom: {
              bsonType: "string",
              description: "Nom du representant légal",
            },
            pcs: {
              bsonType: "int",
              description: "Nomenclatures des professions et catégories socioprofessionnelles",
              enum: [
                10, 21, 22, 23, 31, 33, 34, 37, 38, 42, 43, 44, 45, 46, 47, 48, 52, 53, 54, 55, 56, 61, 66, 69, 71, 72,
                73, 76, 81, 82, 99,
              ],
            },
            prenom: {
              bsonType: "string",
              description: "Prénom du representant légal",
            },
            telephone: {
              bsonType: "string",
              example: "+33908070605",
              maxLength: 13,
              minLength: 8,
              pattern: "^([+])?(\\d{7,12})$",
            },
          },
        },
        responsable_mail1: {
          bsonType: "string",
          description: "Adresse mail du responsable 1",
        },
        responsable_mail2: {
          bsonType: "string",
          description: "Adresse mail du responsable 2",
        },
        rqth: {
          bsonType: "bool",
          description: "Apprenant en situation d'handicape (RQTH)",
        },
        sexe: {
          bsonType: "string",
          description: "Sexe de l'apprenant (M: Homme, F: Femme)",
          enum: ["M", "F"],
        },
        situation_avant_contrat: {
          bsonType: "int",
          description: "Situation de l'apprenant avant le contrat",
          enum: [11, 12, 21, 31, 41, 51, 52, 53, 54, 90, 99],
        },
        telephone: {
          bsonType: "string",
          description: "Téléphone de l'apprenant",
          example: "+33908070605",
          maxLength: 13,
          minLength: 8,
          pattern: "^([+])?(\\d{7,12})$",
        },
        type_cfa: {
          bsonType: "string",
          description: "Type de CFA",
          enum: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10"],
        },
      },
      required: ["nom", "prenom", "historique_statut"],
    },
    archive: {
      bsonType: "bool",
      description: "Dossier apprenant est archivé (rétention maximum 5 ans)",
    },
    contrats: {
      bsonType: "array",
      description: "Historique des contrats de l'apprenant",
      items: {
        additionalProperties: true,
        bsonType: "object",
        properties: {
          adresse: {
            additionalProperties: false,
            bsonType: "object",
            properties: {
              academie: {
                bsonType: "string",
                enum: [
                  "1",
                  "2",
                  "3",
                  "4",
                  "6",
                  "7",
                  "8",
                  "9",
                  "10",
                  "11",
                  "12",
                  "13",
                  "14",
                  "15",
                  "16",
                  "17",
                  "18",
                  "19",
                  "20",
                  "22",
                  "23",
                  "24",
                  "25",
                  "27",
                  "28",
                  "31",
                  "32",
                  "33",
                  "43",
                  "44",
                  "70",
                  "77",
                  "78",
                ],
              },
              bassinEmploi: {
                bsonType: "string",
                description: "Code Bassin d'emploi",
              },
              code_insee: {
                bsonType: "string",
                description: "Le code insee doit contenir 5 caractères",
                example: "54318",
                maxLength: 5,
                minLength: 5,
                pattern: "^[0-9]{1}[0-9A-Z]{1}[0-9]{3}$",
              },
              code_postal: {
                bsonType: "string",
                description: "Le code postal doit contenir 5 caractères",
                example: "75000",
                maxLength: 5,
                minLength: 5,
                pattern: "^[0-9]{5}$",
              },
              commune: {
                bsonType: "string",
                description: "Commune",
                example: "PARIS",
                maxLength: 80,
              },
              complement: {
                bsonType: "string",
                description: "Complément d'adresse",
                example: "Bâtiment ; Résidence ; Entrée ; Appartement ; Escalier ; Etage",
              },
              complete: {
                bsonType: "string",
                description: "Adresse complète",
                example: "13 Bis Boulevard de la liberté 75000 PARIS",
              },
              departement: {
                bsonType: "string",
                enum: [
                  "01",
                  "02",
                  "03",
                  "04",
                  "05",
                  "06",
                  "07",
                  "08",
                  "09",
                  "10",
                  "11",
                  "12",
                  "13",
                  "14",
                  "15",
                  "16",
                  "17",
                  "18",
                  "19",
                  "21",
                  "22",
                  "23",
                  "24",
                  "25",
                  "26",
                  "27",
                  "28",
                  "29",
                  "2A",
                  "2B",
                  "30",
                  "31",
                  "32",
                  "33",
                  "34",
                  "35",
                  "36",
                  "37",
                  "38",
                  "39",
                  "40",
                  "41",
                  "42",
                  "43",
                  "44",
                  "45",
                  "46",
                  "47",
                  "48",
                  "49",
                  "50",
                  "51",
                  "52",
                  "53",
                  "54",
                  "55",
                  "56",
                  "57",
                  "58",
                  "59",
                  "60",
                  "61",
                  "62",
                  "63",
                  "64",
                  "65",
                  "66",
                  "67",
                  "68",
                  "69",
                  "70",
                  "71",
                  "72",
                  "73",
                  "74",
                  "75",
                  "76",
                  "77",
                  "78",
                  "79",
                  "80",
                  "81",
                  "82",
                  "83",
                  "84",
                  "85",
                  "86",
                  "87",
                  "88",
                  "89",
                  "90",
                  "91",
                  "92",
                  "93",
                  "94",
                  "95",
                  "971",
                  "972",
                  "973",
                  "974",
                  "975",
                  "976",
                  "977",
                  "978",
                  "984",
                  "986",
                  "987",
                  "988",
                  "989",
                ],
                example: "1 Ain, 99 Étranger",
                maxLength: 3,
                minLength: 1,
                pattern: "^([0-9][0-9]|2[AB]|9[012345]|97[12345678]|98[46789])$",
              },
              numero: {
                bsonType: "int",
                description: "N° de la voie",
                example: 13,
                pattern: "^(?!0{1})[0-9]*$",
              },
              pays: {
                bsonType: "string",
                description: "Pays",
                enum: [
                  "AF",
                  "ZA",
                  "AL",
                  "DZ",
                  "DE",
                  "AD",
                  "AO",
                  "AG",
                  "SA",
                  "AR",
                  "AM",
                  "AU",
                  "AT",
                  "AZ",
                  "BS",
                  "BH",
                  "BD",
                  "BB",
                  "BE",
                  "BZ",
                  "BJ",
                  "BT",
                  "BY",
                  "MM",
                  "BO",
                  "BQ",
                  "BA",
                  "BW",
                  "BR",
                  "BN",
                  "BG",
                  "BF",
                  "BI",
                  "KH",
                  "CM",
                  "CA",
                  "CV",
                  "CF",
                  "CL",
                  "CN",
                  "CY",
                  "CO",
                  "KM",
                  "CG",
                  "CD",
                  "KR",
                  "KP",
                  "CR",
                  "CI",
                  "HR",
                  "CU",
                  "CW",
                  "DK",
                  "DJ",
                  "DO",
                  "DM",
                  "EG",
                  "SV",
                  "AE",
                  "EC",
                  "ER",
                  "ES",
                  "EE",
                  "SZ",
                  "US",
                  "ET",
                  "MK",
                  "FJ",
                  "FI",
                  "FR",
                  "GA",
                  "GM",
                  "GE",
                  "GH",
                  "GR",
                  "GD",
                  "GT",
                  "GN",
                  "GQ",
                  "GW",
                  "GY",
                  "HT",
                  "HN",
                  "HU",
                  "IN",
                  "ID",
                  "IR",
                  "IQ",
                  "IE",
                  "IS",
                  "IL",
                  "IT",
                  "JM",
                  "JP",
                  "JO",
                  "KZ",
                  "KE",
                  "KG",
                  "KI",
                  "XK",
                  "KW",
                  "LA",
                  "LS",
                  "LV",
                  "LB",
                  "LR",
                  "LY",
                  "LI",
                  "LT",
                  "LU",
                  "MG",
                  "MY",
                  "MW",
                  "MV",
                  "ML",
                  "MT",
                  "MA",
                  "MH",
                  "MU",
                  "MR",
                  "MX",
                  "FM",
                  "MD",
                  "MC",
                  "MN",
                  "ME",
                  "MZ",
                  "NA",
                  "NR",
                  "NP",
                  "NI",
                  "NE",
                  "NG",
                  "NO",
                  "NZ",
                  "OM",
                  "UG",
                  "UZ",
                  "PK",
                  "PW",
                  "PS",
                  "PA",
                  "PG",
                  "PY",
                  "NL",
                  "PE",
                  "PH",
                  "PL",
                  "PT",
                  "QA",
                  "RO",
                  "GB",
                  "RU",
                  "RW",
                  "KN",
                  "SM",
                  "SX",
                  "VC",
                  "LC",
                  "SB",
                  "WS",
                  "ST",
                  "SN",
                  "RS",
                  "SC",
                  "SL",
                  "SG",
                  "SK",
                  "SI",
                  "SO",
                  "SD",
                  "SS",
                  "LK",
                  "SE",
                  "CH",
                  "SR",
                  "SY",
                  "TJ",
                  "TZ",
                  "TD",
                  "CZ",
                  "TH",
                  "TL",
                  "TG",
                  "TO",
                  "TT",
                  "TN",
                  "TM",
                  "TR",
                  "TV",
                  "UA",
                  "UY",
                  "VU",
                  "VA",
                  "VE",
                  "VN",
                  "YE",
                  "ZM",
                  "ZW",
                ],
              },
              region: {
                bsonType: "string",
                enum: [
                  "01",
                  "02",
                  "03",
                  "04",
                  "06",
                  "11",
                  "24",
                  "27",
                  "28",
                  "32",
                  "44",
                  "52",
                  "53",
                  "75",
                  "76",
                  "84",
                  "93",
                  "94",
                  "978",
                  "977",
                  "00",
                ],
              },
              repetition_voie: {
                bsonType: "string",
                description: "Indice de répétition du numéro de voie",
                enum: ["B", "T", "Q", "C"],
                example: "B",
              },
              voie: {
                bsonType: "string",
                description: "Nom de voie",
                example: "Boulevard de la liberté",
              },
            },
          },
          cause_rupture: {
            bsonType: "string",
            description: "Cause de rupture du contrat",
          },
          date_debut: {
            bsonType: "date",
            description: "Date de début du contrat",
          },
          date_fin: {
            bsonType: "date",
            description: "Date de fin du contrat",
          },
          date_rupture: {
            bsonType: "date",
            description: "Date de rupture du contrat",
          },
          denomination: {
            bsonType: "string",
            description: "La dénomination sociale doit être celle de l'établissement dans lequel le contrat s'exécute.",
          },
          naf: {
            bsonType: "string",
            description:
              "Le Code NAF est composé de 4 chiffres et 1 lettre. Il est délivré par l'INSEE.[Informations sur le Code NAF.](https://www.economie.gouv.fr/entreprises/activite-entreprise-code-ape-code-naf)",
            example: "1031Z",
            maxLength: 6,
            pattern: "^([0-9]){2}\\.?([0-9]){0,2}([a-zA-Z]){0,1}$",
          },
          nombre_de_salaries: {
            bsonType: "int",
            description:
              "L'effectif salarié rempli automatiquement correspond à l'estimation de la base Entreprises de l'INSEE. <br/>L'effectif renseigné est celui de l’entreprise dans sa globalité (et non seulement l’effectif de l’établissement d’exécution du contrat).",
            example: 123,
          },
          siret: {
            bsonType: "string",
            description: "N° SIRET de l'employeur",
            maxLength: 14,
            minLength: 14,
            pattern: "^[0-9]{14}$",
          },
          type_employeur: {
            bsonType: "int",
            description: "Le type d'employeur doit être en adéquation avec son statut juridique.",
            enum: [11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25, 26, 27, 28, 29],
          },
        },
        required: ["date_debut"],
      },
    },
    created_at: {
      bsonType: "date",
      description: "Date d'ajout en base de données",
    },
    formation: {
      additionalProperties: true,
      bsonType: "object",
      properties: {
        annee: {
          bsonType: "int",
          description: "Numéro de l'année dans la formation (promo)",
        },
        cause_exclusion: {
          bsonType: "string",
          description: "Cause de l'exclusion",
        },
        cfd: {
          bsonType: "string",
          description: "Code CFD de la formation",
          maxLength: 8,
          pattern: "^[A-Z0-9]{8}$",
        },
        date_entree: {
          bsonType: "date",
          description: "Date d'entrée en formation",
        },
        date_exclusion: {
          bsonType: "date",
          description: "Date d'exclusion",
        },
        date_fin: {
          bsonType: "date",
          description: "Date de fin de la formation",
        },
        date_inscription: {
          bsonType: "date",
          description: "Date d'inscription",
        },
        date_obtention_diplome: {
          bsonType: "date",
          description: "Date d'obtention du diplôme",
        },
        duree_formation_relle: {
          bsonType: "int",
          description: "Durée réelle de la formation en mois",
        },
        duree_theorique: {
          bsonType: "int",
          description: "Durée théorique de la formation en année",
        },
        duree_theorique_mois: {
          bsonType: "int",
          description: "Durée théorique de la formation en mois",
        },
        formation_id: {
          bsonType: "objectId",
          description: "ID de la formation",
        },
        formation_presentielle: {
          bsonType: "bool",
          description: "Formation en présentiel",
        },
        libelle_long: {
          bsonType: "string",
          description: "Libellé long de la formation visée",
        },
        niveau: {
          bsonType: ["string", "null"],
          description: "Niveau de formation récupéré via Tables de Correspondances",
        },
        niveau_libelle: {
          bsonType: ["string", "null"],
          description: "Libellé du niveau de formation récupéré via Tables de Correspondances",
        },
        obtention_diplome: {
          bsonType: "bool",
          description: "Diplôme obtenu",
        },
        periode: {
          bsonType: "array",
          description: "Période de la formation, en année (peut être sur plusieurs années)",
          items: {
            bsonType: "int",
          },
        },
        referent_handicap: {
          additionalProperties: false,
          bsonType: "object",
          properties: {
            email: {
              bsonType: "string",
              description: "Email du référent handicap",
            },
            nom: {
              bsonType: "string",
              description: "Nom du référent handicap",
            },
            prenom: {
              bsonType: "string",
              description: "Prénom du référent handicap",
            },
          },
        },
        rncp: {
          bsonType: "string",
          description: "Code RNCP de la formation à laquelle l'apprenant est inscrit",
          maxLength: 9,
          pattern: "^(RNCP)?[0-9]{2,5}$",
        },
      },
    },
    id_erp_apprenant: {
      bsonType: "string",
      description: "Identifiant de l'apprenant dans l'erp",
    },
    is_lock: {
      additionalProperties: true,
      bsonType: ["number", "string", "bool", "object", "array", "null"],
      description: "Indique les champs verrouillés",
    },
    organisme_formateur_id: {
      bsonType: "objectId",
      description: "Organisme formateur id",
    },
    organisme_id: {
      bsonType: "objectId",
      description: "Organisme id (lieu de formation de l'apprenant pour la v3)",
    },
    organisme_responsable_id: {
      bsonType: "objectId",
      description: "Organisme responsable id",
    },
    source: {
      bsonType: "string",
      description: "Source du dossier apprenant (FICHIER, ERP, DECA)",
      enum: ["FICHIER", "ERP", "DECA"],
    },
    source_organisme_id: {
      bsonType: "string",
      description: "Identifiant de l'organisme id source transmettant",
    },
    updated_at: {
      bsonType: "date",
      description: "Date de mise à jour en base de données",
    },
    validation_errors: {
      bsonType: "array",
      description: "Erreurs de validation de cet effectif",
      items: {
        additionalProperties: false,
        bsonType: "object",
        properties: {
          fieldName: {
            bsonType: "string",
            description: "Nom du champ en erreur",
          },
          inputValue: {
            bsonType: "string",
            description: "Valeur fournie en entrée",
          },
          message: {
            bsonType: "string",
            description: "Message de l'erreur",
          },
          type: {
            bsonType: "string",
            description: "Type d'erreur",
          },
        },
      },
    },
  },
  required: ["apprenant", "id_erp_apprenant", "organisme_id", "source", "annee_scolaire"],
};
