// auto-generated by bson-schema-to-typescript

export interface DossiersApprenantsMigration {
  _id?: any;
  /**
   * Organisme id
   */
  organisme_id: any;
  /**
   * Identifiant de l'apprenant dans l'erp
   */
  id_erp_apprenant: string;
  /**
   * Source du dossier apprenant (Ymag, Gesti, MANUEL...)
   */
  source: string;
  /**
   * Année scolaire sur laquelle l'apprenant est enregistré (ex: "2020-2021")
   */
  annee_scolaire: string;
  /**
   * Code UAI de l'établissement formateur
   */
  uai_etablissement: string;
  /**
   * Siret de l'établissement d'origine
   */
  siret_etablissement: string;
  /**
   * Réseaux auxquels appartient l'organisme de formation de l'apprenant
   */
  etablissement_reseaux?: string[];
  /**
   * Nom de l'établissement d'origine
   */
  nom_etablissement?: string;
  /**
   * Adresse complète du CFA
   */
  etablissement_adresse?: string;
  /**
   * Région du CFA
   */
  etablissement_nom_region?: string;
  /**
   * Numéro de la région du CFA
   */
  etablissement_num_region?:
    | "01"
    | "02"
    | "03"
    | "04"
    | "06"
    | "11"
    | "24"
    | "27"
    | "28"
    | "32"
    | "44"
    | "52"
    | "53"
    | "75"
    | "76"
    | "84"
    | "93"
    | "94"
    | "978"
    | "977"
    | "00";
  /**
   * Numéro de departement du CFA
   */
  etablissement_num_departement?: string;
  /**
   * Nom du departement du CFA
   */
  etablissement_nom_departement?: string;
  /**
   * N° INE de l'apprenant
   */
  ine_apprenant?: string;
  /**
   * Nom de l'apprenant
   */
  nom_apprenant: string;
  /**
   * Prénom de l'apprenant
   */
  prenom_apprenant: string;
  /**
   * Adresse mail de contact de l'apprenant
   */
  email_contact?: string;
  /**
   * Date de naissance de l'apprenant
   */
  date_de_naissance_apprenant?: Date;
  /**
   * Dans le cas d'un numéro français, il n'est pas
   *         nécessaire de saisir le "0" car l'indicateur pays est
   *         pré-renseigné.
   *         Il doit contenir 9 chiffres après l'indicatif.
   */
  telephone_apprenant?: string;
  /**
   * Code commune insee de l'apprenant
   */
  code_commune_insee_apprenant?: string;
  historique_statut_apprenant: {
    valeur_statut: 2 | 3 | 0;
    date_statut: Date;
    date_reception: Date;
  }[];
  /**
   * N° SIRET de l'employeur
   */
  employeur_siret?: string;
  /**
   * Date de début du contrat
   */
  contrat_date_debut?: Date;
  /**
   * Date de fin du contrat
   */
  contrat_date_fin?: Date;
  /**
   * Date de rupture du contrat
   */
  contrat_date_rupture?: Date;
  /**
   * CFD de la formation à laquelle l'apprenant est inscrit
   */
  formation_cfd: string;
  /**
   * Code RNCP de la formation à laquelle l'apprenant est inscrit
   */
  formation_rncp?: string;
  /**
   * Libellé court de la formation visée
   */
  libelle_long_formation?: string;
  /**
   * Le niveau de la formation (ex: 3)
   */
  niveau_formation?: string;
  /**
   * Libellé du niveau de la formation (ex: '3 (BTS, DUT...)')
   */
  niveau_formation_libelle?: string;
  /**
   * Date debut & date de fin de la formation
   */
  periode_formation?: number[];
  /**
   * Numéro de l'année dans la formation (promo)
   */
  annee_formation?: number;
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
  /**
   * Dossier apprenant est archivé (retnetion maximum 5 ans)
   */
  archive?: boolean;
}
