// auto-generated by bson-schema-to-typescript
import { ObjectId } from "mongodb";

export interface Effectif {
  /**
   * Identifiant MongoDB de l'effectif
   */
  /**
   * Organisme id (lieu de formation de l'apprenant pour la v3)
   */
  organisme_id: ObjectId;
  /**
   * Organisme responsable id
   */
  organisme_responsable_id?: ObjectId;
  /**
   * Organisme formateur id
   */
  organisme_formateur_id?: ObjectId;
  /**
   * Identifiant de l'apprenant dans l'erp
   */
  id_erp_apprenant: string;
  /**
   * Source du dossier apprenant (Ymag, Gesti, TDB_MANUEL, TDB_FILE...)
   */
  source: string;
  /**
   * Année scolaire sur laquelle l'apprenant est enregistré (ex: "2020-2021")
   */
  annee_scolaire: string;
  apprenant: {
    /**
     * N° INE de l'apprenant
     */
    ine?: string;
    /**
     * Nom de l'apprenant
     */
    nom: string;
    /**
     * Prénom de l'apprenant
     */
    prenom: string;
    /**
     * Sexe de l'apprenant (M: Homme, F: Femme)
     */
    sexe?: "M" | "F";
    /**
     * Date de naissance de l'apprenant
     */
    date_de_naissance?: Date;
    /**
     * Le code postal doit contenir 5 caractères
     */
    code_postal_de_naissance?: string;
    /**
     * Apprenant étranger, non citoyen européen
     */
    nationalite?: 1 | 2 | 3;
    /**
     * Régime scolaire (I : Interne, D : Demi-pensionnaire, E : Externe, IE : Interne externé)
     */
    regime_scolaire?: "I" | "D" | "E" | "IE";
    /**
     * Apprenant en situation d'handicape (RQTH)
     */
    rqth?: boolean;
    /**
     * Date de la reconnaissance travailleur handicapé
     */
    date_rqth?: Date;
    affelnet?: string[];
    parcoursup?: string[];
    /**
     * Apprenant inscrit sur la liste des sportifs, entraîneurs, arbitres et juges sportifs de haut niveau
     */
    inscription_sportif_haut_niveau?: boolean;
    /**
     * Adresse mail de contact de l'apprenant
     */
    courriel?: string;
    /**
     * Téléphone de l'apprenant
     */
    telephone?: string;
    adresse?: {
      /**
       * N° de la voie
       */
      numero?: number;
      /**
       * Indice de répétition du numéro de voie
       */
      repetition_voie?: "B" | "T" | "Q" | "C";
      /**
       * Nom de voie
       */
      voie?: string;
      /**
       * Complément d'adresse
       */
      complement?: string;
      /**
       * Le code postal doit contenir 5 caractères
       */
      code_postal?: string;
      /**
       * Code commune insee de l'apprenant
       */
      code_insee?: string;
      /**
       * Commune
       */
      commune?: string;
      departement?:
        | "01"
        | "02"
        | "03"
        | "04"
        | "05"
        | "06"
        | "07"
        | "08"
        | "09"
        | "10"
        | "11"
        | "12"
        | "13"
        | "14"
        | "15"
        | "16"
        | "17"
        | "18"
        | "19"
        | "21"
        | "22"
        | "23"
        | "24"
        | "25"
        | "26"
        | "27"
        | "28"
        | "29"
        | "2A"
        | "2B"
        | "30"
        | "31"
        | "32"
        | "33"
        | "34"
        | "35"
        | "36"
        | "37"
        | "38"
        | "39"
        | "40"
        | "41"
        | "42"
        | "43"
        | "44"
        | "45"
        | "46"
        | "47"
        | "48"
        | "49"
        | "50"
        | "51"
        | "52"
        | "53"
        | "54"
        | "55"
        | "56"
        | "57"
        | "58"
        | "59"
        | "60"
        | "61"
        | "62"
        | "63"
        | "64"
        | "65"
        | "66"
        | "67"
        | "68"
        | "69"
        | "70"
        | "71"
        | "72"
        | "73"
        | "74"
        | "75"
        | "76"
        | "77"
        | "78"
        | "79"
        | "80"
        | "81"
        | "82"
        | "83"
        | "84"
        | "85"
        | "86"
        | "87"
        | "88"
        | "89"
        | "90"
        | "91"
        | "92"
        | "93"
        | "94"
        | "95"
        | "971"
        | "972"
        | "973"
        | "974"
        | "976"
        | "977"
        | "978"
        | "984"
        | "986"
        | "987"
        | "988"
        | "989";
      region?:
        | "01"
        | "02"
        | "03"
        | "04"
        | "06"
        | "11"
        | "24"
        | "27"
        | "28"
        | "32"
        | "44"
        | "52"
        | "53"
        | "75"
        | "76"
        | "84"
        | "93"
        | "94"
        | "978"
        | "977"
        | "00";
      academie?:
        | "1"
        | "2"
        | "3"
        | "4"
        | "6"
        | "7"
        | "8"
        | "9"
        | "10"
        | "11"
        | "12"
        | "13"
        | "14"
        | "15"
        | "16"
        | "17"
        | "18"
        | "19"
        | "20"
        | "22"
        | "23"
        | "24"
        | "25"
        | "27"
        | "28"
        | "31"
        | "32"
        | "33"
        | "43"
        | "70"
        | "77"
        | "78";
      /**
       * Adresse complète
       */
      complete?: string;
      /**
       * Pays
       */
      pays?:
        | "AF"
        | "ZA"
        | "AL"
        | "DZ"
        | "DE"
        | "AD"
        | "AO"
        | "AG"
        | "SA"
        | "AR"
        | "AM"
        | "AU"
        | "AT"
        | "AZ"
        | "BS"
        | "BH"
        | "BD"
        | "BB"
        | "BE"
        | "BZ"
        | "BJ"
        | "BT"
        | "BY"
        | "MM"
        | "BO"
        | "BQ"
        | "BA"
        | "BW"
        | "BR"
        | "BN"
        | "BG"
        | "BF"
        | "BI"
        | "KH"
        | "CM"
        | "CA"
        | "CV"
        | "CF"
        | "CL"
        | "CN"
        | "CY"
        | "CO"
        | "KM"
        | "CG"
        | "CD"
        | "KR"
        | "KP"
        | "CR"
        | "CI"
        | "HR"
        | "CU"
        | "CW"
        | "DK"
        | "DJ"
        | "DO"
        | "DM"
        | "EG"
        | "SV"
        | "AE"
        | "EC"
        | "ER"
        | "ES"
        | "EE"
        | "SZ"
        | "US"
        | "ET"
        | "MK"
        | "FJ"
        | "FI"
        | "FR"
        | "GA"
        | "GM"
        | "GE"
        | "GH"
        | "GR"
        | "GD"
        | "GT"
        | "GN"
        | "GQ"
        | "GW"
        | "GY"
        | "HT"
        | "HN"
        | "HU"
        | "IN"
        | "ID"
        | "IR"
        | "IQ"
        | "IE"
        | "IS"
        | "IL"
        | "IT"
        | "JM"
        | "JP"
        | "JO"
        | "KZ"
        | "KE"
        | "KG"
        | "KI"
        | "XK"
        | "KW"
        | "LA"
        | "LS"
        | "LV"
        | "LB"
        | "LR"
        | "LY"
        | "LI"
        | "LT"
        | "LU"
        | "MG"
        | "MY"
        | "MW"
        | "MV"
        | "ML"
        | "MT"
        | "MA"
        | "MH"
        | "MU"
        | "MR"
        | "MX"
        | "FM"
        | "MD"
        | "MC"
        | "MN"
        | "ME"
        | "MZ"
        | "NA"
        | "NR"
        | "NP"
        | "NI"
        | "NE"
        | "NG"
        | "NO"
        | "NZ"
        | "OM"
        | "UG"
        | "UZ"
        | "PK"
        | "PW"
        | "PS"
        | "PA"
        | "PG"
        | "PY"
        | "NL"
        | "PE"
        | "PH"
        | "PL"
        | "PT"
        | "QA"
        | "RO"
        | "GB"
        | "RU"
        | "RW"
        | "KN"
        | "SM"
        | "SX"
        | "VC"
        | "LC"
        | "SB"
        | "WS"
        | "ST"
        | "SN"
        | "RS"
        | "SC"
        | "SL"
        | "SG"
        | "SK"
        | "SI"
        | "SO"
        | "SD"
        | "SS"
        | "LK"
        | "SE"
        | "CH"
        | "SR"
        | "SY"
        | "TJ"
        | "TZ"
        | "TD"
        | "CZ"
        | "TH"
        | "TL"
        | "TG"
        | "TO"
        | "TT"
        | "TN"
        | "TM"
        | "TR"
        | "TV"
        | "UA"
        | "UY"
        | "VU"
        | "VA"
        | "VE"
        | "VN"
        | "YE"
        | "ZM"
        | "ZW";
      /**
       * Code Bassin d'emploi
       */
      bassinEmploi?: string;
    };
    /**
     * Historique du statut de l'apprenant
     */
    historique_statut: {
      /**
       * Statut de l'apprenant
       */
      valeur_statut: 2 | 3 | 0;
      date_statut: Date;
      date_reception?: Date;
    }[];
    /**
     * Situation de l'apprenant avant le contrat
     */
    situation_avant_contrat?: 11 | 12 | 21 | 31 | 41 | 51 | 52 | 53 | 54 | 90 | 99;
    /**
     * Situation de l'apprenant N-1
     */
    derniere_situation?:
      | 1003
      | 1005
      | 1009
      | 1013
      | 1015
      | 1017
      | 1018
      | 1019
      | 1021
      | 1023
      | 2001
      | 2003
      | 2005
      | 2007
      | 3001
      | 3101
      | 3003
      | 3103
      | 3009
      | 3109
      | 3011
      | 3111
      | 3031
      | 3131
      | 3032
      | 3132
      | 3033
      | 3133
      | 3117
      | 3119
      | 3021
      | 3121
      | 3023
      | 3123
      | 4001
      | 4101
      | 4003
      | 4103
      | 4005
      | 4105
      | 4007
      | 4107
      | 4009
      | 4011
      | 4111
      | 4013
      | 4113
      | 4015
      | 4115
      | 4017
      | 4117
      | 4019
      | 4119
      | 4021
      | 4121
      | 5901
      | 5903
      | 5905
      | 5907
      | 5909
      | 9900
      | 9999;
    /**
     * Numéro UAI de l’établissement fréquenté l’année dernière (N-1), si déjà en apprentissage, mettre l’UAI du site de formation ou departement
     */
    dernier_organisme_uai?: string;
    /**
     * Organisme gestionnaire de l’établissement
     */
    organisme_gestionnaire?: 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 21 | 23 | 24 | 25;
    /**
     * Dernier diplôme obtenu
     */
    dernier_diplome?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 99;
    /**
     * l'apprenant(e) sera-t-il(elle) mineur(e) ? (calc)
     */
    mineur?: boolean;
    /**
     * Un mineur émancipé peut accomplir seul les actes nécessitant la majorité légale.
     */
    mineur_emancipe?: boolean;
    representant_legal?: {
      /**
       * Nom du representant légal
       */
      nom?: string;
      /**
       * Prénom du representant légal
       */
      prenom?: string;
      /**
       * l'apprenti(e) vit à la même adresse que son representant légal
       */
      meme_adresse?: boolean;
      adresse?: {
        /**
         * N° de la voie
         */
        numero?: number;
        /**
         * Indice de répétition du numéro de voie
         */
        repetition_voie?: "B" | "T" | "Q" | "C";
        /**
         * Nom de voie
         */
        voie?: string;
        /**
         * Complément d'adresse
         */
        complement?: string;
        /**
         * Le code postal doit contenir 5 caractères
         */
        code_postal?: string;
        /**
         * Le code insee doit contenir 5 caractères
         */
        code_insee?: string;
        /**
         * Commune
         */
        commune?: string;
        departement?:
          | "01"
          | "02"
          | "03"
          | "04"
          | "05"
          | "06"
          | "07"
          | "08"
          | "09"
          | "10"
          | "11"
          | "12"
          | "13"
          | "14"
          | "15"
          | "16"
          | "17"
          | "18"
          | "19"
          | "21"
          | "22"
          | "23"
          | "24"
          | "25"
          | "26"
          | "27"
          | "28"
          | "29"
          | "2A"
          | "2B"
          | "30"
          | "31"
          | "32"
          | "33"
          | "34"
          | "35"
          | "36"
          | "37"
          | "38"
          | "39"
          | "40"
          | "41"
          | "42"
          | "43"
          | "44"
          | "45"
          | "46"
          | "47"
          | "48"
          | "49"
          | "50"
          | "51"
          | "52"
          | "53"
          | "54"
          | "55"
          | "56"
          | "57"
          | "58"
          | "59"
          | "60"
          | "61"
          | "62"
          | "63"
          | "64"
          | "65"
          | "66"
          | "67"
          | "68"
          | "69"
          | "70"
          | "71"
          | "72"
          | "73"
          | "74"
          | "75"
          | "76"
          | "77"
          | "78"
          | "79"
          | "80"
          | "81"
          | "82"
          | "83"
          | "84"
          | "85"
          | "86"
          | "87"
          | "88"
          | "89"
          | "90"
          | "91"
          | "92"
          | "93"
          | "94"
          | "95"
          | "971"
          | "972"
          | "973"
          | "974"
          | "976"
          | "977"
          | "978"
          | "984"
          | "986"
          | "987"
          | "988"
          | "989";
        region?:
          | "01"
          | "02"
          | "03"
          | "04"
          | "06"
          | "11"
          | "24"
          | "27"
          | "28"
          | "32"
          | "44"
          | "52"
          | "53"
          | "75"
          | "76"
          | "84"
          | "93"
          | "94"
          | "978"
          | "977"
          | "00";
        academie?:
          | "1"
          | "2"
          | "3"
          | "4"
          | "6"
          | "7"
          | "8"
          | "9"
          | "10"
          | "11"
          | "12"
          | "13"
          | "14"
          | "15"
          | "16"
          | "17"
          | "18"
          | "19"
          | "20"
          | "22"
          | "23"
          | "24"
          | "25"
          | "27"
          | "28"
          | "31"
          | "32"
          | "33"
          | "43"
          | "70"
          | "77"
          | "78";
        /**
         * Adresse complète
         */
        complete?: string;
        /**
         * Pays
         */
        pays?:
          | "AF"
          | "ZA"
          | "AL"
          | "DZ"
          | "DE"
          | "AD"
          | "AO"
          | "AG"
          | "SA"
          | "AR"
          | "AM"
          | "AU"
          | "AT"
          | "AZ"
          | "BS"
          | "BH"
          | "BD"
          | "BB"
          | "BE"
          | "BZ"
          | "BJ"
          | "BT"
          | "BY"
          | "MM"
          | "BO"
          | "BQ"
          | "BA"
          | "BW"
          | "BR"
          | "BN"
          | "BG"
          | "BF"
          | "BI"
          | "KH"
          | "CM"
          | "CA"
          | "CV"
          | "CF"
          | "CL"
          | "CN"
          | "CY"
          | "CO"
          | "KM"
          | "CG"
          | "CD"
          | "KR"
          | "KP"
          | "CR"
          | "CI"
          | "HR"
          | "CU"
          | "CW"
          | "DK"
          | "DJ"
          | "DO"
          | "DM"
          | "EG"
          | "SV"
          | "AE"
          | "EC"
          | "ER"
          | "ES"
          | "EE"
          | "SZ"
          | "US"
          | "ET"
          | "MK"
          | "FJ"
          | "FI"
          | "FR"
          | "GA"
          | "GM"
          | "GE"
          | "GH"
          | "GR"
          | "GD"
          | "GT"
          | "GN"
          | "GQ"
          | "GW"
          | "GY"
          | "HT"
          | "HN"
          | "HU"
          | "IN"
          | "ID"
          | "IR"
          | "IQ"
          | "IE"
          | "IS"
          | "IL"
          | "IT"
          | "JM"
          | "JP"
          | "JO"
          | "KZ"
          | "KE"
          | "KG"
          | "KI"
          | "XK"
          | "KW"
          | "LA"
          | "LS"
          | "LV"
          | "LB"
          | "LR"
          | "LY"
          | "LI"
          | "LT"
          | "LU"
          | "MG"
          | "MY"
          | "MW"
          | "MV"
          | "ML"
          | "MT"
          | "MA"
          | "MH"
          | "MU"
          | "MR"
          | "MX"
          | "FM"
          | "MD"
          | "MC"
          | "MN"
          | "ME"
          | "MZ"
          | "NA"
          | "NR"
          | "NP"
          | "NI"
          | "NE"
          | "NG"
          | "NO"
          | "NZ"
          | "OM"
          | "UG"
          | "UZ"
          | "PK"
          | "PW"
          | "PS"
          | "PA"
          | "PG"
          | "PY"
          | "NL"
          | "PE"
          | "PH"
          | "PL"
          | "PT"
          | "QA"
          | "RO"
          | "GB"
          | "RU"
          | "RW"
          | "KN"
          | "SM"
          | "SX"
          | "VC"
          | "LC"
          | "SB"
          | "WS"
          | "ST"
          | "SN"
          | "RS"
          | "SC"
          | "SL"
          | "SG"
          | "SK"
          | "SI"
          | "SO"
          | "SD"
          | "SS"
          | "LK"
          | "SE"
          | "CH"
          | "SR"
          | "SY"
          | "TJ"
          | "TZ"
          | "TD"
          | "CZ"
          | "TH"
          | "TL"
          | "TG"
          | "TO"
          | "TT"
          | "TN"
          | "TM"
          | "TR"
          | "TV"
          | "UA"
          | "UY"
          | "VU"
          | "VA"
          | "VE"
          | "VN"
          | "YE"
          | "ZM"
          | "ZW";
        /**
         * Code Bassin d'emploi
         */
        bassinEmploi?: string;
      };
      /**
       * Adresse mail de contact du representant légal
       */
      courriel?: string;
      /**
       * Dans le cas d'un numéro français, il n'est pas
       *       nécessaire de saisir le "0" car l'indicateur pays est
       *       pré-renseigné.
       *       Il doit contenir 9 chiffres après l'indicatif.
       */
      telephone?: string;
      /**
       * Nomenclatures des professions et catégories socioprofessionnelles
       */
      pcs?:
        | 10
        | 21
        | 22
        | 23
        | 31
        | 33
        | 34
        | 37
        | 38
        | 42
        | 43
        | 44
        | 45
        | 46
        | 47
        | 48
        | 52
        | 53
        | 54
        | 55
        | 56
        | 61
        | 66
        | 69
        | 71
        | 72
        | 73
        | 76
        | 81
        | 82
        | 99;
    };
    /**
     * Numéro de sécurité sociale de l'apprenant
     */
    nir?: string;
    /**
     * Adresse mail du responsable 1
     */
    responsable_mail1?: string;
    /**
     * Adresse mail du responsable 2
     */
    responsable_mail2?: string;
  };
  formation?: {
    /**
     * ID de la formation
     */
    formation_id?: ObjectId;
    /**
     * Code CFD de la formation
     */
    cfd: string;
    /**
     * Code RNCP de la formation à laquelle l'apprenant est inscrit
     */
    rncp?: string;
    /**
     * Libellé long de la formation visée
     */
    libelle_long?: string;
    /**
     * Niveau de formation récupéré via Tables de Correspondances
     */
    niveau?: string | null;
    /**
     * Libellé du niveau de formation récupéré via Tables de Correspondances
     */
    niveau_libelle?: string | null;
    /**
     * Numéro de l'année dans la formation (promo)
     */
    annee?: number;
    /**
     * Date de début de la formation
     */
    date_debut_formation?: Date;
    /**
     * Date de fin de la formation
     */
    date_fin_formation?: Date;
    /**
     * Date d'obtention du diplôme
     */
    date_obtention_diplome?: Date;
    /**
     * Durée réelle de la formation en mois
     */
    duree_formation_relle?: number;
    /**
     * Période de la formation, en année (peut être sur plusieurs années)
     */
    periode?: number[];
    /**
     * Date d'inscription
     */
    date_inscription?: Date;
    /**
     * Diplôme obtenu
     */
    obtention_diplome?: boolean;
    /**
     * Date d'exclusion
     */
    date_exclusion?: Date;
    /**
     * Cause de l'exclusion
     */
    cause_exclusion?: string;
    referent_handicap?: {
      /**
       * Nom du référent handicap
       */
      nom?: string;
      /**
       * Prénom du référent handicap
       */
      prenom?: string;
      /**
       * Email du référent handicap
       */
      email?: string;
    };
    /**
     * Formation en présentiel
     */
    formation_presentielle?: boolean;
    /**
     * Durée théorique de la formation en mois
     */
    duree_theorique?: number;
    /**
     * Date de fin de la formation
     */
    date_fin?: Date;
    /**
     * Date de début de la formation
     */
    date_debut?: Date;
    /**
     * Date d'entrée en formation
     */
    date_entree?: Date;
  };
  /**
   * Historique des contrats de l'apprenant
   */
  contrats?: {
    /**
     * N° SIRET de l'employeur
     */
    siret?: string;
    /**
     * La dénomination sociale doit être celle de l'établissement dans lequel le contrat s'exécute.
     */
    denomination?: string;
    /**
     * Le type d'employeur doit être en adéquation avec son statut juridique.
     */
    type_employeur?: 11 | 12 | 13 | 14 | 15 | 16 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29;
    /**
     * Le Code NAF est composé de 4 chiffres et 1 lettre. Il est délivré par l'INSEE.[Informations sur le Code NAF.](https://www.economie.gouv.fr/entreprises/activite-entreprise-code-ape-code-naf)
     */
    naf?: string;
    /**
     * L'effectif salarié rempli automatiquement correspond à l'estimation de la base Entreprises de l'INSEE. <br/>L'effectif renseigné est celui de l’entreprise dans sa globalité (et non seulement l’effectif de l’établissement d’exécution du contrat).
     */
    nombre_de_salaries?: number;
    adresse?: {
      /**
       * N° de la voie
       */
      numero?: number;
      /**
       * Indice de répétition du numéro de voie
       */
      repetition_voie?: "B" | "T" | "Q" | "C";
      /**
       * Nom de voie
       */
      voie?: string;
      /**
       * Complément d'adresse
       */
      complement?: string;
      /**
       * Le code postal doit contenir 5 caractères
       */
      code_postal?: string;
      /**
       * Le code insee doit contenir 5 caractères
       */
      code_insee?: string;
      /**
       * Commune
       */
      commune?: string;
      departement?:
        | "01"
        | "02"
        | "03"
        | "04"
        | "05"
        | "06"
        | "07"
        | "08"
        | "09"
        | "10"
        | "11"
        | "12"
        | "13"
        | "14"
        | "15"
        | "16"
        | "17"
        | "18"
        | "19"
        | "21"
        | "22"
        | "23"
        | "24"
        | "25"
        | "26"
        | "27"
        | "28"
        | "29"
        | "2A"
        | "2B"
        | "30"
        | "31"
        | "32"
        | "33"
        | "34"
        | "35"
        | "36"
        | "37"
        | "38"
        | "39"
        | "40"
        | "41"
        | "42"
        | "43"
        | "44"
        | "45"
        | "46"
        | "47"
        | "48"
        | "49"
        | "50"
        | "51"
        | "52"
        | "53"
        | "54"
        | "55"
        | "56"
        | "57"
        | "58"
        | "59"
        | "60"
        | "61"
        | "62"
        | "63"
        | "64"
        | "65"
        | "66"
        | "67"
        | "68"
        | "69"
        | "70"
        | "71"
        | "72"
        | "73"
        | "74"
        | "75"
        | "76"
        | "77"
        | "78"
        | "79"
        | "80"
        | "81"
        | "82"
        | "83"
        | "84"
        | "85"
        | "86"
        | "87"
        | "88"
        | "89"
        | "90"
        | "91"
        | "92"
        | "93"
        | "94"
        | "95"
        | "971"
        | "972"
        | "973"
        | "974"
        | "976"
        | "977"
        | "978"
        | "984"
        | "986"
        | "987"
        | "988"
        | "989";
      region?:
        | "01"
        | "02"
        | "03"
        | "04"
        | "06"
        | "11"
        | "24"
        | "27"
        | "28"
        | "32"
        | "44"
        | "52"
        | "53"
        | "75"
        | "76"
        | "84"
        | "93"
        | "94"
        | "978"
        | "977"
        | "00";
      academie?:
        | "1"
        | "2"
        | "3"
        | "4"
        | "6"
        | "7"
        | "8"
        | "9"
        | "10"
        | "11"
        | "12"
        | "13"
        | "14"
        | "15"
        | "16"
        | "17"
        | "18"
        | "19"
        | "20"
        | "22"
        | "23"
        | "24"
        | "25"
        | "27"
        | "28"
        | "31"
        | "32"
        | "33"
        | "43"
        | "70"
        | "77"
        | "78";
      /**
       * Adresse complète
       */
      complete?: string;
      /**
       * Pays
       */
      pays?:
        | "AF"
        | "ZA"
        | "AL"
        | "DZ"
        | "DE"
        | "AD"
        | "AO"
        | "AG"
        | "SA"
        | "AR"
        | "AM"
        | "AU"
        | "AT"
        | "AZ"
        | "BS"
        | "BH"
        | "BD"
        | "BB"
        | "BE"
        | "BZ"
        | "BJ"
        | "BT"
        | "BY"
        | "MM"
        | "BO"
        | "BQ"
        | "BA"
        | "BW"
        | "BR"
        | "BN"
        | "BG"
        | "BF"
        | "BI"
        | "KH"
        | "CM"
        | "CA"
        | "CV"
        | "CF"
        | "CL"
        | "CN"
        | "CY"
        | "CO"
        | "KM"
        | "CG"
        | "CD"
        | "KR"
        | "KP"
        | "CR"
        | "CI"
        | "HR"
        | "CU"
        | "CW"
        | "DK"
        | "DJ"
        | "DO"
        | "DM"
        | "EG"
        | "SV"
        | "AE"
        | "EC"
        | "ER"
        | "ES"
        | "EE"
        | "SZ"
        | "US"
        | "ET"
        | "MK"
        | "FJ"
        | "FI"
        | "FR"
        | "GA"
        | "GM"
        | "GE"
        | "GH"
        | "GR"
        | "GD"
        | "GT"
        | "GN"
        | "GQ"
        | "GW"
        | "GY"
        | "HT"
        | "HN"
        | "HU"
        | "IN"
        | "ID"
        | "IR"
        | "IQ"
        | "IE"
        | "IS"
        | "IL"
        | "IT"
        | "JM"
        | "JP"
        | "JO"
        | "KZ"
        | "KE"
        | "KG"
        | "KI"
        | "XK"
        | "KW"
        | "LA"
        | "LS"
        | "LV"
        | "LB"
        | "LR"
        | "LY"
        | "LI"
        | "LT"
        | "LU"
        | "MG"
        | "MY"
        | "MW"
        | "MV"
        | "ML"
        | "MT"
        | "MA"
        | "MH"
        | "MU"
        | "MR"
        | "MX"
        | "FM"
        | "MD"
        | "MC"
        | "MN"
        | "ME"
        | "MZ"
        | "NA"
        | "NR"
        | "NP"
        | "NI"
        | "NE"
        | "NG"
        | "NO"
        | "NZ"
        | "OM"
        | "UG"
        | "UZ"
        | "PK"
        | "PW"
        | "PS"
        | "PA"
        | "PG"
        | "PY"
        | "NL"
        | "PE"
        | "PH"
        | "PL"
        | "PT"
        | "QA"
        | "RO"
        | "GB"
        | "RU"
        | "RW"
        | "KN"
        | "SM"
        | "SX"
        | "VC"
        | "LC"
        | "SB"
        | "WS"
        | "ST"
        | "SN"
        | "RS"
        | "SC"
        | "SL"
        | "SG"
        | "SK"
        | "SI"
        | "SO"
        | "SD"
        | "SS"
        | "LK"
        | "SE"
        | "CH"
        | "SR"
        | "SY"
        | "TJ"
        | "TZ"
        | "TD"
        | "CZ"
        | "TH"
        | "TL"
        | "TG"
        | "TO"
        | "TT"
        | "TN"
        | "TM"
        | "TR"
        | "TV"
        | "UA"
        | "UY"
        | "VU"
        | "VA"
        | "VE"
        | "VN"
        | "YE"
        | "ZM"
        | "ZW";
      /**
       * Code Bassin d'emploi
       */
      bassinEmploi?: string;
    };
    /**
     * Date de début du contrat
     */
    date_debut: Date;
    /**
     * Date de fin du contrat
     */
    date_fin: Date;
    /**
     * Date de rupture du contrat
     */
    date_rupture?: Date;
    /**
     * Cause de rupture du contrat
     */
    cause_rupture?: string;
  }[];
  /**
   * Indique les champs verrouillés
   */
  is_lock?: any;
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
  /**
   * Dossier apprenant est archivé (rétention maximum 5 ans)
   */
  archive?: boolean;
  /**
   * Erreurs de validation de cet effectif
   */
  validation_errors?: {
    /**
     * Nom du champ en erreur
     */
    fieldName?: string;
    /**
     * Type d'erreur
     */
    type?: string;
    /**
     * Valeur fournie en entrée
     */
    inputValue?: string;
    /**
     * Message de l'erreur
     */
    message?: string;
  }[];
  /**
   * Propriétés calculées ou récupérées d'autres collections
   */
  _computed?: {
    organisme?: {
      region?:
        | "01"
        | "02"
        | "03"
        | "04"
        | "06"
        | "11"
        | "24"
        | "27"
        | "28"
        | "32"
        | "44"
        | "52"
        | "53"
        | "75"
        | "76"
        | "84"
        | "93"
        | "94"
        | "978"
        | "977"
        | "00";
      departement?:
        | "01"
        | "02"
        | "03"
        | "04"
        | "05"
        | "06"
        | "07"
        | "08"
        | "09"
        | "10"
        | "11"
        | "12"
        | "13"
        | "14"
        | "15"
        | "16"
        | "17"
        | "18"
        | "19"
        | "21"
        | "22"
        | "23"
        | "24"
        | "25"
        | "26"
        | "27"
        | "28"
        | "29"
        | "2A"
        | "2B"
        | "30"
        | "31"
        | "32"
        | "33"
        | "34"
        | "35"
        | "36"
        | "37"
        | "38"
        | "39"
        | "40"
        | "41"
        | "42"
        | "43"
        | "44"
        | "45"
        | "46"
        | "47"
        | "48"
        | "49"
        | "50"
        | "51"
        | "52"
        | "53"
        | "54"
        | "55"
        | "56"
        | "57"
        | "58"
        | "59"
        | "60"
        | "61"
        | "62"
        | "63"
        | "64"
        | "65"
        | "66"
        | "67"
        | "68"
        | "69"
        | "70"
        | "71"
        | "72"
        | "73"
        | "74"
        | "75"
        | "76"
        | "77"
        | "78"
        | "79"
        | "80"
        | "81"
        | "82"
        | "83"
        | "84"
        | "85"
        | "86"
        | "87"
        | "88"
        | "89"
        | "90"
        | "91"
        | "92"
        | "93"
        | "94"
        | "95"
        | "971"
        | "972"
        | "973"
        | "974"
        | "976"
        | "977"
        | "978"
        | "984"
        | "986"
        | "987"
        | "988"
        | "989";
      academie?:
        | "1"
        | "2"
        | "3"
        | "4"
        | "6"
        | "7"
        | "8"
        | "9"
        | "10"
        | "11"
        | "12"
        | "13"
        | "14"
        | "15"
        | "16"
        | "17"
        | "18"
        | "19"
        | "20"
        | "22"
        | "23"
        | "24"
        | "25"
        | "27"
        | "28"
        | "31"
        | "32"
        | "33"
        | "43"
        | "70"
        | "77"
        | "78";
      reseaux?: (
        | "ADEN"
        | "CMA"
        | "AGRI"
        | "ANASUP"
        | "CCI"
        | "CFA_EC"
        | "COMP_DU_DEVOIR"
        | "GRETA"
        | "UIMM"
        | "BTP_CFA"
        | "MFR"
        | "AFTRAL"
        | "GRETA_VAUCLUSE"
        | "CFA_SAT"
        | "EN_HORS_MURS"
        | "EN_CFA_ACADEMIQUE"
        | "EN_EPLE"
      )[];
      bassinEmploi?: string;
      uai?: string;
      siret?: string;
      /**
       * organismes.fiabilisation_statut == "FIABLE" && ferme != false
       */
      fiable?: boolean;
    };
  };
}
