// auto-generated by bson-schema-to-typescript
import { ObjectId } from "mongodb";

export interface EffectifsQueue {
  /**
   * Nom de l'apprenant
   */
  nom_apprenant?: any;
  /**
   * Prénom de l'apprenant
   */
  prenom_apprenant?: any;
  /**
   * Date de naissance de l'apprenant
   */
  date_de_naissance_apprenant?: any;
  /**
   * Code UAI de l'établissement
   */
  uai_etablissement?: any;
  /**
   * Nom de l'organisme de formation
   */
  nom_etablissement?: any;
  /**
   * Code CFD de la formation
   */
  id_formation?: any;
  /**
   * Année scolaire sur laquelle l'apprenant est enregistré (ex: "2020-2021")
   */
  annee_scolaire?: any;
  /**
   * 0,2,3
   */
  statut_apprenant?: any;
  date_metier_mise_a_jour_statut?: any;
  /**
   * Identifiant de l'apprenant dans l'erp
   */
  id_erp_apprenant?: any;
  /**
   * N° INE de l'apprenant
   */
  ine_apprenant?: any;
  /**
   * Adresse mail de contact de l'apprenant
   */
  email_contact?: any;
  /**
   * Téléphone de l'apprenant
   */
  tel_apprenant?: any;
  /**
   * Code commune insee de l'apprenant
   */
  code_commune_insee_apprenant?: any;
  /**
   * N° SIRET de l'établissement
   */
  siret_etablissement?: any;
  /**
   * Libellé long de la formation visée
   */
  libelle_long_formation?: any;
  /**
   * Période de la formation, en année (peut être sur plusieurs années)
   */
  periode_formation?: any;
  /**
   * Numéro de l'année dans la formation (promo)
   */
  annee_formation?: any;
  /**
   * Code RNCP de la formation à laquelle l'apprenant est inscrit
   */
  formation_rncp?: any;
  /**
   * Date de début du contrat
   */
  contrat_date_debut?: any;
  /**
   * Date de fin du contrat
   */
  contrat_date_fin?: any;
  /**
   * Date de rupture du contrat
   */
  contrat_date_rupture?: any;
  /**
   * Source du dossier apprenant (Ymag, Gesti, TDB_MANUEL, TDB_FILE...)
   */
  source: string;
  /**
   * Id de l'effectif associé
   */
  effectif_id?: ObjectId;
  /**
   * Id de l'organisme associé
   */
  organisme_id?: ObjectId;
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout en base de données
   */
  created_at: Date;
  /**
   * Date de process des données
   */
  processed_at?: Date;
  /**
   * Erreur rencontrée lors de la création de l'effectif
   */
  error?: any;
  /**
   * Erreurs de validation de cet effectif
   */
  validation_errors?: {
    /**
     * message d'erreur
     */
    message?: any;
    /**
     * champ en erreur
     */
    path?: any;
  }[];
}
