// auto-generated by bson-schema-to-typescript

export interface EffectifsQueue {
  nom_apprenant?: any;
  prenom_apprenant?: any;
  date_de_naissance_apprenant?: any;
  uai_etablissement?: any;
  nom_etablissement?: any;
  id_formation?: any;
  /**
   * Année scolaire sur laquelle l'apprenant est enregistré (ex: "2020-2021")
   */
  annee_scolaire?: any;
  statut_apprenant?: any;
  date_metier_mise_a_jour_statut?: any;
  /**
   * Identifiant de l'apprenant dans l'erp
   */
  id_erp_apprenant?: any;
  ine_apprenant?: any;
  email_contact?: any;
  tel_apprenant?: any;
  code_commune_insee_apprenant?: any;
  siret_etablissement?: any;
  libelle_long_formation?: any;
  periode_formation?: any;
  /**
   * Année de formation
   */
  annee_formation?: any;
  formation_rncp?: any;
  contrat_date_debut?: any;
  contrat_date_fin?: any;
  contrat_date_rupture?: any;
  /**
   * Source du dossier apprenant (Ymag, Gesti, TDB_MANUEL, TDB_FILE...)
   */
  source?: string;
  /**
   * Id de l'effectif associé
   */
  effectif_id?: any;
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
  /**
   * Date de process des données
   */
  processed_at?: Date;
  /**
   * Erreur rencontré lors de la création de l'effectif
   */
  error?: any;
  /**
   * Erreurs de validation de cet effectif
   */
  validation_errors?: {
    /**
     * message d'erreur
     */
    message?: any;
    /**
     * champ en erreur
     */
    path?: any;
  }[];
}
