// auto-generated by bson-schema-to-typescript
import { ObjectId } from "mongodb";

export interface EffectifsV3Queue {
  apprenant?: {
    /**
     * Nom de l'apprenant
     */
    nom?: any;
    /**
     * Prénom de l'apprenant
     */
    prenom?: any;
    /**
     * Date de naissance de l'apprenant
     */
    date_de_naissance?: any;
    /**
     * 0,2,3
     */
    statut?: any;
    date_metier_mise_a_jour_statut?: any;
    /**
     * Identifiant de l'apprenant dans l'erp
     */
    id_erp?: any;
    /**
     * N° INE de l'apprenant
     */
    ine?: any;
    /**
     * Adresse mail de contact de l'apprenant
     */
    email?: any;
    /**
     * Téléphone de l'apprenant
     */
    telephone?: any;
    /**
     * Code commune insee de l'apprenant
     */
    code_commune_insee?: any;
    /**
     * Sexe de l'apprenant (M: Homme, F: Femme)
     */
    sexe?: any;
    /**
     * Reconnaissance de la Qualité de Travailleur Handicapé de l'apprenant
     */
    rqth?: any;
    /**
     * Date de reconnaissance du RQTH de l'apprenant
     */
    date_rqth?: any;
  };
  /**
   * Information sur l'établissement responsable
   */
  etablissement_responsable?: {
    /**
     * N° SIRET de l'établissement
     */
    siret?: any;
    /**
     * Code UAI de l'établissement
     */
    uai?: any;
    /**
     * Nom de l'organisme de formation
     */
    nom?: any;
    /**
     * Le code insee doit contenir 5 caractères
     */
    code_commune_insee?: any;
  };
  /**
   * Information sur l'établissement formateur
   */
  etablissement_formateur?: {
    /**
     * N° SIRET de l'établissement
     */
    siret?: any;
    /**
     * Code UAI de l'établissement
     */
    uai?: any;
    /**
     * Nom de l'organisme de formation
     */
    nom?: any;
    /**
     * Le code insee doit contenir 5 caractères
     */
    code_commune_insee?: any;
  };
  formation?: {
    /**
     * Libellé long de la formation visée
     */
    libelle_long?: any;
    /**
     * Période de la formation, en année (peut être sur plusieurs années)
     */
    periode?: any;
    /**
     * Année scolaire sur laquelle l'apprenant est enregistré (ex: "2020-2021")
     */
    annee_scolaire?: any;
    /**
     * Numéro de l'année dans la formation (promo)
     */
    annee?: any;
    /**
     * Code RNCP de la formation à laquelle l'apprenant est inscrit
     */
    code_rncp?: any;
    /**
     * Code CFD de la formation
     */
    code_cfd?: any;
    /**
     * Date de début de la formation
     */
    date_inscription?: any;
    /**
     * Date de début de la formation
     */
    date_entree?: any;
    /**
     * Date de fin de la formation
     */
    date_fin?: any;
    obtention_diplome?: any;
    /**
     * Date d'obtention du diplôme
     */
    date_obtention_diplome?: any;
    date_exclusion?: any;
    cause_exclusion?: any;
    referent_handicap?: {
      nom?: any;
      prenom?: any;
      email?: any;
    };
  };
  /**
   * Information sur le contrat d'apprentissage
   */
  contrat?: {
    /**
     * Date de début du contrat
     */
    date_debut?: any;
    /**
     * Date de fin du contrat
     */
    date_fin?: any;
    /**
     * Date de rupture du contrat
     */
    date_rupture?: any;
    /**
     * Cause de rupture du contrat
     */
    cause_rupture?: any;
  };
  /**
   * Information sur l'employeur de l'apprenti
   */
  employeur?: {
    /**
     * N° SIRET de l'établissement
     */
    siret?: any;
    /**
     * Le code insee doit contenir 5 caractères
     */
    code_commune_insee?: any;
    /**
     * Code NAF de l'employeur
     */
    code_naf?: any;
  };
  /**
   * Source du dossier apprenant (Ymag, Gesti, TDB_MANUEL, TDB_FILE...)
   */
  source: string;
  /**
   * Id de l'effectif associé
   */
  effectif_id?: ObjectId;
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout en base de données
   */
  created_at: Date;
  /**
   * Date de process des données
   */
  processed_at?: Date;
  /**
   * Erreur rencontrée lors de la création de l'effectif
   */
  error?: any;
  /**
   * Erreurs de validation de cet effectif
   */
  validation_errors?: {
    /**
     * message d'erreur
     */
    message?: any;
    /**
     * champ en erreur
     */
    path?: any;
  }[];
}
