// auto-generated by bson-schema-to-typescript
import { ObjectId } from "mongodb";

export interface EffectifsDuplicatesGroup {
  /**
   * Organisme id
   */
  organisme_id: ObjectId;
  /**
   * Liste des effectifs en doublon
   */
  duplicatesEffectifs: {
    /**
     * Identifiant de l'effectif en doublon
     */
    _id: ObjectId;
    /**
     * Statut de l'effectif en doublon
     */
    statut?: 0 | 1 | 2 | 3;
  }[];
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
}
