// auto-generated by bson-schema-to-typescript

export interface Formation {
  /**
   * Code CFD de la formation
   */
  cfd: string;
  /**
   * Date d'ouverture du CFD
   */
  cfd_start_date?: Date | null;
  /**
   * Date de fermeture du CFD
   */
  cfd_end_date?: Date | null;
  /**
   * Libellé normalisé depuis Tables de Correspondances
   */
  libelle?: string | null;
  /**
   * Liste des codes RNCPs de la formation récupéré depuis Tables de Correspondances
   */
  rncps?: string[];
  /**
   * Niveau de formation récupéré via Tables de Correspondances
   */
  niveau?: string | null;
  /**
   * Libellé du niveau de formation récupéré via Tables de Correspondances
   */
  niveau_libelle?: string | null;
  /**
   * Les domaines métiers rattachés à la formation
   */
  metiers?: string[];
  /**
   * Durée de la formation théorique
   */
  duree?: string | null;
  /**
   * Année de la formation (cursus)
   */
  annee?: string | null;
  /**
   * Date d'update en base de données
   */
  updated_at?: Date | null;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
}
