// auto-generated by bson-schema-to-typescript

export interface Invitation {
  _id?: any;
  /**
   * Jeton d'invitation
   */
  token: string;
  /**
   * Email destinataire
   */
  email: string;
  /**
   * Organisation cible de l'invitation
   */
  organisation_id: any;
  /**
   * Date de création en base de données
   */
  created_at?: Date;
}
