// auto-generated by bson-schema-to-typescript

export interface Job {
  /**
   * Identifiant unique
   */
  /**
   * Le nom de la tâche
   */
  name: string;
  /**
   * Type du job simple ou cron
   */
  type: "simple" | "cron" | "cron_task";
  /**
   * Statut courant du job
   */
  status: "pending" | "will_start" | "running" | "finished" | "blocked" | "errored";
  /**
   * Si le job est synchrone
   */
  sync?: boolean;
  /**
   * La donnée liéé à la tâche
   */
  payload?: any;
  /**
   * Les valeurs de retours du job
   */
  output?: any;
  /**
   * standard cron string exemple: '* /2 * * * *'
   */
  cron_string?: string;
  /**
   * Date de lancement programmée
   */
  scheduled_for: Date;
  /**
   * Date de lancement
   */
  started_at?: Date;
  /**
   * Date de fin d'execution
   */
  ended_at?: Date;
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
}
