// auto-generated by bson-schema-to-typescript

export interface OrganismesSoltea {
  /**
   * Code UAI de l'établissement
   */
  uai?: string | null;
  /**
   * N° SIRET de l'établissement
   */
  siret?: string | null;
  raison_sociale?: string | null;
  commune?: string | null;
  code_postal?: string | null;
  departement?: string | null;
}
