// auto-generated by bson-schema-to-typescript

export interface OrganismesReferentiel {
  siret: string;
  uai?: string;
  raison_sociale?: string;
  enseigne?: string;
  siege_social?: boolean;
  numero_declaration_activite?: string;
  etat_administratif?: "actif" | "fermé";
  nature: "responsable" | "formateur" | "responsable_formateur" | "inconnue";
  adresse?: {
    label?: string;
    code_postal: string;
    code_insee: string;
    localite: string;
    departement?: {
      code: string;
      nom: string;
    };
    region: {
      code: string;
      nom: string;
    };
    academie: {
      code: string;
      nom: string;
    };
    geojson?: {
      type: string;
      geometry: {
        type: string;
        coordinates: any;
      };
      properties?: {
        score?: number;
        source?: string;
      };
    };
  };
  forme_juridique?: {
    code: string;
    label: string;
  };
  qualiopi?: boolean;
  lieux_de_formation: {
    uai?: string;
    uai_fiable?: boolean;
  }[];
  /**
   * Formations de cet organisme
   */
  contacts?: {
    email?: string;
    confirmé?: boolean;
    date_collecte?: string;
    sources?: string[];
  }[];
  relations?: {
    type?: "formateur->responsable" | "responsable->formateur" | "entreprise";
    siret?: string;
    uai?: string | null;
    referentiel?: boolean;
    label?: string;
    sources?: string[];
  }[];
}
