// auto-generated by bson-schema-to-typescript
import { ObjectId } from "mongodb";

export interface Organisme {
  /**
   * Code UAI de l'établissement
   */
  uai?: string;
  /**
   * N° SIRET de l'établissement
   */
  siret: string;
  /**
   * Réseaux du CFA, s'ils existent
   */
  reseaux?: (
    | "ADEN"
    | "CMA"
    | "AGRI"
    | "ANASUP"
    | "CCI"
    | "CFA_EC"
    | "COMP_DU_DEVOIR"
    | "GRETA"
    | "UIMM"
    | "BTP_CFA"
    | "MFR"
    | "AFTRAL"
    | "GRETA_VAUCLUSE"
    | "CFA_SAT"
    | "EN_HORS_MURS"
    | "EN_CFA_ACADEMIQUE"
    | "EN_EPLE"
  )[];
  /**
   * ERPs rattachés au CFA, s'ils existent
   */
  erps?: string[];
  /**
   * Compteur sur le nombre d'effectifs de l'organisme
   */
  effectifs_count?: number;
  /**
   * Compteur sur le nombre d'effectifs de l'organisme sur l'année courante
   */
  effectifs_current_year_count?: number;
  /**
   * Nature de l'organisme de formation
   */
  nature?: "responsable" | "formateur" | "responsable_formateur" | "lieu_formation" | "inconnue";
  /**
   * Nom de l'organisme de formation
   */
  nom?: string;
  /**
   * Enseigne de l'organisme de formation
   */
  enseigne?: string;
  /**
   * Raison sociale de l'organisme de formation
   */
  raison_sociale?: string;
  /**
   * Adresse de l'établissement
   */
  adresse?: {
    /**
     * N° de la voie
     */
    numero?: number;
    /**
     * Indice de répétition du numéro de voie
     */
    repetition_voie?: "B" | "T" | "Q" | "C";
    /**
     * Nom de voie
     */
    voie?: string;
    /**
     * Complément d'adresse
     */
    complement?: string;
    /**
     * Le code postal doit contenir 5 caractères
     */
    code_postal?: string;
    /**
     * Le code insee doit contenir 5 caractères
     */
    code_insee?: string;
    /**
     * Commune
     */
    commune?: string;
    departement?:
      | "01"
      | "02"
      | "03"
      | "04"
      | "05"
      | "06"
      | "07"
      | "08"
      | "09"
      | "10"
      | "11"
      | "12"
      | "13"
      | "14"
      | "15"
      | "16"
      | "17"
      | "18"
      | "19"
      | "21"
      | "22"
      | "23"
      | "24"
      | "25"
      | "26"
      | "27"
      | "28"
      | "29"
      | "2A"
      | "2B"
      | "30"
      | "31"
      | "32"
      | "33"
      | "34"
      | "35"
      | "36"
      | "37"
      | "38"
      | "39"
      | "40"
      | "41"
      | "42"
      | "43"
      | "44"
      | "45"
      | "46"
      | "47"
      | "48"
      | "49"
      | "50"
      | "51"
      | "52"
      | "53"
      | "54"
      | "55"
      | "56"
      | "57"
      | "58"
      | "59"
      | "60"
      | "61"
      | "62"
      | "63"
      | "64"
      | "65"
      | "66"
      | "67"
      | "68"
      | "69"
      | "70"
      | "71"
      | "72"
      | "73"
      | "74"
      | "75"
      | "76"
      | "77"
      | "78"
      | "79"
      | "80"
      | "81"
      | "82"
      | "83"
      | "84"
      | "85"
      | "86"
      | "87"
      | "88"
      | "89"
      | "90"
      | "91"
      | "92"
      | "93"
      | "94"
      | "95"
      | "971"
      | "972"
      | "973"
      | "974"
      | "975"
      | "976"
      | "977"
      | "978"
      | "984"
      | "986"
      | "987"
      | "988"
      | "989";
    region?:
      | "01"
      | "02"
      | "03"
      | "04"
      | "06"
      | "11"
      | "24"
      | "27"
      | "28"
      | "32"
      | "44"
      | "52"
      | "53"
      | "75"
      | "76"
      | "84"
      | "93"
      | "94"
      | "978"
      | "977"
      | "00";
    academie?:
      | "1"
      | "2"
      | "3"
      | "4"
      | "6"
      | "7"
      | "8"
      | "9"
      | "10"
      | "11"
      | "12"
      | "13"
      | "14"
      | "15"
      | "16"
      | "17"
      | "18"
      | "19"
      | "20"
      | "22"
      | "23"
      | "24"
      | "25"
      | "27"
      | "28"
      | "31"
      | "32"
      | "33"
      | "43"
      | "44"
      | "70"
      | "77"
      | "78";
    /**
     * Adresse complète
     */
    complete?: string;
    /**
     * Pays
     */
    pays?:
      | "AF"
      | "ZA"
      | "AL"
      | "DZ"
      | "DE"
      | "AD"
      | "AO"
      | "AG"
      | "SA"
      | "AR"
      | "AM"
      | "AU"
      | "AT"
      | "AZ"
      | "BS"
      | "BH"
      | "BD"
      | "BB"
      | "BE"
      | "BZ"
      | "BJ"
      | "BT"
      | "BY"
      | "MM"
      | "BO"
      | "BQ"
      | "BA"
      | "BW"
      | "BR"
      | "BN"
      | "BG"
      | "BF"
      | "BI"
      | "KH"
      | "CM"
      | "CA"
      | "CV"
      | "CF"
      | "CL"
      | "CN"
      | "CY"
      | "CO"
      | "KM"
      | "CG"
      | "CD"
      | "KR"
      | "KP"
      | "CR"
      | "CI"
      | "HR"
      | "CU"
      | "CW"
      | "DK"
      | "DJ"
      | "DO"
      | "DM"
      | "EG"
      | "SV"
      | "AE"
      | "EC"
      | "ER"
      | "ES"
      | "EE"
      | "SZ"
      | "US"
      | "ET"
      | "MK"
      | "FJ"
      | "FI"
      | "FR"
      | "GA"
      | "GM"
      | "GE"
      | "GH"
      | "GR"
      | "GD"
      | "GT"
      | "GN"
      | "GQ"
      | "GW"
      | "GY"
      | "HT"
      | "HN"
      | "HU"
      | "IN"
      | "ID"
      | "IR"
      | "IQ"
      | "IE"
      | "IS"
      | "IL"
      | "IT"
      | "JM"
      | "JP"
      | "JO"
      | "KZ"
      | "KE"
      | "KG"
      | "KI"
      | "XK"
      | "KW"
      | "LA"
      | "LS"
      | "LV"
      | "LB"
      | "LR"
      | "LY"
      | "LI"
      | "LT"
      | "LU"
      | "MG"
      | "MY"
      | "MW"
      | "MV"
      | "ML"
      | "MT"
      | "MA"
      | "MH"
      | "MU"
      | "MR"
      | "MX"
      | "FM"
      | "MD"
      | "MC"
      | "MN"
      | "ME"
      | "MZ"
      | "NA"
      | "NR"
      | "NP"
      | "NI"
      | "NE"
      | "NG"
      | "NO"
      | "NZ"
      | "OM"
      | "UG"
      | "UZ"
      | "PK"
      | "PW"
      | "PS"
      | "PA"
      | "PG"
      | "PY"
      | "NL"
      | "PE"
      | "PH"
      | "PL"
      | "PT"
      | "QA"
      | "RO"
      | "GB"
      | "RU"
      | "RW"
      | "KN"
      | "SM"
      | "SX"
      | "VC"
      | "LC"
      | "SB"
      | "WS"
      | "ST"
      | "SN"
      | "RS"
      | "SC"
      | "SL"
      | "SG"
      | "SK"
      | "SI"
      | "SO"
      | "SD"
      | "SS"
      | "LK"
      | "SE"
      | "CH"
      | "SR"
      | "SY"
      | "TJ"
      | "TZ"
      | "TD"
      | "CZ"
      | "TH"
      | "TL"
      | "TG"
      | "TO"
      | "TT"
      | "TN"
      | "TM"
      | "TR"
      | "TV"
      | "UA"
      | "UY"
      | "VU"
      | "VA"
      | "VE"
      | "VN"
      | "YE"
      | "ZM"
      | "ZW";
    /**
     * Code Bassin d'emploi
     */
    bassinEmploi?: string;
  };
  /**
   * Formations de cet organisme
   */
  relatedFormations?: {
    formation_id?: ObjectId;
    /**
     * Clé unique de la formation
     */
    cle_ministere_educatif?: string;
    /**
     * Année millésime de la formation pour cet organisme
     */
    annee_formation?: number;
    organismes?: {
      organisme_id?: ObjectId;
      nature?: "responsable" | "formateur" | "responsable_formateur" | "lieu_formation" | "inconnue";
      /**
       * Code UAI du lieu de formation (optionnel)
       */
      uai?: string;
      /**
       * Siret du lieu de formation (optionnel)
       */
      siret?: string;
      /**
       * Adresse du lieu de formation (optionnel)
       */
      adresse?: {
        /**
         * N° de la voie
         */
        numero?: number;
        /**
         * Indice de répétition du numéro de voie
         */
        repetition_voie?: "B" | "T" | "Q" | "C";
        /**
         * Nom de voie
         */
        voie?: string;
        /**
         * Complément d'adresse
         */
        complement?: string;
        /**
         * Le code postal doit contenir 5 caractères
         */
        code_postal?: string;
        /**
         * Le code insee doit contenir 5 caractères
         */
        code_insee?: string;
        /**
         * Commune
         */
        commune?: string;
        departement?:
          | "01"
          | "02"
          | "03"
          | "04"
          | "05"
          | "06"
          | "07"
          | "08"
          | "09"
          | "10"
          | "11"
          | "12"
          | "13"
          | "14"
          | "15"
          | "16"
          | "17"
          | "18"
          | "19"
          | "21"
          | "22"
          | "23"
          | "24"
          | "25"
          | "26"
          | "27"
          | "28"
          | "29"
          | "2A"
          | "2B"
          | "30"
          | "31"
          | "32"
          | "33"
          | "34"
          | "35"
          | "36"
          | "37"
          | "38"
          | "39"
          | "40"
          | "41"
          | "42"
          | "43"
          | "44"
          | "45"
          | "46"
          | "47"
          | "48"
          | "49"
          | "50"
          | "51"
          | "52"
          | "53"
          | "54"
          | "55"
          | "56"
          | "57"
          | "58"
          | "59"
          | "60"
          | "61"
          | "62"
          | "63"
          | "64"
          | "65"
          | "66"
          | "67"
          | "68"
          | "69"
          | "70"
          | "71"
          | "72"
          | "73"
          | "74"
          | "75"
          | "76"
          | "77"
          | "78"
          | "79"
          | "80"
          | "81"
          | "82"
          | "83"
          | "84"
          | "85"
          | "86"
          | "87"
          | "88"
          | "89"
          | "90"
          | "91"
          | "92"
          | "93"
          | "94"
          | "95"
          | "971"
          | "972"
          | "973"
          | "974"
          | "975"
          | "976"
          | "977"
          | "978"
          | "984"
          | "986"
          | "987"
          | "988"
          | "989";
        region?:
          | "01"
          | "02"
          | "03"
          | "04"
          | "06"
          | "11"
          | "24"
          | "27"
          | "28"
          | "32"
          | "44"
          | "52"
          | "53"
          | "75"
          | "76"
          | "84"
          | "93"
          | "94"
          | "978"
          | "977"
          | "00";
        academie?:
          | "1"
          | "2"
          | "3"
          | "4"
          | "6"
          | "7"
          | "8"
          | "9"
          | "10"
          | "11"
          | "12"
          | "13"
          | "14"
          | "15"
          | "16"
          | "17"
          | "18"
          | "19"
          | "20"
          | "22"
          | "23"
          | "24"
          | "25"
          | "27"
          | "28"
          | "31"
          | "32"
          | "33"
          | "43"
          | "44"
          | "70"
          | "77"
          | "78";
        /**
         * Adresse complète
         */
        complete?: string;
        /**
         * Pays
         */
        pays?:
          | "AF"
          | "ZA"
          | "AL"
          | "DZ"
          | "DE"
          | "AD"
          | "AO"
          | "AG"
          | "SA"
          | "AR"
          | "AM"
          | "AU"
          | "AT"
          | "AZ"
          | "BS"
          | "BH"
          | "BD"
          | "BB"
          | "BE"
          | "BZ"
          | "BJ"
          | "BT"
          | "BY"
          | "MM"
          | "BO"
          | "BQ"
          | "BA"
          | "BW"
          | "BR"
          | "BN"
          | "BG"
          | "BF"
          | "BI"
          | "KH"
          | "CM"
          | "CA"
          | "CV"
          | "CF"
          | "CL"
          | "CN"
          | "CY"
          | "CO"
          | "KM"
          | "CG"
          | "CD"
          | "KR"
          | "KP"
          | "CR"
          | "CI"
          | "HR"
          | "CU"
          | "CW"
          | "DK"
          | "DJ"
          | "DO"
          | "DM"
          | "EG"
          | "SV"
          | "AE"
          | "EC"
          | "ER"
          | "ES"
          | "EE"
          | "SZ"
          | "US"
          | "ET"
          | "MK"
          | "FJ"
          | "FI"
          | "FR"
          | "GA"
          | "GM"
          | "GE"
          | "GH"
          | "GR"
          | "GD"
          | "GT"
          | "GN"
          | "GQ"
          | "GW"
          | "GY"
          | "HT"
          | "HN"
          | "HU"
          | "IN"
          | "ID"
          | "IR"
          | "IQ"
          | "IE"
          | "IS"
          | "IL"
          | "IT"
          | "JM"
          | "JP"
          | "JO"
          | "KZ"
          | "KE"
          | "KG"
          | "KI"
          | "XK"
          | "KW"
          | "LA"
          | "LS"
          | "LV"
          | "LB"
          | "LR"
          | "LY"
          | "LI"
          | "LT"
          | "LU"
          | "MG"
          | "MY"
          | "MW"
          | "MV"
          | "ML"
          | "MT"
          | "MA"
          | "MH"
          | "MU"
          | "MR"
          | "MX"
          | "FM"
          | "MD"
          | "MC"
          | "MN"
          | "ME"
          | "MZ"
          | "NA"
          | "NR"
          | "NP"
          | "NI"
          | "NE"
          | "NG"
          | "NO"
          | "NZ"
          | "OM"
          | "UG"
          | "UZ"
          | "PK"
          | "PW"
          | "PS"
          | "PA"
          | "PG"
          | "PY"
          | "NL"
          | "PE"
          | "PH"
          | "PL"
          | "PT"
          | "QA"
          | "RO"
          | "GB"
          | "RU"
          | "RW"
          | "KN"
          | "SM"
          | "SX"
          | "VC"
          | "LC"
          | "SB"
          | "WS"
          | "ST"
          | "SN"
          | "RS"
          | "SC"
          | "SL"
          | "SG"
          | "SK"
          | "SI"
          | "SO"
          | "SD"
          | "SS"
          | "LK"
          | "SE"
          | "CH"
          | "SR"
          | "SY"
          | "TJ"
          | "TZ"
          | "TD"
          | "CZ"
          | "TH"
          | "TL"
          | "TG"
          | "TO"
          | "TT"
          | "TN"
          | "TM"
          | "TR"
          | "TV"
          | "UA"
          | "UY"
          | "VU"
          | "VA"
          | "VE"
          | "VN"
          | "YE"
          | "ZM"
          | "ZW";
        /**
         * Code Bassin d'emploi
         */
        bassinEmploi?: string;
      };
    }[];
    /**
     * Durée théorique de la formation en mois pour cet organisme
     */
    duree_formation_theorique?: number;
  }[];
  organismesFormateurs?: {
    _id?: ObjectId | null;
    siret?: string;
    uai?: string | null;
    referentiel?: boolean;
    label?: string;
    sources?: string[];
  }[];
  organismesResponsables?: {
    _id?: ObjectId | null;
    siret?: string;
    uai?: string | null;
    referentiel?: boolean;
    label?: string;
    sources?: string[];
  }[];
  /**
   * Les domaines métiers rattachés à l'établissement
   */
  metiers?: string[];
  /**
   * Date de la première transmission de données
   */
  first_transmission_date?: Date;
  /**
   * Date de la dernière transmission de données
   */
  last_transmission_date?: Date;
  /**
   * Est dans le referentiel onisep des organismes
   */
  est_dans_le_referentiel?: boolean;
  /**
   * Le siret est fermé
   */
  ferme?: boolean;
  /**
   * a la certification Qualiopi
   */
  qualiopi?: boolean;
  /**
   * Le token permettant l'accès au CFA à sa propre page
   */
  access_token?: string;
  /**
   * API key pour envoi de données
   */
  api_key?: string;
  /**
   * Uai envoyé par l'erp
   */
  api_uai?: string;
  /**
   * Siret envoyé par l'erp
   */
  api_siret?: string;
  /**
   * Date de l'interfaçage
   */
  api_configuration_date?: Date;
  /**
   * Statut de fiabilisation de l'organisme
   */
  fiabilisation_statut?:
    | "FIABLE"
    | "NON_FIABILISABLE_PB_COLLECTE"
    | "NON_FIABILISABLE_UAI_NON_VALIDEE"
    | "NON_FIABILISABLE_UAI_VALIDEE"
    | "NON_FIABILISABLE_INEXISTANT"
    | "A_CONTACTER"
    | "INCONNU"
    | "INCONNU_INSCRIPTION";
  /**
   * Mode de transmission des effectifs
   */
  mode_de_transmission?: "API" | "MANUEL";
  /**
   * Etape d'installation courante
   */
  setup_step_courante?: "STEP1" | "STEP2" | "STEP3" | "COMPLETE";
  /**
   * Flag pour identifier que c'est un organisme créé à partir d'un lieu
   */
  creation_statut?: "ORGANISME_LIEU_FORMATION";
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
}
