// auto-generated by bson-schema-to-typescript

export interface OrganismesPrepaApprentissage {
  /**
   * Code UAI de l'établissement
   */
  uai?: string | null;
  /**
   * N° SIRET de l'établissement
   */
  siret?: string | null;
  raison_sociale?: string | null;
  enseigne?: string | null;
  nature?: string | null;
  departement?: string | null;
  commune?: string | null;
  code_postal?: string | null;
  adresse?: string | null;
  prepa_apprentissage?: string | null;
}
