// auto-generated by bson-schema-to-typescript

export interface Permission {
  _id?: any;
  /**
   * Organisme id
   */
  organisme_id: null;
  /**
   * Email utilisateur
   */
  userEmail: string;
  /**
   * Role id
   */
  role: any;
  /**
   * En attente d'acceptation
   */
  pending: boolean;
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout de la permission
   */
  created_at?: Date;
}
