// auto-generated by bson-schema-to-typescript

export interface Rncp {
  rncp: string;
  nouveaux_rncp?: string[];
  intitule: string;
  niveau?: number;
  etat_fiche: string;
  actif: boolean;
  romes: string[];
}
