// auto-generated by bson-schema-to-typescript

export interface Role {
  _id?: any;
  /**
   * Nom du rôle
   */
  name: string;
  /**
   * type de rôle
   */
  type: "user" | "permission";
  /**
   * Access control level array
   */
  acl?: string[];
  /**
   * titre metier du rôle
   */
  title?: string;
  /**
   * description du rôle
   */
  description?: string;
  v?: number;
}
