// auto-generated by bson-schema-to-typescript

export interface Upload {
  _id?: any;
  /**
   * Organisme id
   */
  organisme_id: any;
  /**
   * Historique des documents uploadés
   */
  documents?: {
    /**
     * Identifiant du document
     */
    document_id: any;
    /**
     * Mapping des colonnes du fichier
     */
    mapping_column?: any;
    /**
     * Le type de document (exemple: SIFA-2021, gabarit-tableau-de-bord)
     */
    type_document?: string;
    /**
     * Le type de fichier extension
     */
    ext_fichier: "xlsx" | "xls" | "csv";
    /**
     * Le nom de fichier
     */
    nom_fichier: string;
    /**
     * Description de fichier
     */
    description_fichier?: string;
    /**
     * Chemin du fichier binaire
     */
    chemin_fichier: string;
    /**
     * Taille du fichier en bytes
     */
    taille_fichier: number;
    /**
     * Checksum fichier
     */
    hash_fichier: string;
    /**
     * Le document est confirmé par l'utilisateur
     */
    confirm?: boolean;
    /**
     * Qui a ajouté le fichier
     */
    added_by: string;
    /**
     * Date de mise à jour en base de données
     */
    updated_at?: Date;
    /**
     * Date d'ajout en base de données
     */
    created_at?: Date;
  }[];
  /**
   * Erreurs de validation de cet effectif
   */
  models?: {
    /**
     * Le type de document (exemple: SIFA-2021, gabarit-tableau-de-bord)
     */
    type_document?: string;
    /**
     * Mapping des colonnes du fichier
     */
    mapping_column?: any;
    /**
     * Le modèle est vérouillé
     */
    lock?: boolean;
  }[];
  /**
   * Snapshot backup de tous les effectifs de l'organisme
   */
  last_snapshot_effectifs?: any;
  /**
   * Date de mise à jour en base de données
   */
  updated_at?: Date;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
}
