// auto-generated by bson-schema-to-typescript

export interface User {
  /**
   * Le nom de l'utilisateur, utilisé pour l'authentification
   */
  username: string;
  /**
   * Email de l'utilisateur
   */
  email?: string | null;
  /**
   * Le mot de passe hashed
   */
  password?: string;
  /**
   * Token généré afin de sécuriser le changement de mot de passe
   */
  password_update_token?: string | null;
  /**
   * Date d'expiration du token généré afin de sécuriser le changement de mot de passe
   */
  password_update_token_expiry?: Date | null;
  permissions?: string[];
  /**
   * Date de dernière connexion
   */
  last_connection?: Date;
  /**
   * Le réseau de CFA de l'utilisateur s'il est précisé
   */
  network?: string | null;
  /**
   * La région de l'utilisateur s'il est précisé
   */
  region?: string | null;
  /**
   * L'organisme d'appartenance de l'utilisateur s'il est précisé
   */
  organisme?: string | null;
  /**
   * La date de création de l'utilisateur
   */
  created_at: Date;
}
