/* eslint-disable */
// auto-generated by bson-schema-to-typescript

export interface UsersMigration {
  _id?: any;
  /**
   * Email utilisateur
   */
  email: string;
  /**
   * Le mot de passe hashé
   */
  password?: string;
  /**
   * civilité
   */
  civility?: "Madame" | "Monsieur";
  /**
   * Le nom de l'utilisateur
   */
  nom?: string;
  /**
   * Le prénom de l'utilisateur
   */
  prenom?: string;
  /**
   * Le téléphone de l'utilisateur
   */
  telephone?: string;
  /**
   * N° SIRET
   */
  siret?: string;
  /**
   * Code UAI de l'organisme (seulement pour les utilisateurs OF)
   */
  uai?: string;
  /**
   * Appartenance à une organisation (exemple DREETS, MISSION_LOCALE..)
   */
  organisation?:
    | "TETE_DE_RESEAU"
    | "ACADEMIE"
    | "DRAAF"
    | "CARIF_OREF"
    | "DREETS"
    | "DEETS"
    | "DDETS"
    | "CONSEIL_REGIONAL"
    | "OPCO"
    | "ERP"
    | "AUTRE"
    | "POLE_EMPLOI"
    | "MISSION_LOCALE"
    | "CELLULE_APPRENTISSAGE"
    | "ORGANISME_FORMATION";
  /**
   * Organisme principe id
   */
  main_organisme_id?: any;
  /**
   * Si l'utilisateur est scopé à un réseau, le quel ?
   */
  reseau?:
    | "ADEN"
    | "CMA"
    | "AGRI"
    | "ANASUP"
    | "CCI"
    | "CFA_EC"
    | "COMP_DU_DEVOIR"
    | "GRETA"
    | "UIMM"
    | "BTP_CFA"
    | "MFR"
    | "AFTRAL"
    | "GRETA_VAUCLUSE"
    | "CFA_SAT";
  /**
   * Si l'utilisateur est scopé à un erp, le quel ?
   */
  erp?: string;
  /**
   * Si l'utilisateur est scopé à une ou des région(s), lesquelles ?
   */
  codes_region?: (
    | "01"
    | "02"
    | "03"
    | "04"
    | "06"
    | "11"
    | "24"
    | "27"
    | "28"
    | "32"
    | "44"
    | "52"
    | "53"
    | "75"
    | "76"
    | "84"
    | "93"
    | "94"
    | "978"
    | "977"
    | "00"
  )[];
  /**
   * Si l'utilisateur est scopé à une ou des académie(s), lesquelles ?
   */
  codes_academie?: (
    | "10"
    | "11"
    | "12"
    | "13"
    | "14"
    | "15"
    | "16"
    | "17"
    | "18"
    | "19"
    | "20"
    | "22"
    | "23"
    | "24"
    | "25"
    | "27"
    | "28"
    | "31"
    | "32"
    | "33"
    | "43"
    | "70"
    | "77"
    | "78"
    | "1"
    | "2"
    | "3"
    | "4"
    | "6"
    | "7"
    | "8"
    | "9"
  )[];
  /**
   * Si l'utilisateur est scopé à un ou des département(s), lesquels ?
   */
  codes_departement?: (
    | "01"
    | "02"
    | "03"
    | "04"
    | "05"
    | "06"
    | "07"
    | "08"
    | "09"
    | "10"
    | "11"
    | "12"
    | "13"
    | "14"
    | "15"
    | "16"
    | "17"
    | "18"
    | "19"
    | "21"
    | "22"
    | "23"
    | "24"
    | "25"
    | "26"
    | "27"
    | "28"
    | "29"
    | "2A"
    | "2B"
    | "30"
    | "31"
    | "32"
    | "33"
    | "34"
    | "35"
    | "36"
    | "37"
    | "38"
    | "39"
    | "40"
    | "41"
    | "42"
    | "43"
    | "44"
    | "45"
    | "46"
    | "47"
    | "48"
    | "49"
    | "50"
    | "51"
    | "52"
    | "53"
    | "54"
    | "55"
    | "56"
    | "57"
    | "58"
    | "59"
    | "60"
    | "61"
    | "62"
    | "63"
    | "64"
    | "65"
    | "66"
    | "67"
    | "68"
    | "69"
    | "70"
    | "71"
    | "72"
    | "73"
    | "74"
    | "75"
    | "76"
    | "77"
    | "78"
    | "79"
    | "80"
    | "81"
    | "82"
    | "83"
    | "84"
    | "85"
    | "86"
    | "87"
    | "88"
    | "89"
    | "90"
    | "91"
    | "92"
    | "93"
    | "94"
    | "95"
    | "971"
    | "972"
    | "973"
    | "974"
    | "976"
    | "977"
    | "978"
    | "984"
    | "986"
    | "987"
    | "988"
    | "989"
  )[];
  /**
   * true si l'utilisateur est transverse à tous les organismes
   */
  is_cross_organismes?: boolean;
  /**
   * Statut du compte
   */
  account_status?:
    | "PENDING_EMAIL_VALIDATION"
    | "PENDING_PASSWORD_SETUP"
    | "PENDING_PERMISSIONS_SETUP"
    | "PENDING_ADMIN_VALIDATION"
    | "CONFIRMED"
    | "DIRECT_PENDING_PASSWORD_SETUP";
  /**
   * Version des cgu accepté par l'utilisateur
   */
  has_accept_cgu_version?: string;
  /**
   * true si l'utilisateur est administrateur
   */
  is_admin?: boolean;
  /**
   * Roles de l'utilisateur
   */
  roles?: any[];
  /**
   * Date de création du compte
   */
  created_at?: Date;
  /**
   * Date de dernière connexion
   */
  last_connection?: Date;
  /**
   * Historique des dates de connexion
   */
  connection_history?: Date[];
  /**
   * true si besoin de reset le token
   */
  invalided_token?: boolean;
  /**
   * Date de dernière mise à jour mot de passe
   */
  password_updated_at?: Date;
  emails?: {
    token: string;
    templateName: string;
    payload?: unknown;
    sendDates: Date[];
    openDate?: Date;
    messageIds?: string[];
    error?: {
      type?: "fatal" | "soft_bounce" | "hard_bounce" | "complaint" | "invalid_email" | "blocked" | "error";
      message?: string;
    }[];
    
  }[];
  /**
   * unsubscribe email
   */
  unsubscribe?: boolean;
  v?: number;
  
}
