// auto-generated by bson-schema-to-typescript

export interface UsersMigration {
  _id?: any;
  /**
   * Email utilisateur
   */
  email: string;
  /**
   * Le mot de passe hashé
   */
  password?: string;
  /**
   * civilité
   */
  civility?: "Madame" | "Monsieur";
  /**
   * Le nom de l'utilisateur
   */
  nom?: string;
  /**
   * Le prénom de l'utilisateur
   */
  prenom?: string;
  /**
   * Le téléphone de l'utilisateur
   */
  telephone?: string;
  /**
   * Organisation à laquelle appartient l'utilisateur
   */
  organisation_id?: any;
  /**
   * Type d'organisation [temporaire pendant l'inscription en attendant d'être rattaché]
   */
  type_organisation?: string;
  /**
   * Statut du compte
   */
  account_status?:
    | "PENDING_EMAIL_VALIDATION"
    | "PENDING_PASSWORD_SETUP"
    | "PENDING_PERMISSIONS_SETUP"
    | "PENDING_ADMIN_VALIDATION"
    | "CONFIRMED"
    | "DIRECT_PENDING_PASSWORD_SETUP";
  /**
   * Version des cgu accepté par l'utilisateur
   */
  has_accept_cgu_version?: string;
  /**
   * Date de création du compte
   */
  created_at?: Date;
  /**
   * Date de dernière connexion
   */
  last_connection?: Date;
  /**
   * Historique des dates de connexion
   */
  connection_history?: Date[];
  /**
   * true si besoin de reset le token
   */
  invalided_token?: boolean;
  /**
   * Date de dernière mise à jour mot de passe
   */
  password_updated_at?: Date;
  emails?: {
    token: string;
    templateName: string;
    payload?: any;
    sendDates: Date[];
    openDate?: Date;
    messageIds?: string[];
    error?: {
      type?: "fatal" | "soft_bounce" | "hard_bounce" | "complaint" | "invalid_email" | "blocked" | "error";
      message?: string;
    }[];
  }[];
  /**
   * unsubscribe email
   */
  unsubscribe?: boolean;

  // FIXME à supprimer quand process d'inscription revu
  /**
   * N° SIRET
   * Type d'organisation [temporaire pendant l'inscription en attendant d'être rattaché]
   */
  siret?: string;
  /**
   * Code UAI de l'organisme (seulement pour les utilisateurs OF)
   */
  uai?: string;
  /**
   * Appartenance à une organisation (exemple DREETS, MISSION_LOCALE..)
   */
}
