// auto-generated by bson-schema-to-typescript

export interface UserEvent {
  _id?: any;
  /**
   * Le nom de l'utilisateur, utilisé pour l'authentification
   */
  username?: string | null;
  /**
   * L'email de l'utilisateur, utilisé pour l'authentification
   */
  user_email?: string | null;
  /**
   * La date de l'event
   */
  date: Date;
  /**
   * Le type d'action
   */
  type?: string | null;
  /**
   * L'action ayant eu lieu
   */
  action?: string;
  /**
   * Les données liées à l'action
   */
  data?: any;
}
