import { ACC_CONJOINT_MOTIF_ENUM } from "shared";

export const FREINS_MOTIFS: ACC_CONJOINT_MOTIF_ENUM[] = [
  ACC_CONJOINT_MOTIF_ENUM.LOGEMENT,
  ACC_CONJOINT_MOTIF_ENUM.MOBILITE,
  ACC_CONJOINT_MOTIF_ENUM.SANTE,
  ACC_CONJOINT_MOTIF_ENUM.ADMINISTRATIF,
  ACC_CONJOINT_MOTIF_ENUM.FINANCE,
  ACC_CONJOINT_MOTIF_ENUM.SOCIAL_FAMILIAL,
];
