export const preDefinedModels = [
  {
    type_document: "Fichier modèle fourni par le tableau de bord",
    mapping_column: {
      typeCodeDiplome: "CFD",
      annee_scolaire: "annee_scolaire",
      CFD: "CFD",
      RNCP: "RNCP",
      nom: "nom",
      prenom: "prenom",
      identifiant_unique_apprenant: "identifiant_unique_apprenant",
      annee_formation: "annee_formation",
      INE: "INE",
      sexe: "sexe",
      date_de_naissance: "date_de_naissance",
      code_postal_de_naissance: "code_postal_de_naissance",
      nationalite: "nationalite",
      regime_scolaire: "regime_scolaire",
      inscription_sportif_haut_niveau: "inscription_sportif_haut_niveau",
      courriel: "courriel",
      telephone: "telephone",
      adresse_complete: "adresse_complete",
      adresse_numero: "adresse_numero",
      adresse_repetition_voie: "adresse_repetition_voie",
      adresse_voie: "adresse_voie",
      adresse_complement: "adresse_complement",
      adresse_code_postal: "adresse_code_postal",
      adresse_code_commune_insee: "adresse_code_commune_insee",
      adresse_commune: "adresse_commune",
      situation_avant_contrat: "situation_avant_contrat",
      derniere_situation: "derniere_situation",
      dernier_organisme_uai: "dernier_organisme_uai",
      dernier_diplome: "dernier_diplome",
      mineur_emancipe: "mineur_emancipe",
      representant_legal_nom: "representant_legal_nom",
      representant_legal_prenom: "representant_legal_prenom",
      representant_legal_courriel: "representant_legal_courriel",
      representant_legal_telephone: "representant_legal_telephone",
      representant_legal_pcs: "representant_legal_pcs",
      representant_legal_adresse_complete: "representant_legal_adresse_complete",
      representant_legal_adresse_numero: "representant_legal_adresse_numero",
      representant_legal_adresse_repetition_voie: "representant_legal_adresse_repetition_voie",
      representant_legal_adresse_voie: "representant_legal_adresse_voie",
      representant_legal_adresse_complement: "representant_legal_adresse_complement",
      representant_legal_adresse_code_postal: "representant_legal_adresse_code_postal",
      representant_legal_adresse_code_commune_insee: "representant_legal_adresse_code_commune_insee",
      representant_legal_adresse_commune: "representant_legal_adresse_commune",
      dernier_statut: "dernier_statut",
      date_dernier_statut: "date_dernier_statut",
      dernier_contrat_siret: "dernier_contrat_siret",
      dernier_contrat_type_employeur: "dernier_contrat_type_employeur",
      dernier_contrat_nombre_de_salaries: "dernier_contrat_nombre_de_salaries",
      dernier_contrat_adresse_complete: "dernier_contrat_adresse_complete",
      dernier_contrat_adresse_numero: "dernier_contrat_adresse_numero",
      dernier_contrat_adresse_repetition_voie: "dernier_contrat_adresse_repetition_voie",
      dernier_contrat_adresse_voie: "dernier_contrat_adresse_voie",
      dernier_contrat_adresse_complement: "dernier_contrat_adresse_complement",
      dernier_contrat_adresse_code_postal: "dernier_contrat_adresse_code_postal",
      dernier_contrat_adresse_code_commune_insee: "dernier_contrat_adresse_code_commune_insee",
      dernier_contrat_adresse_commune: "dernier_contrat_adresse_commune",
      dernier_contrat_date_debut: "dernier_contrat_date_debut",
      dernier_contrat_date_fin: "dernier_contrat_date_fin",
      dernier_contrat_date_rupture: "dernier_contrat_date_rupture",
    },
    lock: true,
  },
];
