- name: Install Python pip
  apt: name={{ item }} update_cache=true state=present force_apt_get=yes
  with_items:
    - python-pip
    - python3-pip
  become: true

- name: Install pip dependencies, to encrypt mailhog password
  ansible.builtin.pip:
    name:
      - passlib
      - bcrypt

- name: "Deploiement de la branche {{ git_revision }}"
  shell: "sudo /opt/flux-retour-cfas/start-app.sh {{ git_revision }}"
  register: output

# - name: "Migrations de la base mongoDb"
#   shell: "sudo /opt/flux-retour-cfas/run-migrations.sh"
#   register: output

- name: "Création des indexs de la base mongoDb"
  shell: "sudo /opt/flux-retour-cfas/run-indexes-creation.sh"
  register: output

- debug:
    var: output
