export interface Secteur {
  id: string;
  label: string;
  count: number;
}

export interface EffectifSansContrat {
  id: string;
  nom: string;
  prenom: string;
  date_inscription: string;
  secteur: string;
  formation: string;
  organisme: string;
}

export const SECTEURS_FIXTURES: Secteur[] = [
  { id: "agriculture-elevage", label: "Agriculture et élevage", count: 3 },
  { id: "automobile", label: "Automobile", count: 6 },
  { id: "batiment-travaux-publics", label: "Bâtiment et travaux publics (BTP)", count: 12 },
  { id: "communication-marketing", label: "Communication et marketing", count: 15 },
  { id: "hotellerie-restauration", label: "Hôtellerie et restauration", count: 4 },
  { id: "industrie-papier-imprimerie", label: "Industrie - Papier et imprimerie", count: 1 },
  { id: "industrie-textile-mode", label: "Industrie - Textile et mode", count: 2 },
  { id: "industrie-electronique", label: "Industrie - Électronique", count: 6 },
  { id: "informatique-telecommunication", label: "Informatique et télécommunication", count: 7 },
  { id: "logistique-transport", label: "Logistique et transport", count: 7 },
  { id: "sante", label: "Santé", count: 7 },
  { id: "service-personne", label: "Service à la personne", count: 10 },
  { id: "social", label: "Social", count: 12 },
  { id: "sport-animation-loisir", label: "Sport, animation et loisir", count: 5 },
  { id: "tourisme", label: "Tourisme", count: 3 },
];

export const EFFECTIFS_PAR_SECTEUR: Record<string, EffectifSansContrat[]> = {
  "communication-marketing": [
    {
      id: "1",
      nom: "Martin",
      prenom: "Sophie",
      date_inscription: "2025-09-15",
      secteur: "Communication et marketing",
      formation: "BTS Communication",
      organisme: "CFA Médias Paris",
    },
    {
      id: "2",
      nom: "Dubois",
      prenom: "Thomas",
      date_inscription: "2025-09-12",
      secteur: "Communication et marketing",
      formation: "Licence Pro Marketing Digital",
      organisme: "CFA Commerce Lyon",
    },
    {
      id: "3",
      nom: "Bernard",
      prenom: "Julie",
      date_inscription: "2025-09-10",
      secteur: "Communication et marketing",
      formation: "BTS Communication",
      organisme: "CFA Médias Paris",
    },
    {
      id: "4",
      nom: "Petit",
      prenom: "Lucas",
      date_inscription: "2025-09-08",
      secteur: "Communication et marketing",
      formation: "Bachelor Communication",
      organisme: "CFA Digital Bordeaux",
    },
    {
      id: "5",
      nom: "Robert",
      prenom: "Emma",
      date_inscription: "2025-09-05",
      secteur: "Communication et marketing",
      formation: "BTS Communication",
      organisme: "CFA Médias Paris",
    },
    {
      id: "6",
      nom: "Richard",
      prenom: "Hugo",
      date_inscription: "2025-09-03",
      secteur: "Communication et marketing",
      formation: "Licence Pro Marketing",
      organisme: "CFA Commerce Lyon",
    },
    {
      id: "7",
      nom: "Durand",
      prenom: "Léa",
      date_inscription: "2025-09-01",
      secteur: "Communication et marketing",
      formation: "BTS Communication",
      organisme: "CFA Médias Paris",
    },
    {
      id: "8",
      nom: "Leroy",
      prenom: "Nathan",
      date_inscription: "2025-08-28",
      secteur: "Communication et marketing",
      formation: "Bachelor Communication",
      organisme: "CFA Digital Bordeaux",
    },
    {
      id: "9",
      nom: "Moreau",
      prenom: "Clara",
      date_inscription: "2025-08-25",
      secteur: "Communication et marketing",
      formation: "BTS Communication",
      organisme: "CFA Médias Paris",
    },
    {
      id: "10",
      nom: "Simon",
      prenom: "Antoine",
      date_inscription: "2025-08-22",
      secteur: "Communication et marketing",
      formation: "Licence Pro Marketing Digital",
      organisme: "CFA Commerce Lyon",
    },
    {
      id: "11",
      nom: "Laurent",
      prenom: "Camille",
      date_inscription: "2025-08-20",
      secteur: "Communication et marketing",
      formation: "BTS Communication",
      organisme: "CFA Médias Paris",
    },
    {
      id: "12",
      nom: "Lefebvre",
      prenom: "Maxime",
      date_inscription: "2025-08-18",
      secteur: "Communication et marketing",
      formation: "Bachelor Communication",
      organisme: "CFA Digital Bordeaux",
    },
    {
      id: "13",
      nom: "Michel",
      prenom: "Manon",
      date_inscription: "2025-08-15",
      secteur: "Communication et marketing",
      formation: "BTS Communication",
      organisme: "CFA Médias Paris",
    },
    {
      id: "14",
      nom: "Garcia",
      prenom: "Tom",
      date_inscription: "2025-08-12",
      secteur: "Communication et marketing",
      formation: "Licence Pro Marketing",
      organisme: "CFA Commerce Lyon",
    },
    {
      id: "15",
      nom: "David",
      prenom: "Chloé",
      date_inscription: "2025-08-10",
      secteur: "Communication et marketing",
      formation: "BTS Communication",
      organisme: "CFA Médias Paris",
    },
  ],
  "batiment-travaux-publics": [
    {
      id: "16",
      nom: "Bertrand",
      prenom: "Alexandre",
      date_inscription: "2025-09-14",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Maçonnerie",
      organisme: "CFA BTP Marseille",
    },
    {
      id: "17",
      nom: "Rousseau",
      prenom: "Pierre",
      date_inscription: "2025-09-11",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Électricien",
      organisme: "CFA BTP Lille",
    },
    {
      id: "18",
      nom: "Vincent",
      prenom: "Louis",
      date_inscription: "2025-09-09",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Plombier",
      organisme: "CFA BTP Marseille",
    },
    {
      id: "19",
      nom: "Fournier",
      prenom: "Marc",
      date_inscription: "2025-09-06",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Menuisier",
      organisme: "CFA BTP Toulouse",
    },
    {
      id: "20",
      nom: "Girard",
      prenom: "François",
      date_inscription: "2025-09-04",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Maçonnerie",
      organisme: "CFA BTP Marseille",
    },
    {
      id: "21",
      nom: "Bonnet",
      prenom: "Jean",
      date_inscription: "2025-09-02",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Couvreur",
      organisme: "CFA BTP Lyon",
    },
    {
      id: "22",
      nom: "Dupont",
      prenom: "Michel",
      date_inscription: "2025-08-30",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Peintre",
      organisme: "CFA BTP Lille",
    },
    {
      id: "23",
      nom: "Lambert",
      prenom: "André",
      date_inscription: "2025-08-27",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Électricien",
      organisme: "CFA BTP Marseille",
    },
    {
      id: "24",
      nom: "Fontaine",
      prenom: "Jacques",
      date_inscription: "2025-08-24",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Plombier",
      organisme: "CFA BTP Toulouse",
    },
    {
      id: "25",
      nom: "Chevalier",
      prenom: "Georges",
      date_inscription: "2025-08-21",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Maçonnerie",
      organisme: "CFA BTP Lyon",
    },
    {
      id: "26",
      nom: "Garnier",
      prenom: "René",
      date_inscription: "2025-08-19",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Menuisier",
      organisme: "CFA BTP Lille",
    },
    {
      id: "27",
      nom: "Faure",
      prenom: "Henri",
      date_inscription: "2025-08-16",
      secteur: "Bâtiment et travaux publics (BTP)",
      formation: "CAP Couvreur",
      organisme: "CFA BTP Marseille",
    },
  ],
  automobile: [
    {
      id: "28",
      nom: "André",
      prenom: "Julien",
      date_inscription: "2025-09-13",
      secteur: "Automobile",
      formation: "CAP Maintenance véhicules",
      organisme: "CFA Auto Paris",
    },
    {
      id: "29",
      nom: "Mercier",
      prenom: "Théo",
      date_inscription: "2025-09-10",
      secteur: "Automobile",
      formation: "CAP Carrosserie",
      organisme: "CFA Auto Lyon",
    },
    {
      id: "30",
      nom: "Blanc",
      prenom: "Nicolas",
      date_inscription: "2025-09-07",
      secteur: "Automobile",
      formation: "CAP Maintenance véhicules",
      organisme: "CFA Auto Paris",
    },
    {
      id: "31",
      nom: "Guerin",
      prenom: "Mathis",
      date_inscription: "2025-09-04",
      secteur: "Automobile",
      formation: "CAP Peinture carrosserie",
      organisme: "CFA Auto Marseille",
    },
    {
      id: "32",
      nom: "Boyer",
      prenom: "Adam",
      date_inscription: "2025-09-01",
      secteur: "Automobile",
      formation: "CAP Maintenance véhicules",
      organisme: "CFA Auto Lyon",
    },
    {
      id: "33",
      nom: "Roux",
      prenom: "Raphaël",
      date_inscription: "2025-08-29",
      secteur: "Automobile",
      formation: "CAP Carrosserie",
      organisme: "CFA Auto Paris",
    },
  ],
  "agriculture-elevage": [
    {
      id: "34",
      nom: "Lemoine",
      prenom: "Baptiste",
      date_inscription: "2025-09-08",
      secteur: "Agriculture et élevage",
      formation: "CAP Métiers de l'agriculture",
      organisme: "CFA Agricole Rennes",
    },
    {
      id: "35",
      nom: "Gauthier",
      prenom: "Gabriel",
      date_inscription: "2025-08-25",
      secteur: "Agriculture et élevage",
      formation: "CAPA Palefrenier",
      organisme: "CFA Agricole Caen",
    },
    {
      id: "36",
      nom: "Perrin",
      prenom: "Étienne",
      date_inscription: "2025-08-15",
      secteur: "Agriculture et élevage",
      formation: "CAP Métiers de l'agriculture",
      organisme: "CFA Agricole Rennes",
    },
  ],
  "hotellerie-restauration": [
    {
      id: "37",
      nom: "Morel",
      prenom: "Océane",
      date_inscription: "2025-09-12",
      secteur: "Hôtellerie et restauration",
      formation: "CAP Cuisine",
      organisme: "CFA Hôtellerie Paris",
    },
    {
      id: "38",
      nom: "Giraud",
      prenom: "Sarah",
      date_inscription: "2025-09-05",
      secteur: "Hôtellerie et restauration",
      formation: "CAP Service",
      organisme: "CFA Hôtellerie Lyon",
    },
    {
      id: "39",
      nom: "Colin",
      prenom: "Anaïs",
      date_inscription: "2025-08-28",
      secteur: "Hôtellerie et restauration",
      formation: "CAP Pâtisserie",
      organisme: "CFA Hôtellerie Paris",
    },
    {
      id: "40",
      nom: "Barbier",
      prenom: "Inès",
      date_inscription: "2025-08-20",
      secteur: "Hôtellerie et restauration",
      formation: "CAP Cuisine",
      organisme: "CFA Hôtellerie Nice",
    },
  ],
  "informatique-telecommunication": [
    {
      id: "41",
      nom: "Arnaud",
      prenom: "Maxence",
      date_inscription: "2025-09-14",
      secteur: "Informatique et télécommunication",
      formation: "BTS SIO",
      organisme: "CFA Numérique Paris",
    },
    {
      id: "42",
      nom: "Renard",
      prenom: "Enzo",
      date_inscription: "2025-09-11",
      secteur: "Informatique et télécommunication",
      formation: "BTS SIO",
      organisme: "CFA Numérique Lyon",
    },
    {
      id: "43",
      nom: "Picard",
      prenom: "Valentin",
      date_inscription: "2025-09-08",
      secteur: "Informatique et télécommunication",
      formation: "Bachelor Développeur",
      organisme: "CFA Tech Bordeaux",
    },
    {
      id: "44",
      nom: "Roger",
      prenom: "Arthur",
      date_inscription: "2025-09-05",
      secteur: "Informatique et télécommunication",
      formation: "BTS SIO",
      organisme: "CFA Numérique Paris",
    },
    {
      id: "45",
      nom: "Vidal",
      prenom: "Quentin",
      date_inscription: "2025-09-02",
      secteur: "Informatique et télécommunication",
      formation: "BTS SIO",
      organisme: "CFA Numérique Lyon",
    },
    {
      id: "46",
      nom: "Bourgeois",
      prenom: "Louis",
      date_inscription: "2025-08-30",
      secteur: "Informatique et télécommunication",
      formation: "Bachelor Développeur",
      organisme: "CFA Tech Bordeaux",
    },
    {
      id: "47",
      nom: "Lemaire",
      prenom: "Alexandre",
      date_inscription: "2025-08-27",
      secteur: "Informatique et télécommunication",
      formation: "BTS SIO",
      organisme: "CFA Numérique Paris",
    },
  ],
  "logistique-transport": [
    {
      id: "48",
      nom: "Meunier",
      prenom: "Théo",
      date_inscription: "2025-09-13",
      secteur: "Logistique et transport",
      formation: "CAP Conducteur livreur",
      organisme: "CFA Transport Lyon",
    },
    {
      id: "49",
      nom: "Brun",
      prenom: "Hugo",
      date_inscription: "2025-09-10",
      secteur: "Logistique et transport",
      formation: "CAP Agent magasinier",
      organisme: "CFA Logistique Lille",
    },
    {
      id: "50",
      nom: "Lemoine",
      prenom: "Nathan",
      date_inscription: "2025-09-07",
      secteur: "Logistique et transport",
      formation: "CAP Conducteur livreur",
      organisme: "CFA Transport Lyon",
    },
    {
      id: "51",
      nom: "Roussel",
      prenom: "Lucas",
      date_inscription: "2025-09-04",
      secteur: "Logistique et transport",
      formation: "BTS Transport",
      organisme: "CFA Transport Paris",
    },
    {
      id: "52",
      nom: "Martinez",
      prenom: "Tom",
      date_inscription: "2025-09-01",
      secteur: "Logistique et transport",
      formation: "CAP Agent magasinier",
      organisme: "CFA Logistique Lille",
    },
    {
      id: "53",
      nom: "Gonzalez",
      prenom: "Mathis",
      date_inscription: "2025-08-29",
      secteur: "Logistique et transport",
      formation: "CAP Conducteur livreur",
      organisme: "CFA Transport Lyon",
    },
    {
      id: "54",
      nom: "Lopez",
      prenom: "Antoine",
      date_inscription: "2025-08-26",
      secteur: "Logistique et transport",
      formation: "BTS Transport",
      organisme: "CFA Transport Paris",
    },
  ],
  sante: [
    {
      id: "55",
      nom: "Sanchez",
      prenom: "Jade",
      date_inscription: "2025-09-14",
      secteur: "Santé",
      formation: "CAP Petite enfance",
      organisme: "CFA Santé Paris",
    },
    {
      id: "56",
      nom: "Fernandez",
      prenom: "Lola",
      date_inscription: "2025-09-11",
      secteur: "Santé",
      formation: "CAP Accompagnant éducatif",
      organisme: "CFA Santé Lyon",
    },
    {
      id: "57",
      nom: "Rodriguez",
      prenom: "Luna",
      date_inscription: "2025-09-08",
      secteur: "Santé",
      formation: "CAP Petite enfance",
      organisme: "CFA Santé Paris",
    },
    {
      id: "58",
      nom: "Martin",
      prenom: "Rose",
      date_inscription: "2025-09-05",
      secteur: "Santé",
      formation: "CAP Accompagnant éducatif",
      organisme: "CFA Santé Marseille",
    },
    {
      id: "59",
      nom: "Hernandez",
      prenom: "Alice",
      date_inscription: "2025-09-02",
      secteur: "Santé",
      formation: "CAP Petite enfance",
      organisme: "CFA Santé Lyon",
    },
    {
      id: "60",
      nom: "Perez",
      prenom: "Zoé",
      date_inscription: "2025-08-30",
      secteur: "Santé",
      formation: "CAP Accompagnant éducatif",
      organisme: "CFA Santé Paris",
    },
    {
      id: "61",
      nom: "Gomez",
      prenom: "Louise",
      date_inscription: "2025-08-27",
      secteur: "Santé",
      formation: "CAP Petite enfance",
      organisme: "CFA Santé Marseille",
    },
  ],
  "service-personne": [
    {
      id: "62",
      nom: "Torres",
      prenom: "Léa",
      date_inscription: "2025-09-13",
      secteur: "Service à la personne",
      formation: "CAP Coiffure",
      organisme: "CFA Service Paris",
    },
    {
      id: "63",
      nom: "Ramirez",
      prenom: "Emma",
      date_inscription: "2025-09-10",
      secteur: "Service à la personne",
      formation: "CAP Esthétique",
      organisme: "CFA Beauté Lyon",
    },
    {
      id: "64",
      nom: "Flores",
      prenom: "Chloé",
      date_inscription: "2025-09-07",
      secteur: "Service à la personne",
      formation: "CAP Coiffure",
      organisme: "CFA Service Paris",
    },
    {
      id: "65",
      nom: "Jimenez",
      prenom: "Manon",
      date_inscription: "2025-09-04",
      secteur: "Service à la personne",
      formation: "CAP Esthétique",
      organisme: "CFA Beauté Marseille",
    },
    {
      id: "66",
      nom: "Morales",
      prenom: "Camille",
      date_inscription: "2025-09-01",
      secteur: "Service à la personne",
      formation: "CAP Coiffure",
      organisme: "CFA Service Lyon",
    },
    {
      id: "67",
      nom: "Ruiz",
      prenom: "Clara",
      date_inscription: "2025-08-29",
      secteur: "Service à la personne",
      formation: "CAP Esthétique",
      organisme: "CFA Beauté Paris",
    },
    {
      id: "68",
      nom: "Alvarez",
      prenom: "Léna",
      date_inscription: "2025-08-26",
      secteur: "Service à la personne",
      formation: "CAP Coiffure",
      organisme: "CFA Service Marseille",
    },
    {
      id: "69",
      nom: "Castillo",
      prenom: "Lucie",
      date_inscription: "2025-08-23",
      secteur: "Service à la personne",
      formation: "CAP Esthétique",
      organisme: "CFA Beauté Lyon",
    },
    {
      id: "70",
      nom: "Ortiz",
      prenom: "Anna",
      date_inscription: "2025-08-20",
      secteur: "Service à la personne",
      formation: "CAP Coiffure",
      organisme: "CFA Service Paris",
    },
    {
      id: "71",
      nom: "Reyes",
      prenom: "Nina",
      date_inscription: "2025-08-17",
      secteur: "Service à la personne",
      formation: "CAP Esthétique",
      organisme: "CFA Beauté Marseille",
    },
  ],
  social: [
    {
      id: "72",
      nom: "Cruz",
      prenom: "Elisa",
      date_inscription: "2025-09-14",
      secteur: "Social",
      formation: "CAP Accompagnant éducatif",
      organisme: "CFA Social Paris",
    },
    {
      id: "73",
      nom: "Mendoza",
      prenom: "Eva",
      date_inscription: "2025-09-11",
      secteur: "Social",
      formation: "CAP Assistant technique",
      organisme: "CFA Social Lyon",
    },
    {
      id: "74",
      nom: "Vazquez",
      prenom: "Laura",
      date_inscription: "2025-09-08",
      secteur: "Social",
      formation: "CAP Accompagnant éducatif",
      organisme: "CFA Social Paris",
    },
    {
      id: "75",
      nom: "Ramos",
      prenom: "Juliette",
      date_inscription: "2025-09-05",
      secteur: "Social",
      formation: "CAP Assistant technique",
      organisme: "CFA Social Marseille",
    },
    {
      id: "76",
      nom: "Diaz",
      prenom: "Victoria",
      date_inscription: "2025-09-02",
      secteur: "Social",
      formation: "CAP Accompagnant éducatif",
      organisme: "CFA Social Lyon",
    },
    {
      id: "77",
      nom: "Romero",
      prenom: "Lina",
      date_inscription: "2025-08-30",
      secteur: "Social",
      formation: "CAP Assistant technique",
      organisme: "CFA Social Paris",
    },
    {
      id: "78",
      nom: "Gutierrez",
      prenom: "Lily",
      date_inscription: "2025-08-27",
      secteur: "Social",
      formation: "CAP Accompagnant éducatif",
      organisme: "CFA Social Marseille",
    },
    {
      id: "79",
      nom: "Aguilar",
      prenom: "Maëlys",
      date_inscription: "2025-08-24",
      secteur: "Social",
      formation: "CAP Assistant technique",
      organisme: "CFA Social Lyon",
    },
    {
      id: "80",
      nom: "Medina",
      prenom: "Olivia",
      date_inscription: "2025-08-21",
      secteur: "Social",
      formation: "CAP Accompagnant éducatif",
      organisme: "CFA Social Paris",
    },
    {
      id: "81",
      nom: "Navarro",
      prenom: "Mathilde",
      date_inscription: "2025-08-18",
      secteur: "Social",
      formation: "CAP Assistant technique",
      organisme: "CFA Social Marseille",
    },
    {
      id: "82",
      nom: "Chavez",
      prenom: "Agathe",
      date_inscription: "2025-08-15",
      secteur: "Social",
      formation: "CAP Accompagnant éducatif",
      organisme: "CFA Social Lyon",
    },
    {
      id: "83",
      nom: "Silva",
      prenom: "Charlotte",
      date_inscription: "2025-08-12",
      secteur: "Social",
      formation: "CAP Assistant technique",
      organisme: "CFA Social Paris",
    },
  ],
  "sport-animation-loisir": [
    {
      id: "84",
      nom: "Delgado",
      prenom: "Matteo",
      date_inscription: "2025-09-12",
      secteur: "Sport, animation et loisir",
      formation: "BPJEPS Animation",
      organisme: "CFA Sport Paris",
    },
    {
      id: "85",
      nom: "Herrera",
      prenom: "Noah",
      date_inscription: "2025-09-09",
      secteur: "Sport, animation et loisir",
      formation: "BPJEPS Sport",
      organisme: "CFA Sport Lyon",
    },
    {
      id: "86",
      nom: "Vargas",
      prenom: "Ethan",
      date_inscription: "2025-09-06",
      secteur: "Sport, animation et loisir",
      formation: "BPJEPS Animation",
      organisme: "CFA Sport Marseille",
    },
    {
      id: "87",
      nom: "Castro",
      prenom: "Adam",
      date_inscription: "2025-09-03",
      secteur: "Sport, animation et loisir",
      formation: "BPJEPS Sport",
      organisme: "CFA Sport Paris",
    },
    {
      id: "88",
      nom: "Ortega",
      prenom: "Gabriel",
      date_inscription: "2025-08-31",
      secteur: "Sport, animation et loisir",
      formation: "BPJEPS Animation",
      organisme: "CFA Sport Lyon",
    },
  ],
  tourisme: [
    {
      id: "89",
      nom: "Mendez",
      prenom: "Jade",
      date_inscription: "2025-09-11",
      secteur: "Tourisme",
      formation: "BTS Tourisme",
      organisme: "CFA Tourisme Paris",
    },
    {
      id: "90",
      nom: "Moreno",
      prenom: "Lola",
      date_inscription: "2025-09-04",
      secteur: "Tourisme",
      formation: "BTS Tourisme",
      organisme: "CFA Tourisme Nice",
    },
    {
      id: "91",
      nom: "Soto",
      prenom: "Luna",
      date_inscription: "2025-08-28",
      secteur: "Tourisme",
      formation: "BTS Tourisme",
      organisme: "CFA Tourisme Paris",
    },
  ],
  "industrie-papier-imprimerie": [
    {
      id: "92",
      nom: "Rivera",
      prenom: "Alexandre",
      date_inscription: "2025-09-07",
      secteur: "Industrie - Papier et imprimerie",
      formation: "CAP Imprimerie",
      organisme: "CFA Industrie Paris",
    },
  ],
  "industrie-textile-mode": [
    {
      id: "93",
      nom: "Nunez",
      prenom: "Sarah",
      date_inscription: "2025-09-10",
      secteur: "Industrie - Textile et mode",
      formation: "CAP Couture",
      organisme: "CFA Mode Paris",
    },
    {
      id: "94",
      nom: "Pena",
      prenom: "Léa",
      date_inscription: "2025-09-02",
      secteur: "Industrie - Textile et mode",
      formation: "CAP Couture",
      organisme: "CFA Mode Lyon",
    },
  ],
  "industrie-electronique": [
    {
      id: "95",
      nom: "Santos",
      prenom: "Lucas",
      date_inscription: "2025-09-13",
      secteur: "Industrie - Électronique",
      formation: "CAP Électronique",
      organisme: "CFA Industrie Lyon",
    },
    {
      id: "96",
      nom: "Torres",
      prenom: "Hugo",
      date_inscription: "2025-09-10",
      secteur: "Industrie - Électronique",
      formation: "BTS Électronique",
      organisme: "CFA Tech Paris",
    },
    {
      id: "97",
      nom: "Mendoza",
      prenom: "Nathan",
      date_inscription: "2025-09-07",
      secteur: "Industrie - Électronique",
      formation: "CAP Électronique",
      organisme: "CFA Industrie Lyon",
    },
    {
      id: "98",
      nom: "Chavez",
      prenom: "Théo",
      date_inscription: "2025-09-04",
      secteur: "Industrie - Électronique",
      formation: "BTS Électronique",
      organisme: "CFA Tech Marseille",
    },
    {
      id: "99",
      nom: "Reyes",
      prenom: "Tom",
      date_inscription: "2025-09-01",
      secteur: "Industrie - Électronique",
      formation: "CAP Électronique",
      organisme: "CFA Industrie Lyon",
    },
    {
      id: "100",
      nom: "Guerrero",
      prenom: "Mathis",
      date_inscription: "2025-08-29",
      secteur: "Industrie - Électronique",
      formation: "BTS Électronique",
      organisme: "CFA Tech Paris",
    },
  ],
};

export const EFFECTIFS_DEJA_TRAITES: EffectifSansContrat[] = [
  {
    id: "200",
    nom: "Fontaine",
    prenom: "Paul",
    date_inscription: "2025-07-10",
    secteur: "Informatique et télécommunication",
    formation: "BTS SIO",
    organisme: "CFA Numérique Paris",
  },
  {
    id: "201",
    nom: "Benoit",
    prenom: "Marie",
    date_inscription: "2025-07-08",
    secteur: "Communication et marketing",
    formation: "BTS Communication",
    organisme: "CFA Médias Paris",
  },
  {
    id: "202",
    nom: "Lemoine",
    prenom: "Jean",
    date_inscription: "2025-07-06",
    secteur: "Automobile",
    formation: "CAP Maintenance véhicules",
    organisme: "CFA Auto Paris",
  },
  {
    id: "203",
    nom: "Dupuis",
    prenom: "Sophie",
    date_inscription: "2025-07-04",
    secteur: "Hôtellerie et restauration",
    formation: "CAP Cuisine",
    organisme: "CFA Hôtellerie Paris",
  },
  {
    id: "204",
    nom: "Marchand",
    prenom: "Pierre",
    date_inscription: "2025-07-02",
    secteur: "Bâtiment et travaux publics (BTP)",
    formation: "CAP Maçonnerie",
    organisme: "CFA BTP Marseille",
  },
  {
    id: "205",
    nom: "Lefevre",
    prenom: "Julie",
    date_inscription: "2025-06-30",
    secteur: "Service à la personne",
    formation: "CAP Coiffure",
    organisme: "CFA Service Paris",
  },
  {
    id: "206",
    nom: "Rousseau",
    prenom: "Antoine",
    date_inscription: "2025-06-28",
    secteur: "Social",
    formation: "CAP Accompagnant éducatif",
    organisme: "CFA Social Paris",
  },
  {
    id: "207",
    nom: "Vincent",
    prenom: "Clara",
    date_inscription: "2025-06-26",
    secteur: "Logistique et transport",
    formation: "CAP Conducteur livreur",
    organisme: "CFA Transport Lyon",
  },
  {
    id: "208",
    nom: "Fournier",
    prenom: "Thomas",
    date_inscription: "2025-06-24",
    secteur: "Santé",
    formation: "CAP Petite enfance",
    organisme: "CFA Santé Paris",
  },
  {
    id: "209",
    nom: "Girard",
    prenom: "Emma",
    date_inscription: "2025-06-22",
    secteur: "Sport, animation et loisir",
    formation: "BPJEPS Animation",
    organisme: "CFA Sport Paris",
  },
  {
    id: "210",
    nom: "Bonnet",
    prenom: "Lucas",
    date_inscription: "2025-06-20",
    secteur: "Industrie - Électronique",
    formation: "CAP Électronique",
    organisme: "CFA Industrie Lyon",
  },
  {
    id: "211",
    nom: "Dupont",
    prenom: "Léa",
    date_inscription: "2025-06-18",
    secteur: "Tourisme",
    formation: "BTS Tourisme",
    organisme: "CFA Tourisme Paris",
  },
];
