- name: Vérification de l'existence du groupe "mna"
  group:
    name: mna
    state: present

- name: "Création utilisateur {{ habilitation.username }}"
  user:
    name: "{{ habilitation.username }}"
    password: "{{ vault[env_type].FLUX_RETOUR_CFAS_HABILITATION_PASSWORD }}"
    update_password: on_create
    shell: /bin/bash
    groups: sudo,mna
    append: yes
  register: user

- name: Force password update
  command: "chage -d 0 {{ habilitation.username }}"
  when: user.changed

- name: "Ajout des clés d'autorisation à l'utilisateur {{habilitation.username}}"
  authorized_key:
    user: "{{ habilitation.username }}"
    state: present
    key: '{{key}}'
  loop: "{{ habilitation.authorized_keys }}"
  loop_control:
    loop_var: key
