- name: Ignore ICMP broadcast requests
  #Ignores broadcast pings, reducing the damage of SMURF attacks.
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '1'
    sysctl_set: yes

- name: Ignore send redirects
  # Prevents hijacking of routing path by only allowing redirects from gateways known in our routing table.
  ansible.posix.sysctl:
    name: "net.ipv4.conf.{{item}}.send_redirects"
    value: '0'
    sysctl_set: yes
  with_items:
    - "all"
    - "default"

- name: Ignore ICMP redirects  (accept_redirects)
  ansible.posix.sysctl:
    name: "net.ipv4.conf.{{item}}.accept_redirects"
    value: '0'
    sysctl_set: yes
  with_items:
    - "all"
    - "default"
-
  name: Ignore ICMP redirects  (secure_redirects)
  ansible.posix.sysctl:
    name: "net.ipv4.conf.{{item}}.secure_redirects"
    value: '0'
    sysctl_set: yes
  with_items:
    - "all"
    - "default"

- name: Some routers ignore RFC 1122 and send junk error responses that get logged
  ansible.posix.sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: '1'
    sysctl_set: yes

- name: Block SYN attacks
  #Implements TCP Syncookies. When the connection queue is filled, we drop back to this; we lose TCP extensions as a trade-off for any connections made as Syncookies, but we would otherwise not be making said connections at all so this is a net gain.
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: yes

- name: IP Spoofing protection
  ansible.posix.sysctl:
    name: "net.ipv4.conf.{{item}}.rp_filter"
    value: '1'
    sysctl_set: yes
  with_items:
    - "all"
    - "default"

- name: Disable source packet routing
  ansible.posix.sysctl:
    name: "net.{{item}}.conf.all.accept_source_route"
    value: '0'
    sysctl_set: yes
  with_items:
    - "ipv4"
    - "ipv6"
