- name: Install fail2ban packages
  apt:
    name: [ 'fail2ban' ]

- name: Copy fail2ban actions
  copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/action.d"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "fail2ban/action.d/*"
  notify: restart-fail2ban

- name: Copy fail2ban filters
  copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/filter.d"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "fail2ban/filter.d/*"
  notify: restart-fail2ban

- name: Copy fail2ban jails
  copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/jail.d"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "fail2ban/jail.d/*"
  notify: restart-fail2ban
