- name: Create /var/log/data-jobs
  file:
    path: /var/log/data-jobs
    state: directory
    owner: root
    group: root
    mode: 700

- name: Add CRON to run jobs processing application data everyday at 02:30AM
  become: true
  cron:
    name: "Run daily jobs each day at 02h30"
    minute: "30"
    hour: "2"
    job: "bash /opt/flux-retour-cfas/tools/cron-data-jobs/run-daily-jobs.sh"
    state: absent

- name: Add CRON to run fiabilité analyses on data received in last 24hours everyday at 11:15AM
  become: true
  cron:
    name: "Run analyses fiabilité données reçues job each day at 11h15"
    minute: "15"
    hour: "11"
    job: "bash /opt/flux-retour-cfas/tools/cron-data-jobs/run-analyse-fiabilite-donnees-recues-job.sh"
    state: absent

- name: Add CRON to archive dossiersApprenants every 1rst day of the month at 12:45AM
  become: true
  cron:
    name: "Run archive dossiers apprenants & effectifs job each first day of month at 12h45"
    minute: "45"
    hour: "12"
    day: "1"
    job: "bash /opt/flux-retour-cfas/tools/cron-data-jobs/run-archive-job.sh"
    state: absent
