export interface FieldConfig {
  type: "string" | "date" | "boolean";
  mandatory: boolean;
}

export const televersementHeaders: Record<string, FieldConfig> = {
  nom_apprenant: { type: "string", mandatory: true },
  prenom_apprenant: { type: "string", mandatory: true },
  date_de_naissance_apprenant: { type: "date", mandatory: true },
  sexe_apprenant: { type: "string", mandatory: true },
  code_postal_de_naissance_apprenant: { type: "string", mandatory: false },
  email_contact: { type: "string", mandatory: true },
  adresse_apprenant: { type: "string", mandatory: true },
  code_postal_apprenant: { type: "string", mandatory: true },
  ine_apprenant: { type: "string", mandatory: false },
  tel_apprenant: { type: "string", mandatory: false },
  rqth_apprenant: { type: "boolean", mandatory: false },
  date_rqth_apprenant: { type: "date", mandatory: false },
  responsable_apprenant_mail1: { type: "string", mandatory: false },
  responsable_apprenant_mail2: { type: "string", mandatory: false },
  dernier_organisme_uai: { type: "string", mandatory: false },
  derniere_situation: { type: "string", mandatory: false },
  type_cfa: { type: "string", mandatory: false },
  dernier_organisme_departement: { type: "string", mandatory: false },
  etablissement_responsable_uai: { type: "string", mandatory: false },
  etablissement_responsable_siret: { type: "string", mandatory: false },
  etablissement_formateur_uai: { type: "string", mandatory: false },
  etablissement_formateur_siret: { type: "string", mandatory: false },
  etablissement_lieu_de_formation_uai: { type: "string", mandatory: false },
  etablissement_lieu_de_formation_siret: { type: "string", mandatory: false },
  annee_scolaire: { type: "string", mandatory: true },
  annee_formation: { type: "string", mandatory: true },
  formation_rncp: { type: "string", mandatory: false },
  formation_cfd: { type: "string", mandatory: false },
  date_inscription_formation: { type: "date", mandatory: false },
  date_entree_formation: { type: "date", mandatory: false },
  date_fin_formation: { type: "date", mandatory: false },
  duree_theorique_formation_mois: { type: "string", mandatory: false },
  libelle_court_formation: { type: "string", mandatory: false },
  obtention_diplome_formation: { type: "boolean", mandatory: false },
  date_obtention_diplome_formation: { type: "date", mandatory: false },
  date_exclusion_formation: { type: "date", mandatory: false },
  cause_exclusion_formation: { type: "string", mandatory: false },
  formation_presentielle: { type: "boolean", mandatory: false },
  nom_referent_handicap_formation: { type: "string", mandatory: false },
  prenom_referent_handicap_formation: { type: "string", mandatory: false },
  email_referent_handicap_formation: { type: "string", mandatory: false },
  contrat_date_debut: { type: "date", mandatory: false },
  contrat_date_fin: { type: "date", mandatory: false },
  siret_employeur: { type: "string", mandatory: false },
  contrat_date_rupture: { type: "date", mandatory: false },
  cause_rupture_contrat: { type: "string", mandatory: false },
  contrat_date_debut_2: { type: "date", mandatory: false },
  contrat_date_fin_2: { type: "date", mandatory: false },
  siret_employeur_2: { type: "string", mandatory: false },
  contrat_date_rupture_2: { type: "date", mandatory: false },
  cause_rupture_contrat_2: { type: "string", mandatory: false },
  contrat_date_debut_3: { type: "date", mandatory: false },
  contrat_date_fin_3: { type: "date", mandatory: false },
  siret_employeur_3: { type: "string", mandatory: false },
  contrat_date_rupture_3: { type: "date", mandatory: false },
  cause_rupture_contrat_3: { type: "string", mandatory: false },
  contrat_date_debut_4: { type: "date", mandatory: false },
  contrat_date_fin_4: { type: "date", mandatory: false },
  siret_employeur_4: { type: "string", mandatory: false },
  contrat_date_rupture_4: { type: "date", mandatory: false },
  cause_rupture_contrat_4: { type: "string", mandatory: false },
};
