// auto-generated by bson-schema-to-typescript

export interface AuditLog {
  /**
   * L'action en cours
   */
  action: string;
  /**
   * La date de l'évènement
   */
  date: Date;
  data?: unknown;
}
