// auto-generated by bson-schema-to-typescript

export interface BassinsEmploi {
  /**
   * Code commune
   */
  code_commune: string;
  /**
   * Code zone d'emploi
   */
  code_zone_emploi: string;
}
