// auto-generated by bson-schema-to-typescript

export interface ContratsDeca {
  alternant: {
    /**
     * Le nom de l'alternant
     */
    nom: string;
    /**
     * Le prenom de l'alternant
     */
    prenom: string;
    /**
     * Le sexe de l'alternant
     */
    sexe: string;
    /**
     * La date de naissance de l'alternant
     */
    dateNaissance: string;
    /**
     * Le département de naissance de l'alternant
     */
    departementNaissance: string;
    /**
     * Le code de la nationalité de l'alternant
     */
    nationalite?: number | null;
    /**
     * Indique si l'alternant est identifié comme porteur d'un handicap
     */
    handicap?: boolean | null;
    /**
     * L'adresse email de l'alternant
     */
    courriel?: string | null;
    /**
     * Le numéro de téléphone de l'alternant
     */
    telephone?: string | null;
    adresse?: {
      /**
       * Le numéro de l'adresse
       */
      numero?: number | null;
      /**
       * La voie de l'adresse
       */
      voie?: string | null;
      /**
       * Le code postal de l'adresse
       */
      codePostal?: string | null;
    };
    /**
     * La dernière classe de l'apprenant
     */
    derniereClasse?: string | null;
  };
  formation: {
    /**
     * La date de début de la formation
     */
    dateDebutFormation: string;
    /**
     * La date de fin de la formation
     */
    dateFinFormation: string;
    /**
     * Le code diplôme de la formation
     */
    codeDiplome: string;
    /**
     * Le code RNCP de la formation
     */
    rncp?: string | null;
    /**
     * L'adresse email de l'alternant
     */
    intituleOuQualification?: string | null;
  };
  etablissementFormation: {
    /**
     * Le siret de l'établissement de la formation
     */
    siret?: string | null;
  };
  organismeFormationResponsable: {
    /**
     * L'UAI de l'organisme responsable
     */
    uaiCfa?: string | null;
    /**
     * Le SIRET de l'organisme responsable
     */
    siret?: string | null;
  };
  detailsContrat: {
    /**
     * Le numéro du contrat
     */
    noContrat: string;
    /**
     * La date de début du contrat
     */
    dateDebutContrat: string;
    /**
     * La date de fin du contrat
     */
    dateFinContrat: string;
    /**
     * Le statut du contrat
     */
    statut: string;
    /**
     * La date d'effet de l'avenant du contrat
     */
    dateEffetAvenant?: string | null;
    /**
     * Le numéro de l'avenant du contrat
     */
    noAvenant?: string | null;
  };
  rupture?: null;
  employeur: {
    /**
     * Le code IDCC de l'employeur
     */
    codeIdcc: string;
  };
  /**
   * Date d'ajout en base de données
   */
  created_at: Date;
}
