// auto-generated by bson-schema-to-typescript

import type { Jsonify } from "type-fest";

export interface FiabilisationUaiSiret {
  created_at?: Date;
  /**
   * Statut de fiabilisation du couple UAI SIRET
   */
  type?:
    | "FIABLE"
    | "A_FIABILISER"
    | "NON_FIABILISABLE_INEXISTANT"
    | "NON_FIABILISABLE_PB_COLLECTE"
    | "NON_FIABILISABLE_UAI_VALIDEE"
    | "NON_FIABILISABLE_UAI_NON_VALIDEE";
  /**
   * L'UAI du couple à fiabiliser
   */
  uai?: string;
  /**
   * Le SIRET du couple à fiabiliser
   */
  siret?: string | null;
  /**
   * L'UAI fiable lié au couple à fiabiliser
   */
  uai_fiable?: string;
  /**
   * Le SIRET fiable lié au couple à fiabiliser
   */
  siret_fiable?: string;
}

export type FiabilisationUaiSiretJson = Jsonify<FiabilisationUaiSiret>;
