// auto-generated by bson-schema-to-typescript
import type { ObjectId } from "mongodb";

export interface Invitation {
  /**
   * Jeton d'invitation
   */
  token: string;
  /**
   * Email destinataire
   */
  email: string;
  /**
   * Organisation cible de l'invitation
   */
  organisation_id: ObjectId;
  /**
   * Auteur de l'invitation
   */
  author_id: ObjectId;
  /**
   * Date de création en base de données
   */
  created_at: Date;
}
