// auto-generated by bson-schema-to-typescript

export interface JobEvent {
  /**
   * Le nom du job
   */
  jobname: string;
  /**
   * La date de l'evenement
   */
  date: Date;
  /**
   * L'action en cours
   */
  action: string;
  /**
   * La donnée liéé à l'action
   */
  data?: any;
}
