// auto-generated by bson-schema-to-typescript

export interface Rome {
  /**
   * Code ROME
   */
  code: string;
  /**
   * Label fiche métier
   */
  label_fiche: string;
  /**
   * Label domaine professionnel
   */
  label_domaine: string;
  /**
   * Label famille de métier
   */
  label_famille: string;
}
