// auto-generated by bson-schema-to-typescript
import type { ObjectId } from "mongodb";

export interface UsersMigration {
  /**
   * Email utilisateur
   */
  email: string;
  /**
   * Le mot de passe hashé
   */
  password: string;
  /**
   * civilité
   */
  civility: "Madame" | "Monsieur";
  /**
   * Le nom de l'utilisateur
   */
  nom: string;
  /**
   * Le prénom de l'utilisateur
   */
  prenom: string;
  /**
   * Le téléphone de l'utilisateur
   */
  telephone?: string;
  /**
   * La fonction de l'utilisateur
   */
  fonction?: string;
  /**
   * Organisation à laquelle appartient l'utilisateur
   */
  organisation_id: ObjectId;
  /**
   * Statut du compte
   */
  account_status: "PENDING_EMAIL_VALIDATION" | "PENDING_ADMIN_VALIDATION" | "CONFIRMED";
  /**
   * Version des cgu accepté par l'utilisateur
   */
  has_accept_cgu_version?: string;
  /**
   * Date de création du compte
   */
  created_at?: Date;
  /**
   * Date de dernière connexion
   */
  last_connection?: Date;
  /**
   * Historique des dates de connexion
   */
  connection_history?: Date[];
  /**
   * true si besoin de reset le token
   */
  invalided_token?: boolean;
  /**
   * Date de dernière mise à jour mot de passe
   */
  password_updated_at?: Date;
  /**
   * Date d'envoi de la relance email pour données manquantes
   */
  reminder_missing_data_sent_date?: Date;
  /**
   * Date d'envoi de la relance email pour configuration et données manquantes
   */
  reminder_missing_configuration_and_data_sent_date?: Date;
  emails?: {
    token: string;
    templateName: string;
    payload?: any;
    sendDates: Date[];
    openDate?: Date;
    messageIds?: string[];
    error?: {
      type?: "fatal" | "soft_bounce" | "hard_bounce" | "complaint" | "invalid_email" | "blocked" | "error";
      message?: string;
    }[];
  }[];
  /**
   * unsubscribe email
   */
  unsubscribe?: boolean;
}
