name: Manual Image Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to build (use beta or rc)
        type: string
        required: true
      environment:
        description: The environment to deploy to
        type: choice
        required: true
        options:
          - recette
          - preprod

jobs:
  npm-packages-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Clone mna-npm-check repository
        uses: actions/checkout@v6
        with:
          repository: mission-apprentissage/mna-npm-check
          path: mna-npm-check

      - name: Analyze NPM dependancies
        run: mna-npm-check/npm-check.sh -p .

  release:
    if: ${{ success() }}
    needs: ["npm-packages-check"]
    concurrency:
      group: "build-${{ github.workflow }}-${{ github.ref }}"
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.TOKEN_MNA_SHARED }}
          persist-credentials: false
          submodules: true
          fetch-depth: 0
          fetch-tags: true

      - name: Initialize the GnuPG keyring
        run: |
          echo -n "$OPENPGP_KEY" | gpg --import
        env:
          OPENPGP_KEY: ${{ secrets.OPENPGP_PRIVATE_SUBKEY }}

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 22.6

      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            .yarn/install-state.gz
            .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-
          save-always: true

      - name: Install dependencies
        run: yarn install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: bump and release
        run: .bin/mna-tdb app:build "${{ inputs.version }}" push "${{ inputs.environment }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}

  deploy:
    concurrency:
      group: "deploy-${{ github.workflow }}-${{ github.ref }}"
    needs: ["release"]
    name: Deploy ${{ inputs.version }} on ${{ inputs.environment }}
    uses: "./.github/workflows/_deploy.yml"
    with:
      environment: ${{ inputs.environment }}
      app_version: ${{ inputs.version }}
    secrets:
      DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
      SLACK_WEBHOOK_NOTIF: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_WEBHOOK_ALERTING: ${{ secrets.SLACK_WEBHOOK_ALERTING }}
      OPENPGP_PRIVATE_SUBKEY: ${{ secrets.OPENPGP_PRIVATE_SUBKEY }}
      TOKEN_MNA_SHARED: ${{ secrets.TOKEN_MNA_SHARED }}
