name: Cron Job pour import dossiers apprenants en Recette
on:
  # Note: only schedules in default branch (i.e master) are run
  schedule: 
    - cron: "0 4 * * *"
env:
  API_URL: https://cfas-recette.apprentissage.beta.gouv.fr
  API_USERNAME: ${{ secrets.API_RECETTE_USERNAME }}
  API_PASSWORD: ${{ secrets.API_RECETTE_PASSWORD }}
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: sven/recette/send-dossiers-apprenant
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: |
          make install-server
          echo "installed"

      - name: Run Job to send "dossiers apprenants" to recette plaform
        run: |
          node server/tests/recette/jobs/send-dossiers-apprenants/index.js
