# name: Release version develop
# on:
#   push:
#     branches: [develop]

# jobs:
#   release:
#     # avoids buggy Github Actions behaviour triggering infinite loop of release commits
#     if: "!startsWith(github.event.head_commit.message, 'chore(release')"
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout project
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#           persist-credentials: false

#       - uses: actions/setup-node@v1
#         with:
#           node-version: 16.6.0
#       - uses: actions/cache@v2
#         with:
#           path: "**/node_modules"
#           key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-

#       - name: Run yarn Install
#         run: yarn install

#       - name: bump
#         run: yarn npm:release
#         env:
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
